<table  width="100%" style="border:none !important;">
<tbody>
<?php
if(count($regions)>0){
	$i=1;
 foreach ($regions as $region) {
?>


<tr>
<td>
<a href="javascript:void(0);" id="regionsearch<?=$i;?>" onclick="grabvalues2('<?=$region->region_name?>','<?=$region->id?>','<?=$parentname?>');"><?= $region->region_name?></a>
</td>
</tr>
<?php
$i++;
}
}
else echo "<p>No matched search</p>";
?>
</tbody>
</table>