<?php use Application\ApplicationConstant;?>
<style>
    .li_listmember_wid{
        width:100% !important;
    }
    .profile-created-heading{
     color: #eda344;
     font-size: 11px;
    }
    .connect-heading{
    color: #777 !important;
    font-weight: 700 !important;
    font-size: 13px !important;
    padding-bottom: 0px !important; 
        margin: 5px 0;
    font-size: 12px;
    font-weight: 700;
    border: 0;
    border-radius: 5px;
    }
    .btn-request-yes{
    padding: 5px 0 !important;
    color: #fff !important;
    background-color: #f4ad01 !important;
    margin: 5px 0 !important;
    text-align: center !important;
   font-size: 12px !important;
    font-weight: 700 !important;
    border: 0 !important;
    border-radius: 5px !important;
    }
    .btn-request-maybe{
    padding: 5px 0;
    color: #eeeeee !important;
    background-color: #ffb85d ;
    font-size: 12px !important;
    font-weight: 700 !important;
    border: 0 !important;
    border-radius: 5px !important;

    }
    .btn-request-no{
    padding: 5px 0;
    color: #b1b1b2 !important;
    background-color: #f1f1f2 !important;
    
    margin: 5px 0 !important;
    font-size: 12px !important;
    font-weight: 700 !important;
    border: 0 !important;
    border-radius: 5px !important;
        
    }
    .view-profile{
    color: #eda344;
    font-size: 11px;
    }
</style>

<?php //var_dump($this->GroomData); exit;
echo $this->headLink()

        ->prependStylesheet($this->basePath() . '/css/componant-vs-14.css')
?>
<div class="col-sm-3 col-sm-3-new width20per">
    <?php echo $this->partial('layout/sidebar-membership') ?>
    <?php //print_r($filters_data);
// echo MembershipController::membercount(); 
    ?>
</div>
<div class="showerrorbox">

</div>
<div class="col-sm-9 width80per">
    <div class="row">
        <div class="col-xs-9">
            <ul class="view-menu">
                <li>Sort By :</li>
                <li><a href="javascript:void(0);" onclick="sortmembers(this, 'Latest', '<?php echo $this->url('membership', array('action'=>'sortmembers')); ?>', sortmembersresults)" >New Joining</a></li>
                <li><a href="javascript:void(0);" onclick="sortmembers(this, 'IsExecutive', '<?php echo $this->url('membership', array('action'=>'sortmembers')); ?>', sortmembersresults)">Executive Communinty</a></li>
                <li><a href="javascript:void(0);" onclick="sortmembers(this, 'age', '<?php echo $this->url('membership', array('action'=>'sortmembers')); ?>', sortmembersresults)">Senior Citizen</a></li>             
            </ul>
        </div>
        <div class="col-xs-3">
            <ul class="prof-view pull-right">
                <li><a href="#" id="list"><span class="glyphicon glyphicon-th-list"></span><span class="sr-only">List View</span></a></li>
                <li><a href="#" id="grid"><span class="glyphicon glyphicon-th"></span><span class="sr-only">Grid View</span></a></li>
            </ul>
        </div>
    </div>
    <div class="clearfix"></div>
    <!-- <div class="filters_loader_box">
            <div id="filters_data_loader"><h1>Loading...</h1></div>
    </div> -->
    <div id="profile">

        <div class="commen-list grid-view">
            <ul  id="items">
                <li>
                    <div class="col-xs-2"></div>
                    <div class="col-xs-10">
                        <div class="col-xs-2">Name</div>
                        <div class="col-xs-3">F. Name</div>
                        <div class="col-xs-3">Occupation</div>
                        <div class="col-xs-2">Area</div>
                        <div class="col-xs-2">Branch</div>
                    </div>
                </li>
                <?php if (count($this->GroomData) > 0) {
                    foreach ($GroomData as $GrData) {
                        
                        ?>
                        <li class="li_listmember">
                            <div class="col-xs-2">
                                <div class="profile-pic">
                                 <div class="row_box">
                                        <div style="opacity: 1; display: block;" class="item tr big">
                                   <img src="<?php
                                       if ($GrData->image_path != '') {
                                           echo $this->basePath() .'uploads/'. $GrData->image_path;
                                       } else {
                                           echo $this->basePath() . '/img/default_user.png';
                                       }
                                       ?>" />
                                   </div>
                                 </div>
                                </div>
                                <h3><?php echo $GrData->name_title_user . " " . $GrData->full_name. " " . $GrData->last_name; ?></h3>
                                <h4><?= $GrData->profession ?></h4>
                                <a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $GrData->uid ?>" class="btn btn-default">more info</a>
                            </div>
                            
                       
                            
                            
                            
                            <div class="col-xs-10">
                                <div class="col-xs-8">
                                    <div class="col-xs-2 col-xs-2-member">Name</div>

                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->name_title_user . " " . $GrData->full_name. " " . $GrData->last_name ?></div>
                                    <div class="col-xs-2 col-xs-2-member">F. Name</div>

                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->name_title_father . " " . $GrData->father_name. " " . $GrData->last_name ?> </div>
                                    <div class="col-xs-2 col-xs-2-member">Occupation</div>

                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->profession ?></div>
                                    <div class="col-xs-2 col-xs-2-member">Address</div>
                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->address . " " . $GrData->city_name ?></div>

                                    <div class="col-xs-2 col-xs-2-member">Branch</div>
                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->branch_name ?></div> 
                                    
                                     
                                </div>
                                    <div class="col-xs-4 col-xs-4">
                                        <p class="text-center profile-created-heading">(Profile created by Self)</p>
                                        <h3 class="connect-heading">Connect with her?</h3> <?php                                                                               //var_dump($GrData->id); exit; ?>
                                        <button class="btn  col-xs-10 btn-request-yes" onclick="sendInterestToMember(<?php echo $GrData->id ?>,<?php echo ApplicationConstant::YES ?>)">Yes</button>
                                        <button class="btn  col-xs-5  btn-request-maybe" onclick="sendInterestToMember(<?php echo $GrData->id ?>,<?php echo ApplicationConstant::MAYBE ?>)">May be</button>
                                        <button class="btn  col-xs-5 btn-request-no" onclick="sendInterestToMember(<?php echo $GrData->id ?>,<?php echo ApplicationConstant::NO ?>)">No</button>
                                        <div class="clearfix"></div>
                                        <p class="text-center view-profile"><a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $GrData->id ?>">(View full Profile)</a></p>
                                    </div>
                                <div class="clearfix"></div>
                                <div class="col-xs-8" style="padding:0 0;">Short Description : President ( 2012 - Till )</div>
                                <div class="col-xs-4" style="padding:0 0;">
                                    <div style="">
                                        <span>Follow : -</span>
                                        <ul class="follow">
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="facebook"></a></li>
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="twitter"></a></li>
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="gplus"></a></li>
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="linkedin"></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-xs-12" style="display:none;">
                                    <p><?= $GrData->about_yourself_partner_family ?></p>
                                </div>
                            </div>
                             
                        </li>


                    <?php }
                } else {
                    ?> 
                    <span style="text-align:center;font-weight:bold;font-size:12px;color:cornflowerblue;">No Data available</span>
<?php } ?>


                <!--/* <li>
                <div class="col-xs-2">
                <div class="profile-pic"><img src="<?php echo $this->basePath('images/profile-pic.png') ?>" /></div>
                <h3>Sunny Deo</h3>
                <h4>Actor</h4>
                <a href="<?php echo $this->basePath() ?>/membership/profile-view" class="btn btn-default">more info</a>
                </div>
                <div class="col-xs-10">
                <div class="col-xs-2">S. Deo</div>
                <div class="col-xs-3">Rajkumar </div>
                <div class="col-xs-3">Business Man</div>
                <div class="col-xs-2">Gk</div>
                <div class="col-xs-2">Rohini</div>
                <div class="clearfix"></div>
                <div class="col-xs-8">Short Description : President ( 2012 - Till )</div>
                <div class="col-xs-4">
                <div>
                <span>Follow : -</span>
                <ul class="follow">
                <li><a href="#" class="facebook"></a></li>
                <li><a href="#" class="twitter"></a></li>
                <li><a href="#" class="gplus"></a></li>
                <li><a href="#" class="linkedin"></a></li>
                </ul>
                </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-xs-12">
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the 
                </p>
                </div>
                </div>
                </li> */-->

            </ul>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="featured-list">
    
     <div id="banner-load" style="width:100%; padding:0 25px;"></div>
        
    </div>

    <!--<nav id="chk" >
      <ul class="pagination">
      <li class="disabled"><a href="#">Pages:</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">6</a></li>
        <li><a href="#">7</a></li>
        <li class="disabled"><a href="#">.....</a></li>
        
      </ul>
    </nav>-->
</div>

<div id="myModal1" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
   <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 280px; height: 250px; overflow: hidden; visibility: hidden; background-color: #24262e;">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('../img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 280px; height: 250px; overflow: hidden;">
            <?php foreach($Pphotos as $Pphotosl){
                //echo $Pphotosl;
                ?>
            <div data-p="144.50" style="display: none;">
                <img data-u="image" src="<?php echo $this->basePath().'/uploads/'.$Pphotosl?>" />
               
            </div>
            <?php } ?>
<!--            <div data-p="144.50" style="display: none;">
                <img data-u="image" src="../images/bride-deepika.jpg" />
                
            </div>-->
          
           
            
        
        </div>
        <!-- Thumbnail Navigator -->
        <div data-u="thumbnavigator" class="jssort01" style="position:absolute;left:0px;bottom:0px;width:800px;height:100px;" data-autocenter="1">
            <!-- Thumbnail Item Skin Begin -->
            <div data-u="slides" style="cursor: default;">
                <div data-u="prototype" class="p">
                    <div class="w">
                        <div data-u="thumbnailtemplate" class="t"></div>
                    </div>
                    <div class="c"></div>
                </div>
            </div>
            <!-- Thumbnail Item Skin End -->
        </div>
        <!-- Arrow Navigator -->
        <span data-u="arrowleft" class="jssora05l" style="top:158px;left:8px;width:40px;height:40px;"></span>
        <span data-u="arrowright" class="jssora05r" style="top:158px;right:8px;width:40px;height:40px;"></span>
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<?php   echo $this->partial('application/templet/modalPopUp.phtml'); ?> 
<script>
     USERAUTH=<?php echo $this->authUser()->isLogin(); ?>;
   USERTYPEID=<?php echo $this->authUser()->getUser()->user_type_id; ?>;
        jssor_1_slider_init();
    </script>

<script>
    $("#list").on('click', function () {

        $(".li_listmember").addClass('li_listmember_wid');
    });
    $("#grid").on('click', function () {
        $(".li_listmember").removeClass('li_listmember_wid');
    });
</script>
<?php  echo $this->inlineScript()->prependFile($this->basePath('/js/common.js')); ?>
<?php echo $this->inlineScript()->prependFile($this->basePath('/js/member_filters.js')); ?>