<?php 
 
// echo $session->offsetGet('email');
?>
<div class="row">
          <div class="col-xs-12"> 
             
                <div class="col-md-12">
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                        <th>S. No.</th>
                        <th>Membershipfeature Name </th>
                        <th>Description</th>
                        <th>Package Name</th>
                        <!--<th>News Category</th>-->                        
                        <!--<th class="hidden-480">Created Date</th>-->
                        <th class="hidden-480">Modified Date</th>
                        <!--<th class="hidden-480">Created By</th>-->
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                        <!--<input type="hidden" id="table_name" value="tbl_membership_features">
                            <input type="hidden" id="id_name" value="feature_id">-->
                      <?php 
                      $i=1;
//                      echo  "<pre>";print_r($newses);exit;
                      foreach ($membershipfeatures as $membershipfeature) {
                          //\Zend\Debug\Debug::dump($news);
                          
                          
//                          echo  "<pre>";
//                          print_r($news);exit;
                      
                      ?>
                      <tr id="<?php //echo $membershipfeature['feature_id']; ?>" >
                         
                        <td><?= $i?></td>
                        <td><?= $membershipfeature['feature_name']?></td>
                        <!--<td class="shorttext"><?php //echo substr($news->description, 0, 100)."..."?></td>-->
                        <td class="shorttext"><div class="showshort"><?php echo $membershipfeature['feature_desc']?></div></td>
                        <!--<td><?php // $image = (empty($membershipfeature->image))? '/images/new-big.jpg' : $membershipfeature->image;?>
                        <img src="<?//= $this->basepath()."/NewsImages/".$image;?>" width="43" height="37" alt="">
                      </td>  -->                     
                        <td class="hidden-480"><?= $membershipfeature['package_name']?></td>
                        <!--<td class="hidden-480"><?//= $membershipfeature['created_date'];?></td>-->
                        <td class="hidden-480"><?= $membershipfeature['modified_date']?></td>
                        <!--<td class="hidden-480"><?php //echo ($news->isActive==1)? 'Active': '<span class="label '
                                //. 'label-sm label-warning">In-Active</span>'; ?></td>-->
                        <!--<td class="hidden-480"><?php //echo $membershipfeature['username']; ?></td>-->
                        <td class="hidden-480"><?php echo $membershipfeature['username']; ?></td>
                        
                        <td class="hidden-480">
						<!--<?php echo ($membershipfeature['is_active']==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($membershipfeature['is_active']==1)? 'Active': 'In-Active';
                        $statuscolor = ($membershipfeature['is_active']==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$membershipfeature['id']?>,<?= ($membershipfeature['is_active']==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/membershipfeature', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        
                        <td><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" href="<?php 
                        echo $this->url('admin/membershipfeature',array('action'=>'view','id'=>$membershipfeature->id)); ?>"> <i 
                         class="ace-icon fa fa-search-plus bigger-130"></i> </a> <a class="green" href=
                            "<?php echo $this->url('admin/membershipfeature',array('action'=>'edit','id'=>$membershipfeature->id));
                            ?>" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" 
                               href="<?php echo $this->url('admin/membershipfeature',array('action'=>'delete',
                                   'id'=>$membershipfeature->id)); ?>" onclick="return confirm('are you sure you want \n\
to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
                
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
            <?php 

        // print_r($countries);

        ?>         
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            
            <!-- /.row -->
            
            <div class="hr hr-18 dotted hr-double"></div>
            <div class="row">
              <div class="col-xs-12">
                
                <div> 
         
      </div>
      <!-- /.page-content --> 
    </div>
  </div>
  <!-- /.main-content -->
  
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->
