

<div id="editForm" class="tab-content dontshow">
                </div>




 



<div class="row">
          <div class="col-xs-12"> 
             
                <div class="col-md-12">
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>S. No.</th>
                        <th>Subevent Title </th>
                        <th>Subevent Picture</th>
                        <!--<th>Event Organiser </th>-->
                        <th>Venue </th>
                        <th>Fees</th>                        
                        <!--<th>Country</th>-->
                        <!--<th>City</th>-->
                        <!--<th>Venue</th>-->
                        <th>Start Time</th>
                        <th>End Time</th>
                        <!--<th class="hidden-480">Created Date</th>-->
                        <th class="hidden-480">Modified Date</th> 
                        <!--<th class="hidden-480">Created By</th>-->
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                        <!--<input type="hidden" id="table_name" value="tbl_subevent">
                            <input type="hidden" id="id_name" value="subevent_id">-->
                      <?php 
                      $i=1;
//                      echo "hello yar";exit;
                      foreach ($subevents as $subevent) {
                          
//                          echo   "<pre>";
//                          print_r($subevent);exit;
                      
                      ?>
                      <tr id="<?php //echo $subevent['subevent_id']; ?>" >
                         
                        <td><?= $i?></td>
                        <td><?= $subevent['title']?></td>
                        <td><?php $imagePath = (empty($subevent['image']))? '/images/new-big.jpg' : $subevent['image'];?>
                        <img src="<?= $this->basepath()."/SubeventsImages/".$imagePath;?>" width="43" height="37" alt="">
                      </td> 
                      <td class="shorttext"><div class="showshort"><?= $subevent['venue']?></div></td>
                      <td class="shorttext"><div class="showshort"><?= $subevent['fees']?></div></td>
                        <!--<td><?php //echo empty($event->eventOrganiser)?'Not Given':$event->eventOrganiser;?></td>-->
                        <!--<td><?php //echo  date("l d-m-y",strtotime($event->eventDate));?></td>-->
                        <!--<td><?php //echo  $subevent->eventDate;?></td>-->
                        
                                              
                        <!--<td class="hidden-480"><?php //echo $subevent->countryName?></td>-->
                        <!--<td class="hidden-480"><?php //echo $subevent->cityName?></td>-->
                        <!--<td class="hidden-480"><?php //echo  $event->venue?></td>-->
                        
                        <td class="hidden-480"><?= date('h:i A',strtotime($subevent['start_time']))?></td>
                        <td class="hidden-480"><?= date('h:i A',strtotime($subevent['end_time']))?></td>
                        <!--<td class="hidden-480"><?//= $subevent['created_date']?></td>-->
                        <td class="hidden-480"><?= $subevent['modified_date']?></td>
                        <!--<td class="hidden-480"><?php //echo $subevent['username']; ?></td>-->
                        <td class="hidden-480"><?php echo $subevent['username']; ?></td>
                        <td class="hidden-480">
						<!--<?php //echo ($subevent->isActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($subevent['is_active']==1)? 'Active': 'In-Active';
                        $statuscolor = ($subevent['is_active']==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatussubeventquick(<?=$subevent['subevent_id']?>,<?= ($subevent['is_active']==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/subevents', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td> 
                        
                        <td><div class="hidden-sm hidden-xs action-buttons"> 
                          <!--<a class="blue" data-toggle="modal" href="#ViewmyModal" onclick="editbox
                              (<?php //echo $event->id?>,'<?php //echo $this->serverurl().$this->url()."/events/eventsview";?>'
                              ,showeventsview)"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a>-->
                          
                          <!--<a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?php //echo $i ?>"> <i onclick="findRowDataByEventsId('<?php //echo $this->url
                                                           //('admin/events', array('action'=>'eventsview','id'=>$event->id)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>-->
                                                           
                          <a class="blue" href="<?php 
                        echo $this->url('admin/subevents',array('action'=>'subeventsview','id'=>$subevent['subevent_id'])); ?>"> <i 
                         class="ace-icon fa fa-search-plus bigger-130"></i> </a>                               

                           <!--<a class="green"  data-toggle="modal" href="#EditmyModal" onclick=
                               "editbox(<?php //echo $event->id?>,'<?php //echo $this->serverurl().$this->url().
                                                                   //"/events/eventsedit";?>',
                                                                       showeventsedit)"> 
                       <i class="ace-icon fa fa-pencil bigger-130"></i> </a> -->
                       <a class="green" href="<?php echo $this->url('admin/subevents',array('action'=>'subeventsedit','id'=>$subevent['subevent_id'])); ?>" > 
                           <i class="ace-icon fa fa-pencil bigger-130"></i> </a>

                           <a class="red" href="<?php echo $this->url('admin/subevents',array('action'=>'subeventsdelete','id'=>$subevent['subevent_id'])); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 </div>
              </div>
              <div class="col-sm-12"> 
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 
<!-- <div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
            <?php 

        // print_r($countries);

        ?>         
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> -->
            
            <!-- /.row -->
            
            <div class="hr hr-18 dotted hr-double"></div>
            <div class="row">
              <div class="col-xs-12">
                
                <div> 
         
                </div>
      <!-- /.page-content --> 
              </div>
          </div>
  <!-- /.main-content -->
  
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->
<div id="viewEventsModel"></div>
<?php echo $this->inlineScript()->prependFile($this->basePath('/assets/js/event.js')); ?>
<!-- <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="<?php //echo $this->basePath(); ?>/assets/js/jquery-1.10.2.js"></script> 
<script src="<?php //echo $this->basePath(); ?>/assets/js/jquery-ui-1.10.4.custom.min.js"></script> 
<script src="<?php //echo $this->basePath(); ?>/assets/js/script.js"></script> -->