<?php $session = new \Zend\Session\Container('user'); ?>
<?php
$user_id = $session->offsetGet('id');
//\Zend\Debug\Debug::dump($userSummary);
?> 
<style>
    /* Dropdown Button */

    label {

        margin-bottom: 0;

    }
    .col-sm-2n
    {
        margin-right:0;	
    }

    .col-sm-3lifestyale
    {
        padding:0 15px 0 0 !important;
        text-align:center;

    }

    .col-sm-3lifestyale1
    {
        border:1px solid #ccc;
        width:100%;
        text-align:center;
        vertical-align:middle;
        min-height:60px;
        padding-top:5px;

    }

</style>

<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/componant-vs-14.css')
?>
<div class="container orange-panelbg">
    <div class="col-sm-3 col-sm-3-new width20per">
        <?php
        if ($session->offsetGet('user_type_id') == '1') {
            include('sidebar_left_member.phtml');
        } elseif ($session->offsetGet('user_type_id') == '2') {
            include('sidebar_left_matrimony.phtml');
        }
        ?>

    </div>

    <div class="col-sm-9 width80per">
        <div class="myshaadi_wrap">
            <div class="welcome_screen"></div>


            <div class="clear"></div>
        </div>

        <!--MY SHAADI LEFT-->
        <div class="col-sm-9" style="padding-top:0; padding-left:0;">

            <!--<div id="my_rustagi_left">
            
            
                    
            
            
            </div>--><!--end left_half-->	

            <!--MIDDLE SECTION-->
            <div id="my_rustagi_middle">



                <!--Pin Interest render-->
                <div id="pin_interest" style="display: block;">    
                    <div class="pinned_wrap">
                        <div class="pinned_shadow">

                            <div class="pinned_profile_green">
                                <p class="pinned_heading" style="font-size:14px;">
                                    <label class="col-sm-4">Change Your Password


                                    </label>             
                                </p>

                                <div id="pin_interest_profile" class="pos_rel">

                                    <div class="pinned_profile_wrap" rel="vSH87477335">
                                        <div class="pinned_pic">
                                            <form role="form" action="<?php echo $this->url('profile', array('action' => 'change-password')) ?>" method="post">
                                                <div class="form-group">



                                                    <div class="modal-body" align="center">
                                                        <?php
//                                                        if ($this->flashMessenger()->hasMessages()) {
//
//                                                            echo '<div style="color: #800">';
//
//                                                            $messages = $this->flashMessenger()->getMessages();
//                                                            foreach ($messages as $message) {
//                                                               echo $message[0];
//                                                            }
//                                                                //echo $messages;
//                                                            echo '</div>';
//                                                        }
                                                        //added by amir
                                                        //echo $notchangePwd;
                                                        //if($this->flashMessenger()->render()=='Password  changed successfully...'){
                                                        // echo $this->flashMessenger()->render();
                                                        //}else{
                                                        //echo $this->flashMessenger()->render();
                                                        //}
                                                        //echo $this->flashMessenger()->render();
//                                                        if(isset($msg) && $msg!=""){
                                                        ?>
                                                        <input type ="hidden"    id="message" value="<?php echo $msg; ?>" >

                                                        <?php // }  ?>
                                                        <?php
//                                                        if($msg=="Password  changed successfully..."){
////                                                            echo $msg;
////                                                        }else{
//                                                            echo $msg;
//                                                            
//                                                        }
                                                        //}
                                                        ?>
                                                        <div class="col-sm-6" style="float:none !important; text-align:left; padding:0;">              
                                                            <div class="col-sm-12">
                                                                Enter Old Password
                                                                <input type="password" name="old_password2" id="old_password2" class="form-control" onchange="validateOldPwd();"/>
                                                                <span style='color:red;'><?php echo $old_password_error; ?></span>
                                                            </div>
                                                            <div class="col-sm-12">
                                                                New Password
                                                                <input type="password" name="new_password" id="new_password" value="" class="form-control" />
                                                                <span style='color:red;'><?php echo $new_password_error; ?></span>
                                                            </div>

                                                            <div class="col-sm-12">
                                                                Confirm Password
                                                                <input type="password" name="confirm_password" id="confirm_password" value="" class="form-control" onchange="confrmValidateChangePwd();"/>
                                                                <span style='color:red;'><?php echo $confirm_password_error; ?></span>
                                                            </div>

                                                            <!-- <div class="col-sm-12">
                                     
                                                                 <input type="checkbox" name="rember" /><em>Remember me</em>
                                                             </div>
                                                            -->
                                                            <div class="col-sm-12" align="center">
                                                                <div class="col-sm-12" style="float:none; margin-top:10px; border:none; padding:0;">
                                                                    <button type="submit" name="change_password" id="login" class="btn btn-default btn-block popuplogingbut">Change Password</button>
                                                                    <!--<a href="#" onclick="sentOtp();">Click Here to Send OTP</a>-->
                                                                </div>


                                                            </div>

                                                            <div class="col-sm-12 text-center"> </div>  

                                                        </div>
                                                        <div class="clearfix"></div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>



                                        <div class="clearfix"></div>


                                    </div>       


                                </div>
                            </div>


                        </div>
                    </div>
                </div>



            </div>
        </div>
        <!--MY rustagi RIGHT-->
        <div id="my_rustagi_right" class="col-sm-3 col-sm-3new pull-right">
<?php
//        if ($session->offsetGet('user_type_id') == '1') {
//        include('sidebar_right_member.phtml'); 
//        }elseif ($session->offsetGet('user_type_id') == '2') {
//        include('sidebar_right_matrimony.phtml'); 
//        }
//        
?>
        </div>
        <!--end right_half-->
        <br class="clear">
    </div>


</div>

<script>
<?php echo $percent[1] ?>

    $('#demo-3').waterbubble({txt: '//<?php echo $percent[0] ?>%', });
</script>


<script>
    $(document).ready(function () {
        $("#contact_detail").click(function () {
            $(".contactde").toggle();
        });

    });

//    function sentOtp() {
//        //alert('amir');
//        var url = '/user/sendOtpByChangePwd';
//        $.ajax({
//            //type: 'POST',
//            url: url,
//            //dataType: "html",
//            //data: data,
//            success: function (result) {
//                if (result.resp == true) {
//                    alert(result.message);
//                }
//                //$(".showerrorbox").fadeOut();
//                //$("#profilepage").hide();
//                //$("#listgrid").show();
//                //document.getElementById("profile1").innerHTML = result;
//            },
//            error: function () {
//                //console.log(); 
//            }
//        });
//
//    }



    $(document).ready(function () {

        var $msg = document.getElementById('message').value;
        if ($msg == 'Password  changed successfully...') {
            alert($msg);

            window.location.href = "<?php echo $this->url('profile', array('action' => 'index')) ?>";
        }
    });

//        var data = {
//            old_password2: old_password2
//
//        }
//        var url = '/user/confirmoldChangePwd';
//        $.ajax({
//            type: 'POST',
//            url: url,
//            //dataType: "html",
//            data: data,
//            success: function (result) {
//                if (result.resp == 0) {
//                    alert(result.error);
//                    document.getElementById('old_password2').value="";
//                    document.getElementById('old_password2').focus();
//                    
//                }
//                //$(".showerrorbox").fadeOut();
//                //$("#profilepage").hide();
//                //$("#listgrid").show();
//                //document.getElementById("profile1").innerHTML = result;
//            },
//            error: function () {
//                //console.log(); 
//            }
//        });

    // }

    function validateOldPwd() {
        //alert('amir');

        if (document.getElementById('old_password2').value != 0) {
            var old_password2 = document.getElementById('old_password2').value;
        }

        var data = {
            old_password2: old_password2

        }
        var url = '/user/confirmoldChangePwd';
        $.ajax({
            type: 'POST',
            url: url,
            //dataType: "html",
            data: data,
            success: function (result) {
                if (result.resp == 0) {
                    alert(result.error);
                    document.getElementById('old_password2').value = "";
                    document.getElementById('old_password2').focus();

                }
                //$(".showerrorbox").fadeOut();
                //$("#profilepage").hide();
                //$("#listgrid").show();
                //document.getElementById("profile1").innerHTML = result;
            },
            error: function () {
                //console.log(); 
            }
        });

    }

    function confrmValidateChangePwd() {
        //alert('amir');

        if (document.getElementById('new_password').value != 0) {
            var new_password = document.getElementById('new_password').value;
        }
        //alert(new_password);
        if (document.getElementById('confirm_password').value != 0) {
            var confirm_password = document.getElementById('confirm_password').value;
        }

        //alert(confirm_password); 
        var data = {
            new_password: new_password,
            confirm_password: confirm_password

        }
        //return false;
        var url = '/user/confirmChangePwd';
        $.ajax({
            type: 'POST',
            url: url,
            //dataType: "html",
            data: data,
            success: function (result) {
                if (result.resp == 0) {
                    alert(result.error);
                    document.getElementById('confirm_password').value = "";
                    document.getElementById('confirm_password').focus();
                }

            },
            error: function () {
                //console.log(); 
            }
        });

    }
</script>