<!-- Brother Copy Fields -->
                            <div class="copy-brother hide">
                                <div class="control-group input-group" style="margin-top:10px;">
                                    <div class="form-group row">
                                        <label for="grand_fatherName" class="col-sm-2 form-control-label edupading">Name</label>
                                        <div class="col-sm-3 coltilte">
                                            <select class="form-control" name="new_name_title_brother[]" style="padding:0;">
                                                <option>Mr</option>
                                                <option>Mrs</option>
                                                <option>Miss</option>
                                                <option>Dr</option>
                                                <option>Prof</option>
                                                <option>Retd</option>
                                                <option>Major</option>
                                                <option>Sh</option>
                                                <option>Smt</option>
                                                <option>Late Sh</option>
                                                <option>Late Smt</option>
                                            </select>
                                        </div>
                                        <div class="col-sm-2 colname">
                                            <input type="text" placeholder="First Name"  name="new_brother_name[]" class="form-control">
                                        </div>
                                        <div class="col-sm-2 colname">
                                            <input type="text" placeholder="Last Name"  name="new_brother_last_name[]" class="form-control">
                                        </div>
                                        <label for="Phone No." class="col-sm-2 form-control-label edupading" style="width: 15% !important;">Status</label>
                                        <div class="col-sm-2">
                                            <select class="form-control"  name="new_brother_status[]" id="new_brother_status">
                                                <option value="Employed">Employed</option>
                                                <option value="Not Employed">Not Employed</option>
                                                <option value="Self Employed">Self Employed</option>
                                                <option value="Govt Employed">Govt Employed</option>
                                                <option value="Business">Business</option>
                                                <option value="Home Maker">Home Maker</option>
                                                <option value="2">Passed Away</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="DOB" class="col-sm-2 form-control-label edupading">DOB</label>
                                        <div class="col-sm-3">
                                            <input type="text" name="new_brother_dob[]" class="form-control dateRangePicker" value="00-00-0000">
                                        </div>
                                        <div id="mother_AliveInfoArea">
                                            
                                            <div class="col-sm-3">
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="Marital Status" class="col-sm-2 form-control-label edupading">Marital Status</label>
                                        <div class="col-sm-3"> 
                                            <select class="form-control" name="new_marital_status_brother[]">
                                                <option>Not-Married</option>
                                                <option>Married</option>
                                                
                                            </select>
                                        </div>
                                        <div class="" id="brotherDodInfo" style="display:none">
                                            <label for="DOD" class="col-sm-2 form-control-label edupading">DOD</label>
                                            <div class="col-sm-3">
                                                <input type="text" name="new_brother_dod[]" class="form-control dateRangePicker" value="00-00-0000">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div id="about_brother">
                                            <label for="About Brother" class="col-sm-2 form-control-label edupading">About</label>
                                            <div class="col-sm-9" style="padding:0;">
                                                <textarea class="form-control" style="height:50px;" name="new_about_brother[]" placeholder="About Brother"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group-btn"> 
                                        <button class="btn btn-danger remove" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                                    </div>
                                </div>
                            </div>                    
             <!--copy end-->  
             
 <!-- Sister Copy Fields -->
                            <div class="copy-sister hide">
                                <div class="control-group input-group" style="margin-top:10px;">
                                    <div class="form-group row">
                                        <label for="grand_fatherName" class="col-sm-2 form-control-label edupading">Name</label>
                                        <div class="col-sm-3 coltilte">
                                            <select class="form-control" name="new_name_title_sister[]" style="padding:0;">
                                                <option>Mr</option>
                                                <option>Mrs</option>
                                                <option>Miss</option>
                                                <option>Dr</option>
                                                <option>Prof</option>
                                                <option>Retd</option>
                                                <option>Major</option>
                                                <option>Sh</option>
                                                <option>Smt</option>
                                                <option>Late Sh</option>
                                                <option>Late Smt</option>
                                            </select>
                                        </div>
                                        <div class="col-sm-2 colname">
                                            <input type="text" placeholder="First Name" name="new_sister_name[]" class="form-control">
                                        </div>
                                        <div class="col-sm-2 colname">
                                            <input type="text" placeholder="Last Name" name="new_sister_last_name[]" class="form-control">
                                        </div>
                                        <label for="Phone No." class="col-sm-2 form-control-label edupading" style="width:15% !important;">Status</label>
                                        <div class="col-sm-2">
                                            <select class="form-control"  name="new_sister_status[]" id="new_sister_status">
                                                <option value="Employed">Employed</option>
                                                <option value="Not Employed">Not Employed</option>
                                                <option value="Self Employed">Self Employed</option>
                                                <option value="Govt Employed">Govt Employed</option>
                                                <option value="Business">Business</option>
                                                <option value="Home Maker">Home Maker</option>
                                                <option value="2">Passed Away</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="DOB" class="col-sm-2 form-control-label edupading">DOB</label>
                                        <div class="col-sm-3">
                                            <input type="text" name="new_sister_dob[]" class="form-control dateRangePicker" value="00-00-0000">
                                        </div>
                                        <div id="mother_AliveInfoArea">
                                            
                                            <div class="col-sm-3">
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="Marital Status" class="col-sm-2 form-control-label edupading">Marital Status</label>
                                        <div class="col-sm-3"> 
                                            <select class="form-control" name="new_marital_status_sister[]">
                                                <option>Not-Married</option>
                                                <option>Married</option>
                                                
                                            </select>
                                        </div>
                                        <div class="" id="sisterDodInfo" style="display:none">
                                            <label for="DOD" class="col-sm-2 form-control-label edupading">DOD</label>
                                            <div class="col-sm-3">
                                                <input type="text" name="new_sister_dod[]" class="form-control dateRangePicker" value="00-00-0000">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div id="about_sister">
                                            <label for="About Brother" class="col-sm-2 form-control-label edupading">About</label>
                                            <div class="col-sm-9" style="padding:0;">
                                                <textarea class="form-control" style="height:50px;" name="new_about_sister[]" placeholder="About Brother"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group-btn"> 
                                        <button class="btn btn-danger remove" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                                    </div>
                                </div>
                            </div>                    
             <!--copy end Sister-->  
             
             
             <!-- Kids Copy Fields -->
                            <div class="copy-kids hide">
                                <div class="control-group input-group" style="margin-top:10px;">
                                    <div class="form-group row">
                                        <label for="grand_fatherName" class="col-sm-2 form-control-label edupading">Name</label>
                                        <div class="col-sm-3 coltilte">
                                            <select class="form-control" name="new_name_title_kids[]" style="padding:0;">
                                                <option>Mr</option>
                                                <option>Mrs</option>
                                                <option>Miss</option>
                                                <option>Dr</option>
                                                <option>Prof</option>
                                                <option>Retd</option>
                                                <option>Major</option>
                                                <option>Sh</option>
                                                <option>Smt</option>
                                                <option>Late Sh</option>
                                                <option>Late Smt</option>
                                            </select>
                                        </div>
                                        <div class="col-sm-3 colname">
                                            <input type="text"  name="new_kids_name[]" class="form-control">
                                        </div>
                                        <label for="Phone No." class="col-sm-2 form-control-label edupading">Status</label>
                                        <div class="col-sm-3">
                                            <select class="form-control"  name="new_kids_status[]" id="new_kids_status">
                                                <option value="Employed">Employed</option>
                                                <option value="Not Employed">Not Employed</option>
                                                <option value="Self Employed">Self Employed</option>
                                                <option value="Govt Employed">Govt Employed</option>
                                                <option value="Business">Business</option>
                                                <option value="Home Maker">Home Maker</option>
                                                <option value="2">Passed Away</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="DOB" class="col-sm-2 form-control-label edupading">DOB</label>
                                        <div class="col-sm-3">
                                            <input type="text" name="new_kids_dob[]" class="form-control dateRangePicker" value="00-00-0000">
                                        </div>
                                        <div id="mother_AliveInfoArea">
                                            
                                            <div class="col-sm-3">
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="Marital Status" class="col-sm-2 form-control-label edupading">Marital Status</label>
                                        <div class="col-sm-3"> 
                                            <select class="form-control" name="new_marital_status_kids[]">
                                                <option>Not-Married</option>
                                                <option>Married</option>
                                                
                                            </select>
                                        </div>
                                        <div class="" id="kidsDodInfo" style="display:none">
                                            <label for="DOD" class="col-sm-2 form-control-label edupading">DOD</label>
                                            <div class="col-sm-3">
                                                <input type="text" name="new_kids_dod[]" class="form-control dateRangePicker" value="00-00-0000">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div id="about_kids">
                                            <label for="About Brother" class="col-sm-2 form-control-label edupading">About</label>
                                            <div class="col-sm-9" style="padding:0;">
                                                <textarea class="form-control" style="height:50px;" name="new_about_kids[]" placeholder="About Brother"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group-btn"> 
                                        <button class="btn btn-danger remove" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                                    </div>
                                </div>
                            </div>                    
             <!--copy end Kids-->  