<div class="modal fade" id="avatar-modal3" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">

        <div class="modal-content">

            <form class="cropimage" method="post" enctype="multipart/form-data" action="<?php echo $this->url("profile", array('action' => 'uploadGalleryImagesMatrimonial')) ?>">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title" id="avatar-modal-label">Profile Picture</h4>
                </div>

                <input type="file" name="photoimg" class="photoimg" />
                <input type="hidden" name="hdn-profile-id" class="hdn-profile-id" value="1" />
                <input type="hidden" name="hdn-x1-axis" class="hdn-x1-axis" value="" />
                <input type="hidden" name="hdn-y1-axis" class="hdn-y1-axis" value="" />
                <input type="hidden" name="hdn-x2-axis" value="" class="hdn-x2-axis" />
                <input type="hidden" name="hdn-y2-axis" value="" class="hdn-y2-axis" />
                <input type="hidden" name="hdn-thumb-width" class="hdn-thumb-width" value="" />
                <input type="hidden" name="hdn-thumb-height" class="hdn-thumb-height" value="" />
                <input type="hidden" name="action" value="" id="action" />
                <input type="hidden" name="uid" value="" id="uid" />
                <input type="hidden" name="image_name" value="" class="image_name" />
                <input type="hidden" name="crop_enabled" value="no" class="crop_enabled" />

                <div class='preview-avatar-profile-matrimonial' style="position:relative;">
                </div>
                <div id="thumbs" style="padding:5px; width:600p"></div>
                <div class="modal-footer">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                    <button type="button" class="btn-crop btn btn-primary">Crop & Save</button>
                </div>			
            </form>
        </div>
    </div>
</div>

<a href="#" data-toggle="modal" data-target="#avatar-modal3" o style="font-weight:bold;padding-left:33.5%;font-size:18px;color:cornflowerblue;">Upload More Photos to Gallery</a> 

<div id="gallery" class="tab-pane fade in active" >
    <table>
        <tr>
            <td>
                <div class="col-sm-4" style="width:100%;">
                    <div class="gallery" id="gallery_images"> 


                        <div class="col-sm-6">
                            <div class="col-sm-12" style="padding:0 !important;">  <h3>Personal Photos</h3></div>
                            <div class="col-sm-4" style="padding:0 !important;"><a href="#" title="" ><img src="<?= $this->basePath(MATRIMONIAL_IMAGE_PATH) . $image[0]['image_name'] ?>" style="width:100%;height:140px;display:block;" class="moreimgthamb" /></a></div>
                            <div class="col-sm-4" style="padding:0 !important;"><a href="#" title="" ><img src="<?= $this->basePath(MATRIMONIAL_IMAGE_PATH) . $image[1]['image_name'] ?>" style="width:100%;height:140px;display:block;" class="moreimgthamb" /></a></div>
                            <div class="col-sm-4" style="padding:0 !important;"><a href="#" title="" ><img src="<?= $this->basePath(MATRIMONIAL_IMAGE_PATH) . $image[2]['image_name'] ?>" class="moreimgthamb" style="width:100%;height:140px;display:block;" /></a></div>
                            <div class="col-sm-3"><a href="#" title="" ><img src="<?= $this->basePath(MATRIMONIAL_IMAGE_PATH) . $image[3]['image_name'] ?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
                            <div class="col-sm-3"><a href="#" title="" ><img src="<?= $this->basePath(MATRIMONIAL_IMAGE_PATH) . $image[4]['image_name'] ?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
                            <div class="col-sm-3"><a href="#" title="" ><img src="<?= $this->basePath(MATRIMONIAL_IMAGE_PATH) . $image[5]['image_name'] ?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
                            <div class="col-sm-3" id="more" onclick="showAllImagesMatrimonialGallery()">
                                <a href="#" title=""><img src="<?= $this->basePath(MATRIMONIAL_IMAGE_PATH) . $image[6]['image_name'] ?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" />
                                </a>
                                <div class="moreimage" style="cursor:pointer;"> + </div>
                            </div>
                        </div>




                        <div class="col-sm-12 userimg" id="showallimages" style="border:1px solid #ccc; margin-top:20px; padding:5px !important; display:block;">
                            <div class="col-md-12"><input class="btn btn-default" type="button" style="float:right;" onclick="deleteSelectedMatrimonial()" value="delete selected"></div>
                            <!-- <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/img4.jpg" class="moreimgthambdeleat imghover"/>
                            <div class="deleteimg"> 
                            <input type="checkbox" />
                            </div>
                            </div>
                            
                            <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/img5.jpg" class="moreimgthambdeleat"/></div>
                            
                            <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/slide1.jpg" class="moreimgthambdeleat"/></div>
                            
                            <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/matrimonial-deepika.jpg" class="moreimgthambdeleat"/></div> -->

                        </div>  

                        <!--  <div class="col-sm-12 familyimg" style="border:1px solid #ccc; margin-top:20px; padding:5px !important; display:none;">
                         <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/img4.jpg" class="moreimgthambdeleat"/></div>
                     
                     <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/img5.jpg" class="moreimgthambdeleat"/></div>
                     
                     <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/slide1.jpg" class="moreimgthambdeleat"/></div>
                     
                     <div class="col-sm-3"><img src="<?= $this->basePath() ?>/gallery/thumb/matrimonial-deepika.jpg" class="moreimgthambdeleat"/></div>
                   
                   </div> -->


                    </div> 
                </div>
            </td>
        </tr>
    </table>
</div>
<script>
    function showAllImagesMatrimonialGallery() {
        //var queryString = "type=" + type;
        //alert('satya');

        $.ajax({
            url: '<?php echo $this->url('profile', array('action' => 'showAllImagesMatrimonialGallery')) ?>',
            //type: "POST",
            dataType: "html",
            // data: {Country_ID: countryId},
            beforeSend: function () {
                $('#Loading_Request').show();
            },
            complete: function () {
                $('#Loading_Request').hide();
            },
            success: function (resp) {

                $.each($.parseJSON(resp), function (index, item) {
                    var data = '<div class="col-sm-3" style="margin-bottom:30px" id="profilepicid' + item.id + '">' +
                            '<input type="checkbox" name="delimagesMatrimonial[]" value="' + item.id + '" />' +
                            '<img src="<?php echo $this->basePath(MATRIMONIAL_IMAGE_PATH) ?>' + item.image_name + '" class="moreimgthambdeleat imghover"/>' +
                            '<div>' +
                            '<input type="hidden" name="id_field" value="' + item.id + '" />' +
                            '<input type="hidden" name="path" value="" />' +
                            '</div>' +
                            //'<div class="familytitles">' + item.image_name + '</div>' +
                            '</div>';
                    $("#showallimages").append(data);
                    //console.log(item.user_id);
                });



                //$("#showallimages").fadeIn();
                //$("#showallimages").html(resp);
                debugger;
//                    if (resp.Status == 'Success') {
//                            $("#profile").empty();
//                            $("#state").append(resp);
//                          
//                    } else {
//                    $("#state").empty();
//                            $("#city").empty();
//                            alert("No States are available");
//                    }
            },
            error: function (error) {
                console.log(error);
                // alert(error);
            }
        });

    }



</script>

<script type="text/javascript">
    jQuery(document).ready(function () {

        jQuery('.photoimg').on('change', function () {
            jQuery(".preview-avatar-profile-matrimonial").html('');
            jQuery(".preview-avatar-profile-matrimonial").html('Uploading....');
            jQuery(".cropimage").ajaxForm(
                    {
                        target: '.preview-avatar-profile-matrimonial',
                        success: function () {
                            jQuery('img.photo').imgAreaSelect({
                                aspectRatio: '0:0',
                                parent: '.preview-avatar-profile-matrimonial',
                                onSelectEnd: getSizes,
                            });
                            jQuery('.image_name').val(jQuery('.photo').attr('file-name'));
                        }
                    }).submit();

        });

//// Function for Save Image Starts Here ////	 

        jQuery('.btn-crop').on('click', function (e) {
            e.preventDefault();
            var galleryUploadUrl = '<?php echo $this->url("profile", array('action' => 'uploadGalleryImagesMatrimonial')) ?>';
            params = {
                //targetUrl: 'profile.php?action=save',
                targetUrl: galleryUploadUrl + '?action=save',
                action: 'save',
                x_axis: jQuery('.hdn-x1-axis').val(),
                y_axis: jQuery('.hdn-y1-axis').val(),
                x2_axis: jQuery('.hdn-x2-axis').val(),
                y2_axis: jQuery('.hdn-y2-axis').val(),
                thumb_width: jQuery('.hdn-thumb-width').val(),
                thumb_height: jQuery('.hdn-thumb-height').val()
            };
            saveCropImage(params);
        });

//// Function for Save Image Ends Here ////

//// Function for Get the Image Size Starts Here ////	 

        function getSizes(img, obj)
        {
            var x_axis = obj.x1;
            var x2_axis = obj.x2;
            var y_axis = obj.y1;
            var y2_axis = obj.y2;
            var thumb_width = obj.width;
            var thumb_height = obj.height;
            if (thumb_width > 0)
            {
                jQuery('.hdn-x1-axis').val(x_axis);
                jQuery('.hdn-y1-axis').val(y_axis);
                jQuery('.hdn-x2-axis').val(x2_axis);
                jQuery('.hdn-y2-axis').val(y2_axis);
                jQuery('.hdn-thumb-width').val(thumb_width);
                jQuery('.hdn-thumb-height').val(thumb_height);
                jQuery('.crop_enabled').val('yes');
            } else
                alert("Please select portion..!");
        }

//// Function for Get the Image Size Ends Here ////
//
//// Function for Save the Crop Image Starts Here ////

        function saveCropImage(params) {
            jQuery.ajax({
                url: params['targetUrl'],
                cache: false,
                dataType: "html",
                data: {
                    action: params['action'],
                    id: jQuery('.hdn-profile-id').val(),
                    t: 'ajax',
                    w1: params['thumb_width'],
                    x1: params['x_axis'],
                    h1: params['thumb_height'],
                    y1: params['y_axis'],
                    x2: params['x2_axis'],
                    y2: params['y2_axis'],
                    image_name: jQuery('.image_name').val(),
                    crop_enabled: jQuery('.crop_enabled').val()
                },
                type: 'Post',
                // async:false,
                success: function (response) {
                    alert(response);
                    jQuery('.changePic').hide();
                    jQuery('.change-pic').show();
                    jQuery(".imgareaselect-border1,.imgareaselect-border2,.imgareaselect-border3,.imgareaselect-border4,.imgareaselect-border2,.imgareaselect-outer").css('display', 'none');
                    //jQuery(".avatar-edit-img").attr('src', response);
                    jQuery(".preview-avatar-profile-matrimonial").html('');
                    jQuery(".photoimg").val('');
                    $('#avatar-modal1').modal('hide');
                    window.location = window.location;

                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('status Code:' + xhr.status + 'Error Message :' + thrownError);
                }
            });
        }

//// Function for Save the Crop Image Ends Here ////

    });
    function deleteSelectedMatrimonial() {
        var chkdata = $("input[name='delimagesMatrimonial\\[\\]']:checked").map(function () {
            return $(this).val();
        }).get();
        //console.log(chkdata);


        $.ajax({
            url: '<?php echo $this->url("profile", array('action' => 'deleteGalleryImagesMatrimonial')) ?>',
            type: "post",
            data: 'ids=' + chkdata,
            beforeSend: function () {
                $('#Loading_Request').show();
            },
            complete: function () {
                $('#Loading_Request').hide();
            },
            success: function (resp) {
                //window.location = window.location;
                $.each(resp.ids, function (index, value) {
                      //console.log(value);
                      $("#profilepicid"+value).hide();
                });
                //console.log(resp);
            },
            error: function (error) {
                console.log(error);
                // alert(error);
            }
        })
//    var type = $("#showallimages").find("input[name=type]").val();
//    var uid = $("#showallimages").find("input[name=uid]").val();
//    var path = $("#showallimages").find("input[name=path]").val();
//    var queryString = "idfield=" + chkdata + "&Itype=" + type + "&user_id=" + uid + "&path=" + path;
//    ajax_call_simple(queryString, action, callback);
    }
</script>

