<?php
 //\Zend\Debug\Debug::dump($this->userSummary);
//if ($this->gallery_data) {
//    $images = array();
//    foreach ($gallery_data as $result) {
//        $images[] = $result;
//    }
//}
?>
<style>
    /* Important part */
    #chooseGallery .modal-dialog{
        overflow-y: initial !important
    }
    #chooseGallery .modal-body{
        height: 400px;
        overflow-y: auto;
    }
    .selected{  
        border: 5px solid blue;
    }



    .profIMG_from_gallery{ width:110px; height:100px; cursor:pointer; opacity: 1; filter: alpha(opacity=100);}


    #container {
        margin: 20px;
        width: 163px;
        height: 52px;
    }

</style>

<?php
echo $this->headLink()

        ->prependStylesheet($this->basePath() . '/css/imgareaselect.css')
?>

<link href="https://fonts.googleapis.com/css?family=Raleway:400,300,600,800,900" rel="stylesheet" type="text/css">

<?php $session = new \Zend\Session\Container('user'); ?>
<div class="col-sm-3 profile-img col-xs-4">
    <?php if (!empty($this->profile_pic['image_name'])) { ?>
        <img   id="profile_photo" src="<?php echo $this->basePath(MATRIMONIAL_IMAGE_PATH) . $this->profile_pic['image_name']; ?>" style="max-width:146px;" height="146"/>
    <?php } else { ?>
        <img src="<?php echo $this->basePath('img/default_user.png') ?>" width="146" height="146"/>
    <?php } ?>
    <p style="margin-bottom:2px;"><?php echo $this->translate('Membership ID ') ?> <?php echo $session->offsetGet('ref_no') ?></p>
    <!-- <button class="btn btn-default" data-toggle="modal" data-target="#myModal" style="float:none;"><?php echo $this->translate('Upload Photo') ?></button> -->
    <a href="#"  data-toggle="modal" data-target="#avatar-modal4">Upload Photo</a> 
     
    
</div>
<?php //Zend\Debug\Debug::dump($this->profile_pic['image_name']);?>
<div class="col-sm-6 col-xs-8">
    <div class="row">
        <div class="col-xs-5"><?php echo $this->translate('Name') ?></div>
        <div class="col-xs-7"><?php echo $this->userSummary['name_title_user']; ?> <?php echo $this->userSummary['full_name']?> <?php echo $this->userSummary['last_name']; ?></div>
        <div class="col-xs-5"><?php echo $this->translate('Father’s. Name') ?></div>
        <div class="col-xs-7"><?= $this->MyHelper()->getFamilyInfoByIdMatrimonial($this->user_id, 1)['title'] . " " . $this->MyHelper()->getFamilyInfoByIdMatrimonial($this->user_id, 1)['name']. " " . $this->MyHelper()->getFamilyInfoByIdMatrimonial($this->user_id, 1)['last_name'];  ?></div>

        <div class="col-xs-5"><?php echo $this->translate('Address') ?></div>
        <div class="col-xs-7"><?php echo $this->userSummary['address'] ?></div>

        <div class="col-xs-5"><?php echo $this->translate('Contact Number') ?></div>
        <div class="col-xs-7"><?php echo $this->userSummary['mobile_no'] ?></div>

        <div class="col-xs-5"><?php echo $this->translate('Profession') ?></div>
        <div class="col-xs-7"><?php echo $this->userSummary['profession_name'] ?></div>

        <div class="col-xs-5"><?php echo $this->translate('Email ID') ?></div>
        <div class="col-xs-7"><?php echo $session->offsetGet('email') ?></div>
        
    </div>
</div>

<div class="col-sm-3" align="center">

    <canvas id="demo-3" style="demo"></canvas>
</div>
<center> <span><?= $percent[0] ?>% Completed</span></center>

<div class="col-sm-6" style="margin-top:22px; float:right; text-align:right;">
       <p style="text-align:right;">Connected <?php $this->MyHelper()->findage($this->userSummary['created_date']); ?> ago</p>
   </div>
<!--********************************upload profile modal********************************-->
<!--  <div class="modal fade" id="myModal">
<div class="modal-dialog">
<div class="modal-content">
<form id="form" enctype="multipart/form-data" role="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Upload Profile Photo</h4>
    </div>
    <div class="modal-body">
        <div id="messages" style="font-weight:bold;width:100%;height:auto;text-align:center;"></div>
        <input type="file" name="img_file" id="img_file">
                                        <h5 style="font-weight:bold;color:cornflowerblue;">OR</h5>
                                        <a href="#" id="profileFrom_gallery" data-toggle="modal" data-target="#chooseGallery" style="font-weight:bold;font-size:14px;color:chocolate;">Choose from Gallery</a>
    </div>
    <div class="modal-footer">
        
        <button type="submit" class="btn btn-default" style="width:60px;">Upload</button>
    </div>
</form>
</div>
</div>
</div> -->

<!-- Modal Window for Profile Image Starts Here-->

<div class="modal fade" id="avatar-modal4" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        
        <div class="modal-content">
            
             <form class="cropimage" method="post" enctype="multipart/form-data" action="<?php echo $this->url("profile", array('action'=>'uploadProfileImagesMatrimonial')) ?>">
		<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title" id="avatar-modal-label">Profile Picture</h4>
                </div>
                 
                                                <input type="file" name="photoimg" class="photoimg" />
						<input type="hidden" name="hdn-profile-id" class="hdn-profile-id" value="1" />
						<input type="hidden" name="hdn-x1-axis" class="hdn-x1-axis" value="" />
						<input type="hidden" name="hdn-y1-axis" class="hdn-y1-axis" value="" />
						<input type="hidden" name="hdn-x2-axis" value="" class="hdn-x2-axis" />
						<input type="hidden" name="hdn-y2-axis" value="" class="hdn-y2-axis" />
						<input type="hidden" name="hdn-thumb-width" class="hdn-thumb-width" value="" />
						<input type="hidden" name="hdn-thumb-height" class="hdn-thumb-height" value="" />
						<input type="hidden" name="action" value="" id="action" />
                                                <input type="hidden" name="uid" value="" id="uid" />
						<input type="hidden" name="image_name" value="" class="image_name" />
                                                <input type="hidden" name="crop_enabled" value="no" class="crop_enabled" />
						
						<div class='preview-avatar-profile' style="position:relative;">
					</div>
					<div id="thumbs" style="padding:5px; width:600p"></div>
		<div class="modal-footer">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                    <button type="button" class="btn-crop btn btn-primary">Crop & Save</button>
                </div>			
             </form>
        </div>
    </div>
</div>

<!-- Modal Window for Profile Image Ends Here-->

<!--**************************upload profile modal ends************************-->	
<!--**************************************************-->	
<!--**************************************************-->	
<!--********************************Choose Gallery modal********************************-->
<div class="modal fade" id="chooseGallery">
    <div class="modal-dialog">
        <div class="modal-content">                        
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Upload Profile Photo</h4>
            </div>
            <div class="modal-body">
                <div id="messages2" style="font-weight:bold;width:100%;height:auto;text-align:center;"></div>
                <div class="gallery">	  
                    <?php
                    if (count($images)) {
                        foreach ($images as $img) {
                            ?>
                            <div class="col-xs-4">
                                <div class="col-xs-12"><img class="profIMG_from_gallery img-responsive" id="<?php echo $img['image_path']; ?>" src="<?php echo $this->basePath($img['image_path']) ?>" /></div>
                            </div>				
                        <?php }
                    }
                    ?>
                    <input type="hidden" name="selected_from_gallery" id="selected_from_gallery" value=""/>
                </div>
            </div>
            <div class="modal-footer">
                <!--<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>-->
                <button type="button" id="Updtbtngallery" class="btn btn-default" style="width:60px;">Save</button>
            </div>                        
        </div>
    </div>
</div>	
<!--**************************Choose Gallery modal ends************************-->			

<script>
    $('#form').submit(function (e) {
        var form = $(this);
        var formdata = false;
        if (window.FormData) {
            formdata = new FormData(form[0]);
        }

        var formAction = form.attr('action');

        $.ajax({
            type: 'POST',
            url: '<?php echo $this->basePath() ?>' + '/account/AjaxImgUpload',
            cache: false,
            data: formdata ? formdata : form.serialize(),
            contentType: false,
            processData: false,
            success: function (response) {
                if (response.Status != "false") {
                    $('#messages').removeClass('alert alert-danger');
                    $('#messages').addClass('alert alert-success').text(response.message);
                    setTimeout(function () {
                        $('#myModal').modal('hide')
                    }, 4000);
                    $("#profile_img1").attr('src', '<?php echo $this->basePath() ?>' + response.file_path);
                } else {
                    $('#messages').addClass('alert alert-danger').text(response.message);
                }
            }
        });
        e.preventDefault();
    });
</script>

<script>
    /***************make image selectable*********************/
    $('img').click(function () {
        $('.selected').removeClass('selected'); // removes the previous selected class
        $(this).addClass('selected'); // adds the class to the clicked image
        var imgName = $(this).attr('id');
        $("#selected_from_gallery").empty();
        $("#selected_from_gallery").val(imgName);
    });
    /***********update user profile img***************/
    $('#Updtbtngallery').click(function () {
        var ImageName = $("#selected_from_gallery").val();
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->basePath() ?>' + '/account/ChangeProfImgFrGallery',
            cache: false,
            data: {ImageName: ImageName},
            dataType: 'json',
            success: function (response) {
                if (response.Status != "false") {
                    $('#messages2').removeClass('alert alert-danger');
                    $('#messages2').addClass('alert alert-success').text(response.message);
                    setTimeout(function () {
                        $('#myModal').modal('hide'),
                                $('#chooseGallery').modal('hide')
                    }, 4000);
                    $("#profile_img1").attr('src', '<?php echo $this->basePath() ?>' + response.file_path);
                } else {
                    $('#messages2').addClass('alert alert-danger').text(response.message);
                }
                setTimeout(function () {
                    $('#myModal').modal('hide');
                    $('#avatar-modal4').modal('hide');
                    $('#chooseGallery').modal('hide');
                }, 1000);

            }
        });
    });
</script>


<?php
        echo $this->inlineScript()
                ->prependFile($this->basePath() . '/js/jquery.imgareaselect.js')
                ->prependFile($this->basePath() . '/js/jquery.form.js')
                //->prependFile($this->basePath() . '/js/upload_photo.js')
        ;
        ?>
<script type="text/javascript">
jQuery(document).ready(function(){

jQuery('.photoimg').on('change', function(){ 
        jQuery(".preview-avatar-profile").html('');
        jQuery(".preview-avatar-profile").html('Uploading....');
        jQuery(".cropimage").ajaxForm(
        {
        target: '.preview-avatar-profile',
        success:    function() { 
                        jQuery('img.photo').imgAreaSelect({
                        aspectRatio: '0:0',
                        parent: '.preview-avatar-profile',
                        onSelectEnd: getSizes,
                });
                jQuery('.image_name').val(jQuery('.photo').attr('file-name'));
                }
        }).submit();

});

//// Function for Save Image Starts Here ////	 

jQuery('.btn-crop').on('click', function(e){
    e.preventDefault();
    var profileImageUploadUrl='<?php echo $this->url("profile", array('action'=>'uploadProfileImagesMatrimonial')) ?>';
    params = {
        //targetUrl: 'profile.php?action=save',
        targetUrl: profileImageUploadUrl+'?action=save',
        action: 'save',
        x_axis: jQuery('.hdn-x1-axis').val(),
        y_axis : jQuery('.hdn-y1-axis').val(),
        x2_axis: jQuery('.hdn-x2-axis').val(),
        y2_axis : jQuery('.hdn-y2-axis').val(),
        thumb_width : jQuery('.hdn-thumb-width').val(),
        thumb_height:jQuery('.hdn-thumb-height').val()        
    };
    saveCropImage(params);
});

//// Function for Save Image Ends Here ////
	    
//// Function for Get the Image Size Starts Here ////	 
	    
function getSizes(img, obj)
{
    var x_axis = obj.x1;
    var x2_axis = obj.x2;
    var y_axis = obj.y1;
    var y2_axis = obj.y2;
    var thumb_width = obj.width;
    var thumb_height = obj.height;
    if(thumb_width > 0)
        {
            jQuery('.hdn-x1-axis').val(x_axis);
            jQuery('.hdn-y1-axis').val(y_axis);
            jQuery('.hdn-x2-axis').val(x2_axis);
            jQuery('.hdn-y2-axis').val(y2_axis);
            jQuery('.hdn-thumb-width').val(thumb_width);
            jQuery('.hdn-thumb-height').val(thumb_height);
            jQuery('.crop_enabled').val('yes');
        }
    else
        alert("Please select portion..!");
}
	
//// Function for Get the Image Size Ends Here ////
//
//// Function for Save the Crop Image Starts Here ////
        
function saveCropImage(params) {
jQuery.ajax({
    url: params['targetUrl'],
    cache: false,
    dataType: "html",
    data: {
        action: params['action'],
        id: jQuery('.hdn-profile-id').val(),
         t: 'ajax',
                            w1:params['thumb_width'],
                            x1:params['x_axis'],
                            h1:params['thumb_height'],
                            y1:params['y_axis'],
                            x2:params['x2_axis'],
                            y2:params['y2_axis'],
       image_name :jQuery('.image_name').val(),
       crop_enabled:jQuery('.crop_enabled').val()
    },
    type: 'Post',
   // async:false,
    success: function (response) {
            alert(response);
            jQuery('.changePic').hide();
            jQuery('.change-pic').show();
            jQuery(".imgareaselect-border1,.imgareaselect-border2,.imgareaselect-border3,.imgareaselect-border4,.imgareaselect-border2,.imgareaselect-outer").css('display', 'none');
            //jQuery(".avatar-edit-img").attr('src', response);
            jQuery(".preview-avatar-profile").html('');
            jQuery(".photoimg").val('');
            $('#avatar-modal4').modal('hide');
            window.location = window.location;

    },
    error: function (xhr, ajaxOptions, thrownError) {
        alert('status Code:' + xhr.status + 'Error Message :' + thrownError);
    }
});
}

//// Function for Save the Crop Image Ends Here ////

});

</script>


<script>

<?php echo $percent[1] ?>

    $('#demo-3').waterbubble({txt: '<?php echo $percent[0] ?>%', });
</script>
<script type="text/javascript">


    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36251023-1']);
    _gaq.push(['_setDomainName', 'jqueryscript.net']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();



    /**
     * 水球图 wataerbubble
     * @author fiona23 (fiona_fanmy@163.com)
     * @2016.3.8 version 1.2
     *  chrome bug fixed
     * @version 1.1
     * Because the bug of chrome V 46.0.2490.86, I have to render the text after animation, so guilty.
     * I have reported this issue to google, hoping it would be sovled in the new version.
     */



</script>
