<style>
    /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
    .show {display:block;}

    label {

        margin-bottom: 0;

    }

    .grid-view ul li .col-xs-2 .profile-pic img {
        border-radius: 50%;
        height: 60px;
        overflow: hidden;
        width: 60px;
    }

    .grid-view ul li .col-xs-2 h3 {
        color: #eda344;
        font-size: 11px;
        font-weight: normal;
        margin: 0;
        padding: 1px 0;
        text-align: center;
    }

    .grid-view ul li .col-xs-2 h4 {
        color: #666666;
        font-size: 11px;
        font-weight: normal;
        margin: 0;
        padding: 1px 0;
        text-align: center;
    }

    .grid-view ul li .col-xs-2 .btn {
        border: 0 none;
        border-radius: 3px;
        display: table;
        font-size: 10px;
        font-weight: 700;
        line-height: 1.1;
        margin: 0 auto;
        padding: 4px 5px;
        float:right;
    }

    .list-view ul li .col-xs-10 .col-xs-8 {
        font-size: 11px;
        font-weight: normal;
        margin: 0;
        padding: 0 0 0;

    }


    .grid-view ul li {
        color: #636363;
        float: left;
        font-size: 11px;
        margin: 0 7px 20px;
    }

    .list-view ul li {

        width:97%;
    }


</style>

<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/componant-vs-14.css')
?>
<div class="container orange-panelbg">
    <div class="col-sm-3 col-sm-3-new width20per">
      <?php include('sidebar_left_member.phtml');?>

    </div>

    <div class="col-sm-9 width80per">
        <div class="myshaadi_wrap">
            <div class="welcome_screen"></div>


            <div class="clear"></div>
        </div>

        <!--MY SHAADI LEFT-->
        <div class="col-sm-9" style="padding-top:0; padding-left:0;">

            <!--MIDDLE SECTION-->
            <div id="my_rustagi_middle">
                <!--Pin Interest render-->

                <!-- request pending  -->
                <div id="recently_joined" style="display: block;">
                    <div class="mid_box">
                        <div class="mid_box_header">
                            Request Pending <span class="recently_joined_count"> (<?php echo count($this->receivedMember->receivedMember) ? count($this->receivedMember->receivedMember) : '' ?>) </span>
                                    <!--<p class="view_all"><a href="#" class="light_link_blue" target="_blank">View all</a></p>-->
                            <div class="col-xs-3 pull-right">
                                <ul class="prof-view pull-right">
                                    <li><a href="#" id="list"><span class="glyphicon glyphicon-th-list"></span><span class="sr-only">List View</span></a></li>
                                    <li><a href="#" id="grid"><span class="glyphicon glyphicon-th"></span><span class="sr-only">Grid View</span></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-9">

                            </div>

                        </div>

                        <div class="clearfix"></div>
                        <!-- <div class="filters_loader_box">
                                <div id="filters_data_loader"><h1>Loading...</h1></div>
                        </div> -->
                        <div id="profile">

                            <div class="commen-list grid-view">
                                <ul id="items">
                                    <li>
                                        <div class="col-xs-2"></div>
                                        <div class="col-xs-10">
                                            <div class="col-xs-2">Name</div>
                                            <div class="col-xs-3">F. Name</div>
                                            <div class="col-xs-3">Occupation</div>
                                            <div class="col-xs-2">Area</div>
                                            <div class="col-xs-2">Branch</div>
                                        </div>
                                    </li>

                                    <?php
                                    $count = count($this->receivedMember->receivedMember);

                                    if ($count == 0) {
                                        echo 'No request is pending';
                                    }
                                    foreach ($this->receivedMember->receivedMember as $receivedMember) {

                                        foreach ($this->receivedMember->memInfo as $memInfos) {
                                            if ($memInfos['received'] == $receivedMember->user_id) {
                                                $meid = $memInfos['id'];
                                            }
                                        }

//                                        foreach ($this->receivedMember->memInfo as $memInfos){
                                        if (!empty($receivedMember['image_path'])) {
                                            $imagepath = 'uploads/' . $receivedMember['image_path'];
                                        } else {
                                            $imagepath = 'images/default_user.png';
                                        }

                                        //\Zend\Debug\Debug::dump($receivedMember);
                                        ?>

                                        <li class="li_listmember" id="<?php echo 'satya_prakash_madheshiya_' . $receivedMember['user_id'] ?>">
                                            <div class="col-xs-2">
                                                <div class="profile-pic"><img src="<?php echo $this->basePath() ?>/images/default_user.png"></div>
                                                <h3><?php echo $receivedMember['full_name'] ?></h3>
                                                <h3>Director</h3>
                                                <h4>Delhi</h4>
                                                <h3> <a href="<?php echo $this->url('profile', array('action' => 'profile-view-member'),array('query'=>array('member_id'=>$receivedMember['user_id']))) ?>" class="btn btn-default" >More</a>
                                                    <a href="javascript:void(0)" class="btn btn-default" style="margin-right:2px;" onclick="acceptRequest(<?php echo $meid; ?>, <?php echo $receivedMember['user_id']; ?>, 'accept')">Accept</a>
                                                </h3>
                                                <h6> 
                                                    <a href="javascript:void(0)" class="btn btn-default" style="float:left;" onclick="acceptRequest(<?php echo $meid; ?>, <?php echo $receivedMember['user_id']; ?>, 'accept')">Accept</a>
                                                    <a href="<?php echo $this->url('profile', array('action' => 'profile-view-member'),array('query'=>array('member_id'=>$receivedMember['user_id']))) ?>" class="btn btn-default" style="margin-left:2px; float:left !important;" >More</a>
                                                </h6>
                                            </div>
                                            <div class="col-xs-10">
                                                <div class="col-xs-8">
                                                    <div class="col-xs-2 col-xs-2-member">Name</div>

                                                    <div class="col-xs-3 col-xs-3-member">Mr Test Senior</div>
                                                    <div class="col-xs-2 col-xs-2-member">F. Name</div>

                                                    <div class="col-xs-3 col-xs-3-member"> testkjk </div>
                                                    <div class="col-xs-2 col-xs-2-member">Occupation</div>

                                                    <div class="col-xs-3 col-xs-3-member">Lecturer</div>
                                                    <div class="col-xs-2 col-xs-2-member">Address</div>
                                                    <div class="col-xs-3 col-xs-3-member">karol bagh New Delhi</div>

                                                    <div class="col-xs-2 col-xs-2-member">Branch</div>
                                                    <div class="col-xs-3 col-xs-3-member">Rustagi Sabha Palam</div> 
                                                </div>
                                                <div class="clearfix"></div>
                                                <div class="col-xs-8" style="padding:0 0;">Short Description : President ( 2012 - Till )</div>
                                                <div class="col-xs-4" style="padding:0 0;">
                                                    <div style="">
                                                        <span>Follow : -</span>
                                                        <ul class="follow">
                                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="facebook"></a></li>
                                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="twitter"></a></li>
                                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="gplus"></a></li>
                                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="linkedin"></a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <div class="clearfix"></div>
                                                <div class="col-xs-12" style="display:none;">
                                                    <p></p>
                                                </div>
                                            </div>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- request pending --> 



            </div>
        </div>
        <!--MY rustagi RIGHT-->
        <div id="my_rustagi_right" class="col-sm-3 col-sm-3new pull-right">
           <?php include('sidebar_right_member.phtml');?>
        </div>
        <!--end right_half-->
        <br class="clear">
    </div>


</div>

<script>

<?php echo $percent[1] ?>

    $('#demo-3').waterbubble({txt: '<?php echo $percent[0] ?>%', });
</script>


<script>
    $(document).ready(function () {
        $("#contact_detail").click(function () {
            $(".contactde").toggle();
        });

    });
</script>

<script>

    function acceptRequest(id, uid, type) {
        $.ajax({
            url: '<?php echo $this->url('profile', array('action' => 'interestaccepted')) ?>',
            data: {
                id: id, uid: uid, type: type
            },
            error: function (request, status, error) {
                console.log(status);
            },
            success: function (data) {
                $('#satya_prakash_madheshiya_' + uid).hide();
                console.log(data);
            },
            type: 'POST'
        });
    }
</script>