<?php
$name           =    $data['name'];
$username       =    $data['username'];
$email          =    $this->MyHelper()->getModifiedEmail($data['email']);
$mobile         =    $this->MyHelper()->getModifiedMobileNo($data['mobile']);
$path           =    "http://www.rustagisamaj.com/emailer/";
$date           =    date('d/m/Y');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
      <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Rustagi Samaj</title>
      <style type="text/css">
/* Client-specific Styles */

#outlook a {
	padding: 0;
} /* Force Outlook to provide a "view in browser" menu link. */
body {
	width: 100% !important;
	-webkit-text-size-adjust: 100%;
	-ms-text-size-adjust: 100%;
	margin: 0;
	padding: 0;
	background: #f3f3f3;
}
/* Prevent Webkit and Windows Mobile platforms from changing default font sizes, while not breaking desktop design. */
.ExternalClass {
	width: 100%;
} /* Force Hotmail to display emails at full width */
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {
	line-height: 100%;
} /* Force Hotmail to display normal line spacing. */
#backgroundTable {
	margin: 0;
	padding: 0;
	width: 100% !important;
	line-height: 100% !important;
}
img {
	outline: none;
	text-decoration: none;
	border: none;
	-ms-interpolation-mode: bicubic;
}
a img {
	border: none;
}
.image_fix {
	display: block;
}
p {
	margin: 0px 0px !important;
}
table td {
	border-collapse: collapse;
}
table {
	border-collapse: collapse;
	mso-table-lspace: 0pt;
	mso-table-rspace: 0pt;
}
a {
	color: #33b9ff;
	text-decoration: none;
	text-decoration: none!important;
}
/*STYLES*/
table[class=full] {
	width: 100%;
	clear: both;
}
.table {
	border-collapse: collapse;
}
.table td {
	border: 1px solid #DDD;
}
		 
		 
         /*IPAD STYLES*/
         @media only screen and (max-width: 640px) {
a[href^="tel"], a[href^="sms"] {
	text-decoration: none;
	color: #0a8cce; /* or whatever your want */
	pointer-events: none;
	cursor: default;
}
.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
	text-decoration: default;
	color: #0a8cce !important;
	pointer-events: auto;
	cursor: default;
}
table[class=devicewidth] {
	width: 440px!important;
	text-align: center!important;
}
table[class=devicewidthmob] {
	width: 420px!important;
	text-align: center!important;
}
table[class=devicewidthinner] {
	width: 420px!important;
	text-align: center!important;
}
img[class=banner] {
	width: 440px!important;
	height: 157px!important;
}
img[class=col2img] {
	width: 440px!important;
	height: 330px!important;
}
table[class="cols3inner"] {
	width: 100px!important;
}
table[class="col3img"] {
	width: 131px!important;
}
img[class="col3img"] {
	width: 131px!important;
	height: 82px!important;
}
table[class='removeMobile'] {
	width: 10px!important;
}
img[class="blog"] {
	width: 420px!important;
	height: 162px!important;
}
}

         /*IPHONE STYLES*/
         @media only screen and (max-width: 480px) {
a[href^="tel"], a[href^="sms"] {
	text-decoration: none;
	color: #0a8cce; /* or whatever your want */
	pointer-events: none;
	cursor: default;
}
.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
	text-decoration: default;
	color: #0a8cce !important;
	pointer-events: auto;
	cursor: default;
}
table[class=devicewidth] {
	width: 280px!important;
	text-align: center!important;
}
table[class=devicewidthmob] {
	width: 260px!important;
	text-align: center!important;
}
table[class=devicewidthinner] {
	width: 260px!important;
	text-align: center!important;
}
img[class=banner] {
	width: 280px!important;
	height: 100px!important;
}
img[class=col2img] {
	width: 280px!important;
	height: 210px!important;
}
table[class="cols3inner"] {
	width: 260px!important;
}
img[class="col3img"] {
	width: 280px!important;
	height: 175px!important;
}
table[class="col3img"] {
	width: 280px!important;
}
img[class="blog"] {
	width: 260px!important;
	height: 100px!important;
}
td[class="padding-top-right15"] {
	padding: 15px 15px 0 0 !important;
}
td[class="padding-right15"] {
	padding-right: 15px !important;
}
}
</style>
      </head>
      <body>

<!-- Start of main-banner -->
<table width="100%" bgcolor="#f3f3f3 " cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="banner">
        <tbody>
    <tr>
            <td><table width="560" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                <tbody>
                <tr>
                    <td width="100%"><table width="560" align="center" cellspacing="0" cellpadding="0" border="0" class="devicewidth">
                        <tbody>
                        <tr> 
                            <!-- start of image -->
                            <td align="center" st-image="banner-image" style="background:#fff;">
                            <div class="imgpop"> 
                            
                            <div class="imgpop" style="background:#fff !important;"> 
                           		<div style="width:20%; float:left;">
                                	<img src="<?php echo $path;?>/logo_emailr.png" />
                                </div>
                                <div style="width:60%; float:left;">
                                	<span style="font-size:25px; color:#443013; font-family:'Arial Black', Gadget, sans-serif; line-height:70px;">Rustagi Samaj</span>
                                </div>
                               
                            
                            </div>
                            
                           </div></td>
                          </tr>
                          
                           <tr>
                            <td style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">
                            <hr style="height:1px; color:#BBB; background-color:#BBB;">
                            </td>
                          </tr>
                      </tbody>
                      </table>
                    
                    <!-- end of image --></td>
                  </tr>
              </tbody>
              </table></td>
          </tr>
  </tbody>
      </table>
<!-- End of main-banner --> 

<!-- leftimage -->
<table width="100%" bgcolor="#f3f3f3 " cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="footer">
        <tbody>
    <tr>
            <td><table width="560" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                <tbody>
                <tr>
                    <td width="100%"><table bgcolor="#ffffff" width="560" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                        <tbody>
                        <!-- Spacing -->
                        <tr>
                            <td height="10" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                          </tr>
                        <!-- Spacing -->
                        <tr>
                            <td><!-- start of social icons -->
                            
                            <table width="210" align="left" vaalign="middle"  border="0" cellpadding="0" cellspacing="0" class="devicewidthmob">
                                <tbody>
                                <tr>
                                    <td width="20"></td>
                                    <td style="font-family: Helvetica, arial, sans-serif; font-size:12px; color: #0a0a0a; text-align:left; line-height: 24px;" class="padding-top-right15"> Dear "<?=$name;?>"</td>
                                  </tr>
                              </tbody>
                              </table>
                            
                            <!-- end of social icons --> 
                            
                            <!-- logo -->
                            
                            <table width="194" align="right" border="0" cellpadding="0" cellspacing="0" class="devicewidthmob">
                                <tbody>
                                <tr>
                                    <td style="font-family: Helvetica, arial, sans-serif; font-size: 12px; color: #0a0a0a; text-align:left; line-height: 24px;" class="padding-top-right15"> Date: <?=$date?> </td>
                                  </tr>
                              </tbody>
                              </table>
                            
                            <!-- end of logo --></td>
                          </tr>
                        <!-- Spacing --> 
                        <!-- Spacing -->
                      </tbody>
                      </table></td>
                  </tr>
              </tbody>
              </table></td>
          </tr>
  </tbody>
      </table>
<!-- end of left image --> 

<!-- leftimage -->
<table width="100%" bgcolor="#f3f3f3 " cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="left-image">
        <tbody>
    <tr>
            <td><table width="560" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                <tbody>
                <tr>
                    <td width="100%"><table bgcolor="#ffffff" width="560" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                        <tbody>
                        <!-- Spacing -->
                        <tr>
                            <td height="20" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                          </tr>
                        <!-- Spacing -->
                        <tr>
                            <td><table width="520" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                                <tbody>
                                <tr>
                                    <td><!-- spacing for mobile devices-->
                                    
                                    <table width="100%" align="right" border="0" cellpadding="0" cellspacing="0" class="devicewidthmob">
                                        <tbody>
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 12px; color: #000000; text-align:left; line-height: 20px;" class="padding-right15">
                                            <span style="color:#c52d2f;"> <strong>Subject:- </strong></span>
                                            &nbsp;&nbsp;Welcome to Rustagi Samaj, India`s First online Rustagi Samaj's Social & Matrimonial Portal for All Member's information. </td>
                                          </tr>
                                        
                                        <!-- Spacing -->
                                        <tr>
                                            <td width="100%" height="15" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                                          </tr>
                                        <!-- /Spacing -->
                                        
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 13px; color: #0a0a0a; text-align:left; line-height: 20px;" class="padding-top-right15"><strong>Welcome to Rustagi Samaj, </strong></td>
                                          </tr>
                                        <!-- end of title --> 
                                        <!-- Spacing -->
                                        <!-- /Spacing --> 
                                        <!-- content -->
                                       
                                        <!-- end of content --> 
                                        
                                        <!-- Spacing -->
                                      
                                        
                                        <!-- content -->
                                        
                                       
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 12px; color: #000000; text-align:left; line-height: 24px;" class="padding-right15"></td>
                                          </tr>
                                        
                                        <!-- end of content --> 
                                        
                                        <!-- Spacing -->
                                        <tr>
                                            <td height="15" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">
                                            
                                            
                                            
                                            
                                            </td>
                                          </tr>
                                        <tr>
                                            <td><!-- start of social icons -->
                            
                                             
                                              
                            
                            <!-- end of social icons --> 
                            
                            <!-- logo -->
                            
                            
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                            
                            <!-- end of logo --></td>
                                          </tr>
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                                         <tr>
                                            <td><!-- start of social icons -->
                                            
                                            
                                            
                                            
                            
                           
                              
                              
                              
                              
                            
                            
                            <!-- end of social icons --> 
                            
                            
               
                            
                            <!-- logo --><!-- end of logo --></td>
                                          </tr> 
                                          
                                          
                                          
                             
                                       
                                      
                                       <!-- <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size:13px; color: #000000; font-weight:bold; text-align:left; line-height: 24px;" class="padding-right15"> For More details Please Download our Mobile App </td>
                                          </tr>-->
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 12px; color:#000000; text-align:left; line-height: 20px;" class="padding-right15">
                                            Thanks for Registration and Showing interest in Rustagi Samaj , India`s First online Rustagi Samaj's Social & Matrimonial Portal for All Member's information. 
                                           </td>
                                          </tr>
                                        <tr>
                                            <td width="100%" height="15" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                                          </tr>
                                      <!--  <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size:12px; color: #000000; font-weight:normal; text-align:left; line-height: 24px;" class="padding-right15"> You can log on our live chat for More Assistance . </td>
                                          </tr>-->
                                        <tr>
                                          <td><!-- start of social icons -->
                            
                            <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%" class="devicewidthmob" vaalign="middle">
                                <tbody>
                                    
                                <tr>
                                  <td></td>
                                  <td width="270" class="padding-top-right15" style="font-family: Helvetica, arial, sans-serif; font-size:12px; color: #0a0a0a; font-weight:bold; text-align:left; line-height: 24px;">
                                  Username:</td>
                                  
                                   <td width="247" class="padding-top-right15" style="font-family: Helvetica, arial, sans-serif; font-size:12px; color: #0a0a0a; font-weight:bold; text-align:left; line-height: 24px;">
                                  <?=$username;?></td>
                                </tr>
                                    
                                <tr>
                                  <td></td>
                                  <td width="270" class="padding-top-right15" style="font-family: Helvetica, arial, sans-serif; font-size:12px; color: #0a0a0a; font-weight:bold; text-align:left; line-height: 24px;">
                                  Your Email ID:</td>
                                  
                                   <td width="247" class="padding-top-right15" style="font-family: Helvetica, arial, sans-serif; font-size:12px; color: #0a0a0a; font-weight:bold; text-align:left; line-height: 24px;">
                                  <?=$email;?></td>
                                </tr>
                                
                                <tr>
                                    <td width="3"></td>
                                    <td class="padding-top-right15" 
                                    style="font-family: Helvetica, arial, sans-serif; font-size:11px; color: #0a0a0a; font-weight:bold; text-align:left; 
                                    line-height: 24px;">Mobile No:</td>
                                    
                                     <td class="padding-top-right15" style="font-family: Helvetica, arial, sans-serif; font-size:12px; color: #0a0a0a; font-weight:bold; text-align:left; line-height: 24px;">
                                  <?=$mobile;?></td>
                                  </tr>

                                  
                                   <tr>
                                    <td width="3"></td>
                                    <td colspan="2" class="padding-top-right15" style="font-family: Helvetica, arial, sans-serif; font-size:11px; color: #0a0a0a; font-weight:bold; text-align:left; line-height: 20px;">Please use Email or Mobile No. to Login.<br/><br/>
                                    You are requested to change your password on regular intervals.
                                    
                                    </td>
                                  </tr>
                              </tbody>
                              </table>
                            
                            <!-- end of social icons --> 
                            
                            <!-- logo --><!-- end of logo --></td>
                            
                            
                            
                            
                            
                                        </tr>
                                        <tr>
                                          <td height="15" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                                        </tr>
                                        <tr>
                                            <td width="100%" height="15" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                                          </tr>
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 11px; color: #000000; text-align:left; line-height: 24px;" class="padding-right15">For  any Assistance or  query write to  </td>
                                          </tr>
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 11px; color: #000000; text-align:left; line-height: 24px;" class="padding-right15"> write to <a href="mailto:admin@rustagisamaj.com">admin@rustagisamaj.com</a> or Call +91-8130454242, We will be Glad to Assist You </td>
                                          </tr>
                                        <!-- Spacing -->
                                        <tr>
                                            <td width="100%" height="15" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                                          </tr>
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 12px; color: #c52d2f; text-align:left; line-height: 24px;" class="padding-right15"><strong>For Rustagi Samaj</strong></td>
                                          </tr>
                                        <tr>
                                            <td style="font-family: Helvetica, arial, sans-serif; font-size: 12px; color: #000000; text-align:left; line-height: 24px;" class="padding-right15"> Ph +91-8130454242 </td>
                                          </tr>
                                      </tbody>
                                      </table>
                                    
                                    <!-- end of for mobile devices--></td>
                                  </tr>
                              </tbody>
                              </table></td>
                          </tr>
                        <!-- Spacing -->
                        <tr>
                            <td height="12" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                          </tr>
                        <!-- Spacing --> 
                        <!-- Spacing --> 
                        <!-- Spacing -->
                      </tbody>
                      </table></td>
                  </tr>
              </tbody>
              </table></td>
          </tr>
  </tbody>
      </table>
<!-- end of left image --> 

<!-- Start of footer -->
<table width="100%" bgcolor="#f3f3f3 " cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="footer">
        <tbody>
    <tr>
            <td><table width="560" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                <tbody>
                <tr>
                    <td width="100%"><table bgcolor="#ffffff" width="560" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                        <tbody>
                        <!-- Spacing -->
                        <tr>
                            <td height="10" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly; color:#BBB;"><hr style="height:1px; color:#BBB; background-color:#BBB;" /></td>
                          </tr>
                        <!-- Spacing --> 
                        
                        <!-- Spacing -->
                        <tr>
                            <td height="15" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly; color:#BBB;">&nbsp;</td>
                          </tr>
                        <!-- Spacing -->
                        <tr>
                            <td><!-- start of social icons -->
                            
                            <table width="106" height="40" align="left" vaalign="middle"  border="0" cellpadding="0" cellspacing="0">
                                <tbody>
                                <tr>
                                    <td align="left" width="20" style="font-size:1px; line-height:1px;">&nbsp;</td>
                                    <td width="24" height="24" align="left"><div class="imgpop"> <a target="_blank" href="https://www.facebook.com/"> <img src="<?php echo $path;?>/fb-icon.png" alt="" border="0" width="24" height="24" style="display:block; border:none; outline:none; text-decoration:none;"> </a> </div></td>
                                    <td align="left" width="10" style="font-size:1px; line-height:1px;">&nbsp;</td>
                                    <td width="25" height="25" align="right"><div class="imgpop"> <a target="_blank" href="https://twitter.com/"> <img src="<?php echo $path;?>/twitter.png" alt="" border="0" width="25" height="25" style="display:block; border:none; outline:none; text-decoration:none;"> </a> </div></td>
                                    <td align="left" width="10" style="font-size:1px; line-height:1px;">&nbsp;</td>
                                    <td width="27" height="27" align="right"><div class="imgpop"> <a target="_blank" href="https://plus.google.com/collections/featured"> <img src="<?php echo $path;?>/google-plus.png" alt="" border="0" width="27" height="27" style="display:block; border:none; outline:none; text-decoration:none;"> </a> </div></td>
                                  </tr>
                              </tbody>
                              </table>
                            
                            <!-- end of social icons --> 
                            
                            <!-- logo -->
                            
                            <table width="291" align="right" border="0" cellpadding="0" cellspacing="0">
                                <tbody>
                                <tr>
                                    <td>
                                    
                                    </td>
                                  </tr>
                              </tbody>
                              </table>
                            
                            <!-- end of logo --></td>
                          </tr>
                        <!-- Spacing -->
                        <tr>
                            <td height="10" style="font-size:1px; line-height:1px; mso-line-height-rule: exactly;">&nbsp;</td>
                          </tr>
                        <!-- Spacing -->
                      </tbody>
                      </table></td>
                  </tr>
              </tbody>
              </table></td>
          </tr>
  </tbody>
      </table>
<!-- End of footer -->

</body>
</html>