<table  width="100%" style="border:none !important;">
<tbody>
<?php
if(count($sponsertypes)>0){
	$i=1;
 foreach ($sponsertypes as $sponsertype) {
?>


<tr>
<td>
<a href="javascript:void(0);" id="sponsertypesearch<?=$i;?>" onclick="grabvalues2('<?=$sponsertype->spons_type_title?>','<?=$sponsertype->id?>','<?=$parentname?>');"><?= $sponsertype->spons_type_title?></a>
</td>
</tr>
<?php
$i++;
}
}
else echo "<p>No matched search</p>";
?>
</tbody>
</table>