<style>
    .tree
    {min-width:2000px;

    }

    .scroldiv
    {

        width:768px; top: 0px; left: 0px; z-index: 2; -webkit-user-select: none; height: 533px; cursor: auto; overflow:scroll;
    }

    .col-sm-9 label {
        color: #777;
        font-size: 11px;
        font-weight: 400;
        line-height: 15px;
        font-weight:normal !important ;
        margin-bottom: 5px;
    }

</style>
<?php
     $breadcum="";
     if($postdata['Country_name']){
       $country=$this->MyHelper()->getCountryNameById($postdata['Country_name']);
       $breadcum.=$country->country_name;
     }
     if($postdata['State_name']){
       $state=$this->MyHelper()->getStateNameById($postdata['State_name']);
       $breadcum.=" / ".$state->state_name;
       
     }
     if($postdata['City_name']){
       $city=$this->MyHelper()->getCityNameById($postdata['City_name']);
       $breadcum.=" / ".$city->city_name;
  
     }
     if($postdata['Branch_name']){
       $branch=$this->MyHelper()->getBranchNameById($postdata['Branch_name']);
       $breadcum.=" / ".$branch[0]['branch_name'];
  
     }
    
     echo "<h2>".$breadcum."</h2>";
       
?>

<div class="scroldiv">    
    <div class="tree">
        <?php $root = $this->MyHelper()->getCommunityMemberByParentId(1); ?>
        <?php foreach ($root as $kahabe) {
            ?>
            <ul>
                <li>
                    <?php $pahalamukabla = $this->MyHelper()->getCommunityMemberById($kahabe['id']); ?>
                    <?php
                    foreach ($community as $com) {
                        //Zend\Debug\Debug::dump($com);
                        if ($com['comm_mem_id'] == $pahalamukabla[0]['id']) {
                            ?>
                            <label>
                                <div class="profile-pic">
                                    <?php
                                    $imagepath=$this->MyHelper()->getProfilePicByUsergId((int)$com['user_id']);
                                    if($imagepath){
                                        ?> <img src="<?php echo $this->basePath() ."/uploads/". $imagepath->image_path; ?>" style="width:71px;"/><?php
                                    }else{
                                     ?> <img src="<?php echo $this->basePath() . '/img/default_user.png'; ?>"/><?php   
                                    }
                                    
                                    ?>
                                </div>
                                <?php echo $com['full_name'] ?><br/>
                                <?php echo $pahalamukabla[0]['category_name'] ?><br/>
                                <span style="padding-bottom:5px;"> <?php echo $this->MyHelper()->getBranchNameById($com['branch_ids'])[0]['branch_name'] ?></span><br/>
                                <label>
                                    <a href="/membership/profile-view?member_id=<?php echo $com['user_id'] ?>" class="btn btn-default homemore">More info</a>
                                </label>
                            </label>
                        <?php }
                    } ?>
                    <ul>
                        <?php
                        foreach ($this->MyHelper()->getCommunityMemberChild($pahalamukabla[0]['id']) as $child1) {
                            //echo $child1['id'];
                            ?>
                            <?php
                            foreach ($community as $com) {
                                //echo $pahalamukabla[0]['id'];
                                //echo $com['branch_ids'];
                                //$memberRepeat= $com['comm_mem_id'];
                                if ($com['comm_mem_id'] == $child1['id']) {
                                    ?>
                                    <li> 
                                        <label>
                                            <div class="profile-pic">
                                                <?php
                                                $imagepath=$this->MyHelper()->getProfilePicByUsergId((int)$com['user_id']);
                                                if($imagepath){
                                                    ?> <img src="<?php echo $this->basePath() ."/uploads/". $imagepath->image_path; ?>" style="width:71px;"/><?php
                                                }else{
                                                 ?> <img src="<?php echo $this->basePath() . '/img/default_user.png'; ?>"/><?php   
                                                }
                                                ?>
      
                                            </div>
                                            <?php echo $com['full_name'] ?><br/>
                                            <?php echo $child1['category_name'] ?><br/>
                                            <span style="padding-bottom:5px;"> <?php echo $this->MyHelper()->getBranchNameById($com['branch_ids'])[0]['branch_name'] ?></span><br/>
                                            <label>
                                                <a href="/membership/profile-view?member_id=<?php echo $com['user_id'] ?>" class="btn btn-default homemore">More info</a>
                                            </label>
                                        </label>      
                                        <ul>
                                            <?php foreach ($this->MyHelper()->getCommunityMemberChild($child1['id']) as $child2) { ?>
                                                <?php
                                                foreach ($community as $com) {
                                                    //echo $pahalamukabla[0]['id'];
                                                    if ($com['comm_mem_id'] == $child2['id']) {
                                                        ?>
                                                        <li> 
                                                            <label>
                                                                <div class="profile-pic">
                                                                    <?php
                                                                    $imagepath=$this->MyHelper()->getProfilePicByUsergId((int)$com['user_id']);
                                                                    if($imagepath){
                                                                        ?> <img src="<?php echo $this->basePath() ."/uploads/". $imagepath->image_path; ?>" style="width:71px;"/><?php
                                                                    }else{
                                                                     ?> <img src="<?php echo $this->basePath() . '/img/default_user.png'; ?>"/><?php   
                                                                    }
                                                                    ?>
      
                                                                </div>
                                                                <?php echo $com['full_name'] ?><br/>
                                                                <?php echo $child2['category_name'] ?><br/>
                                                                <span style="padding-bottom:5px;"> <?php echo $this->MyHelper()->getBranchNameById($com['branch_ids'])[0]['branch_name'] ?></span><br/>
                                                                <label>
                                                                    <a href="/membership/profile-view?member_id=<?php echo $com['user_id'] ?>" class="btn btn-default homemore">More info</a>
                                                                </label>
                                                            </label>
                                                        </li>
                                            <?php }
                                        } ?>
                                    <?php } ?>
                                        </ul>
                                    </li>
            <?php }
        } ?>
    <?php } ?>
                    </ul>
                </li>
            </ul>
<?php } ?>
    </div>
</div>
<!--<div class="tree">
    <ul>
        <li>
            <a href="#">Parent</a>
            <ul>
                <li>
                    <a href="#">Child</a>
                    <ul>
                        <li>
                            <a href="#">Grand Child</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Child</a>
                    <ul>
                        <li><a href="#">Grand Child</a></li>
                        <li>
                            <a href="#">Grand Child</a>
                            <ul>
                                <li>
                                    <a href="#">Great Grand Child</a>
                                </li>
                                <li>
                                    <a href="#">Great Grand Child</a>
                                </li>
                                <li>
                                    <a href="#">Great Grand Child</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#">Grand Child</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>-->