                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                          <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                        <th>S.No.</th>
                        <th>User Type Name</th>
                        <!--<th class="hidden-480">Created Date</th>-->
                        <th class="hidden-480">Modified Date</th>   
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>                        
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody id="sortable">
                        <input type="hidden" id="table_name" value="tbl_user_type">
                            <input type="hidden" id="id_name" value="id">
                      <?php 
                      $i =1;
                      foreach ($usertypes as $usertype) {
                          //\Zend\Debug\Debug::dump($usertypes);exit;
                      
                      ?>
                      <tr id="<?php echo $usertype['id']; ?>" >
                         
                        <td><input type="checkbox" value="<?=$usertype['id']?>" class="checkme" name="checkme[]"> </td>
                        <td><?= $i?></td>                       
                        <td><?= $usertype['user_type']?></td>                       
                        <!--<td class="hidden-480"><?//= $usertype['created_date']?></td>-->
                        <td class="hidden-480"><?= $usertype['modified_date']?></td>
                        <td class="hidden-480"><?php echo ($usertype['modified_by']==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td class="hidden-480">
						<!--<?php echo ($usertype['is_active']==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        
                        <?php $status = ($usertype['is_active']==1)? 'Active': 'In-Active';
                        $statuscolor = ($usertype['is_active']==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$usertype['id']?>,<?= ($usertype['is_active']==0)?0:1; ?>,'<?= $this->serverUrl().$this->url().'/changeUserTypeStatus';?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        
                        <td><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" href="<?php 
                        echo $this->url('admin/master',array('action'=>'viewusertype','id'=>
                            $usertype['id'])); ?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a>
                                <a class="green" href="<?php echo $this->url('admin/master',array('action'=>'editusertype','id'=>$usertype['id'])); ?>" > 
                                    <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" 
                                       href="<?php echo $this->url('admin/master',array(
                                           'action'=>'deleteusertype','id'=>$usertype['id'])); ?>" onclick=
                                               "return confirm('are you sure you want to delete');"> 
                                        <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 
<?php 

if($this->action!='indexusertype'){
    ?>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.2.1.1.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.bootstrap.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.tableTools.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.colVis.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/table.js"></script> 
<?php
}
?>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery-1.10.2.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery-ui-1.10.4.custom.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/script.js"></script> 