<div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                          <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                        <th>S.No.</th>
                        <th>User Type Name</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Modified Date</th>                        
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i =1;
                      if (count($results) > 0) {
                      foreach ($results as $usertype) {
                          //\Zend\Debug\Debug::dump($usertypes);exit;
                      
                      ?>
                      <tr>
                         
                        <td><input type="checkbox" value="<?=$usertype->id?>" class="checkme" name="checkme[]"> </td>
                        <td><?= $i?></td>                       
                        <td><?= $usertype->user_type?></td>                       
                        <td class="hidden-480"><?= $usertype->created_date?></td>
                        <td class="hidden-480"><?= $usertype->modified_date?></td>
                        <td class="hidden-480">
						<!--<?php echo ($usertype->is_active==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        
                        <?php $status = ($usertype->is_active==1)? 'Active': 'In-Active';
                        $statuscolor = ($usertype->is_active==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$usertype->id?>,<?= ($usertype->is_active==0)?0:1; ?>,'<?= $this->serverUrl().$this->url().'/changeUserTypeStatus';?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        <td class="hidden-480"><?php echo ($usertype->modified_by==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" href="<?php 
                        echo $this->url('admin/master',array('action'=>'viewusertype','id'=>
                            $usertype->id)); ?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a>
                                <a class="green" href="<?php echo $this->url('admin/master',array('action'=>'editusertype','id'=>$usertype->id)); ?>" > 
                                    <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" 
                                       href="<?php echo $this->url('admin/master',array(
                                           'action'=>'deleteusertype','id'=>$usertype->id)); ?>" onclick=
                                               "return confirm('are you sure you want to delete');"> 
                                        <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                    
                      } else
        echo" <tr>
                         
                       <td colspan=9><center><h2>No data available</h2></center></td></tr>";
                      ?>                      
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>