                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                           <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.spons_type_id)" > </th>
                        <th>S. No.</th>
                        <th>Sponsertype Name</th>
                        <!--<th class="hidden-480">Created Date</th>-->
                        <th class="hidden-480">Modified Date</th> 
                        <!--<th class="hidden-480">Created By</th>-->
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
					  $i=1;
                        
                      foreach ($sponsertypes as $sponsertype) {
//                          \Zend\Debug\Debug::dump($sponsertype);exit;
                      
                      ?>
                      <tr>
                        <td><input type="checkbox" value="<?=$sponsertype->sponsTypeId?>" class="checkme" name="checkme[]"> </td> 
                       <td><?= $i ?></td>  
                        <td><?= $sponsertype->sponsTypeTitle?></td>            
                        <!--<td class="hidden-480"><?//=$sponsertype->createdDate?></td>-->
                        <td class="hidden-480"><?=$sponsertype->modifiedDate?></td>
                        <!--<td class="hidden-480"><?php //echo ($sponsertype->createdBy==1)? 'Admin': 'NotByAdmin'; ?></td>-->
                        <td class="hidden-480"><?php echo ($sponsertype->modifiedBy==1)? 'Admin': 'NotByAdmin'; ?></td>
                        
                        
                        <td class="hidden-480">
						<!--<?php echo ($sponsertype->isActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($sponsertype->isActive==1)? 'Active': 'In-Active';
                        $statuscolor = ($sponsertype->isActive==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatussponsertypequick(<?=$sponsertype->sponsTypeId?>,<?= ($sponsertype->isActive==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/sponsertype', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        
                        <td><div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('admin',array('controller'=>'sponsertype','action'=>'view','id'=>$sponsertype->spons_type_id)); ?>">
                         <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataBySponsertypeId('<?php echo $this->url
                                                           ('admin/sponsertype', array('action'=>'viewById','id'=>$sponsertype->sponsTypeId)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                         
                         <a class="green" href="javascript:void(0);" onclick="editboxsponsertype(<?= 
                                                   $sponsertype->sponsTypeId ?>, '<?php echo $this->url('admin/sponsertype', array('action' => 
                                                       'edit', 'id' => $sponsertype->sponsTypeId));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 
                          <a class="red" href="<?php echo $this->url('admin/sponsertype',array('action'=>'delete','id'=>
                              $sponsertype->sponsTypeId)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa 
                                                                                             fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      
                      
                      
                      <?php 
                      $i++;
                    }
                    
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                
<?php 

if($this->action!='index'){
    ?>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.2.1.1.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.bootstrap.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.tableTools.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.colVis.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/table.js"></script> 
<?php
}
?>
            
             