<div >
    <p>
        <a href="<?= $this->url('admin/events', array('action' => 'eventsindex')); ?>"><button class="btn btn-warning btn-xlg">Go Back</button></a>
    </p>
</div>

<div class="panel-body">

    <?php
    $form = $this->form;
    $form->prepare();


//        $form->setAttribute('action',$this->url('admin',array('controller'=>'events','action'=>'eventsadd')));
    $form->setAttribute('action', $this->url('admin/events', array('action' => 'eventsedit', 'id' => $id)));
    $form->setAttribute('id', 'EventsEditForm');
    $form->setAttribute('onsubmit', 'return SubmitEventsForm();');
    $form->setAttribute('method', 'post');
    $form->setAttribute('enctype', 'multipart/form-data');


    echo $this->form()->openTag($form);
// echo $this->formCollection($form);
    ?>
    <div class="alert_info">
        <h3>Event Details</h3>
    </div>
    <div class="tab-pane fade active in" id="driver_tab">
        <div class=" col-sm-col-sm-offset-1" >
            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_title')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formHidden($form->get('event_id'));
                        echo $this->formElement($form->get('event_title'));
                        ?>                                    
                    </div>

                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('is_active')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('is_active'));
                        ?>                                    
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('event_organiser')->getLabel())  ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        //echo $this->formElement($form->get('event_organiser'));
                        ?>                                    
                    </div>

                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('sponser_photo')->getLabel())  ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        //echo $this->formElement($form->get('sponser_photo'));
                        ?>                                    
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('organiser_photo')->getLabel())  ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        //echo $this->formElement($form->get('organiser_photo'));
                        ?>                                    
                    </div>

                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('organiser_contact')->getLabel())  ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        //echo $this->formElement($form->get('organiser_contact'));
                        ?>                                    
                    </div>




                </div>

            </div>

            <div class="row">
                <div class="form-group clearfix margintopbottom20">

                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('sponser_contact')->getLabel())  ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        //echo $this->formElement($form->get('sponser_contact'));
                        ?>                                    
                    </div>

                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('is_active')->getLabel())  ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        //echo $this->formElement($form->get('is_active'));
                        ?>                                    
                    </div>




                </div>

            </div>






        </div>
    </div>

    <div class="alert_info">
        <h3>Event Description</h3>
    </div>
    <div class="tab-pane fade active in" id="driver_tab">
        <div class=" col-sm-col-sm-offset-1" >

            <div class="row">
                <div class="col-xs-12">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_desc')->getLabel()) ?>
                    </label>
                    <div class="wysiwyg-editor" id="editor1"><?= $form->get('event_desc')->getValue(); ?></div>

                </div>
            </div>
            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('image')->getLabel())  ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('event_desc'));
                        //echo $this->formElement($form->get('image'));
                        ?>                                    
                    </div>




                </div>
            </div>
            <a href="#"  data-toggle="modal" data-target="#avatar-modalpost_image"  class="cropimage">Upload Photo</a>



    <!--<img id="post_photo" src="<?php //echo $this->basePath('img/default_user.png')      ?>" width="40" height="40"/>
    <input type="hidden" name="image" id="image" value="">-->

            <?php if (!empty($form->get('image')->getValue())) { ?>
                <img id="post_photo" src="<?php echo $this->basePath() . '/EventsImages/' . $form->get('image')->getValue(); ?>" width="40" height="40"/>
            <?php } else { ?>
                <img id="post_photo" src="<?php echo $this->basePath('img/default_user.png') ?>" width="40" height="40"/>
            <?php } ?>

            <?php
//echo $this->formElement($form->get('image'));
            ?>
            <input type="hidden" name="post_image_update" value="<?php
            if (!empty($form->get('image')->getValue())) {
                echo $form->get('image')->getValue();
            }
            ?>">
            <input type="hidden" name="image" id="image" value="<?php
            if (!empty($form->get('image')->getValue())) {
                echo $form->get('image')->getValue();
            }
            ?>">
            <input type="hidden" name="post_image_flag" id="post_image_flag" value="0">



        </div>
    </div>
    <div class="alert_info">
        <h3>Location Details</h3>
    </div>
    <div class="tab-pane fade active in" id="driver_tab">
        <div class=" col-sm-col-sm-offset-1" >
            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_country')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('event_country'));
                        ?>                                    
                    </div>


                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_city')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('event_city'));
                        ?>                                    
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_state')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('event_state'));
                        ?>                                    
                    </div>

                    <label for="rustagi_branch" id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_branch_id')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                                                //Zend\Debug\Debug::dump($events);
                        echo $this->formElement($form->get('event_branch_id'));
                        echo $this->formElement($form->get('event_branch_other'));
                        ?>                                    
                    </div>


                </div>
            </div>






        </div>
    </div>
    <div class="alert_info">
        <h3>Event Timing Details</h3>
    </div>
    <div class="tab-pane fade active in" id="driver_tab">
        <div class=" col-sm-col-sm-offset-1" >
            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php echo $this->translate($form->get('event_date')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <div class="input-group">
                            <?php
                            echo $this->formElement($form->get('event_date'));
                            ?><span class="input-group-addon">
                                <i class="fa fa-calendar bigger-110"></i>
                            </span>


                        </div> 


                    </div>

                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('end_date')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
//echo $this->formElement($form->get('end_date'));
                        ?>                                    
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_start_time')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('event_start_time'));
                        ?>                                    
                    </div>
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_end_time')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('event_end_time'));
                        ?>                                    
                    </div>


                </div>
            </div>


            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('event_venue')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        echo $this->formElement($form->get('event_venue'));
                        ?>                                    
                    </div>


                </div>
            </div>



        </div>
    </div>
   <div class="alert_info">
        <h3>Event Sponsor</h3>
    </div>
    <div class="tab-pane fade active in" id="driver_tab">
        <div class=" col-sm-col-sm-offset-1" >
            <div class="row">
                <BODY>

                    <INPUT type="button" value="Add Row" onclick="addRowSponser('dataTable')" />

                    <INPUT type="button" value="Delete Row" onclick="deleteRow('dataTable')" />
                    <!--<thead><td></td><td>Sponser master</td></thead>-->
                    <TABLE id="dataTable" width="250px" border="1">
                        <?php foreach ($sponser as $sponsers) { ?>
                            <input type="hidden" name="sponser_event_id[]" class="form-control" id="sponser_event_id[]" value="<?php echo $sponsers['event_sponser_ext_id'] ?>">
                            <TR id="sponser_row">

                                <TD><INPUT type="checkbox" name="chk[]" value="<?php echo $sponsers['event_sponser_ext_id'] ?>"/></TD>
                                <!--<TD><INPUT type="text" name="txt"/></TD>-->
                                <TD>
                                    <SELECT name="spons_id[]" >
                                        <OPTION value="">--Select Sponser--</OPTION>
                                        <?php foreach ($sponserMasterList as $key => $value) { ?>
                                            <OPTION value="<?php echo $key ?>" <?php if ($key == $sponsers['spons_id']) { ?>selected="selected" <?php } ?>><?php echo $value ?></OPTION>    
                                        <?php } ?>
                                    </SELECT>
                                </TD>
                                <TD>
                                    <SELECT name="spons_type_id[]" >
                                        <OPTION value="">--Select Sponser Type--</OPTION>
                                        <?php foreach ($sponserTypeList as $key => $value) { ?>
                                            <OPTION value="<?php echo $key ?>" <?php if ($key == $sponsers['spons_type_id']) { ?>selected="selected" <?php } ?>><?php echo $value ?></OPTION>    
                                        <?php } ?>                 
                                    </SELECT>
                                </TD>
                            </TR>
                        <?php } ?>
                    </TABLE>

                </BODY>
            </div>
        </div>
    </div>
    <br/><br/>
    <div class="alert_info">
        <h3>Event Organiser</h3>
    </div>
    <div class="tab-pane fade active in" id="driver_tab">
        <div class=" col-sm-col-sm-offset-1" >
            <div class="row">
                <BODY>

                    <INPUT type="button" value="Add Row" onclick="addRowOrganiser('dataTable2')" />

                    <INPUT type="button" value="Delete Row" onclick="deleteRow('dataTable2')" />
                    <!--<thead><td></td><td>Sponser master</td></thead>-->
                    <TABLE id="dataTable2" width="250px" border="1">
                        <?php foreach ($organiser as $organisers) { ?>
                            <input type="hidden" name="organiser_event_id[]" class="form-control" id="organiser_event_id[]" value="<?php echo $organisers['event_organiser_ext_id'] ?>">
                            <TR id="organiser_row">

                                <TD><INPUT type="checkbox" name="chk[]" value="<?php echo $organisers['event_organiser_ext_id'] ?>"/></TD>
                                <TD>
                                    <SELECT name="organiser_id[]" id="select_organiser_id" >
                                        <OPTION value="">--Select Organiser--</OPTION>
                                        <?php foreach ($organiserList as $key => $value) { ?>
                                            <OPTION value="<?php echo $key ?>" <?php if ($key == $organisers['organiser_id']) { ?>selected="selected" <?php } ?>><?php echo $value ?></OPTION>    
                                        <?php } ?>    

                                    </SELECT>
                                </TD>

                            </TR>
                        <?php } ?>
                        <?php
                        if (is_null($organiser)) {
                            ?>
                            <TR>

                                <TD></TD>
                                <TD>
                                    <SELECT name="new_organiser_id[]">
                                        <OPTION value="">--Select Organiser--</OPTION>
                                        <?php foreach ($organiserList as $key => $value) { ?>
                                            <OPTION value="<?php echo $key ?>" ><?php echo $value ?></OPTION>    
                                        <?php } ?>    

                                    </SELECT>
                                </TD>

                            </TR>
                            <?php
                        }
                        ?>
                    </TABLE>

                </BODY>

            </div>
        </div>
    </div
    <br/><br/>

    <?php
    echo $this->formElement($form->get('submit'));
    echo $this->form()->closeTag();
    ?>

</div>

<!--  Added by Amir -->
<div class="modal fade" id="avatar-modalpost_image" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="avatar-form" id="cropform_post" method="post" action="#" enctype="multipart/form-data" onsubmit="return croppostimage('<?= $this->serverurl() . $this->url() . "/croppostimage" ?>', croppostimageresults);">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title" id="avatar-modal-label">Post Picture</h4>
                </div>
                <div class="modal-body">
                    <div id="showloader_post" style="position:absolute;top:30%;left:0;width:100%;min-height:300px;display:none;z-index:1000;">
                        <center><img src="<?= $this->basepath() ?>/img/loadingmap2.gif"></center>
                    </div>


                    <h4>Image:</h4>
                    <input type="file" name="file" id="file_post"> 
                    <div class="banner"><img class="cropper2" id="showimage_post" src="<?= $this->basepath() ?>/img/default_user.png"></div>

                    <!--<input name="uid" id="uid" type="hidden">
                    <input name="ref_no" id="ref_no" type="hidden">
                    <input name="profile_photo_flag" id="profile_photo_flag" type="hidden">
                    <input name="profile_photo" id="profile_photo" type="hidden">

                    <input name="field_name" id="field_name1" type="hidden">

                    <input name="table_name" id="table_name1" type="hidden">-->

                    <input type="hidden" class="form-control" id="dataX11_post" placeholder="x1" name="x1">

                    <input type="hidden" class="form-control" id="dataY11_post" placeholder="y1" name="y1">

                    <input type="hidden" class="form-control" id="dataX21_post" placeholder="x2" name="x2">

                    <input type="hidden" class="form-control" id="dataY21_post" placeholder="y2" name="y2">

                    <input type="hidden" class="form-control" id="dataWidth1_post" placeholder="width" name="width">

                    <input type="hidden" class="form-control" id="dataHeight1_post" placeholder="height" name="height">

                    <input type="hidden" class="form-control" id="cropenabled2" name="cropenabled" value="Enable">
                    <!--<div id="forprofile">
                        <h5 style="font-weight:bold;color:cornflowerblue;">OR</h5>
                        <a href="#" id="profileFrom_gallery" data-toggle="modal" data-target="#chooseGallery" style="font-weight:bold;font-size:14px;color:chocolate;">Choose from Gallery</a>
                    </div>-->
                    <input type="hidden" id="actualimage_post" name="actualimage">
                    <button id="cropper-enable_post" type="button" class="btn btn-success croptrigger2">Enable</button>
                    <button id="cropper-disable_post" type="button" class="btn btn-danger croptrigger2">Disable</button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                    <input class="btn btn-primary avatar-save" type="submit" value="Save">
                </div>
            </form>
        </div>



    </div>
</div>
<div>
    <TABLE id="dataTable_hidden" width="250px" border="1" style="display: none">

        <TR>

            <TD></TD>
            <TD>
                <SELECT name="new_spons_id[]" >
                    <OPTION value="">--Select Sponser--</OPTION>
                    <?php foreach ($sponserMasterList as $key => $value) { ?>
                        <OPTION value="<?php echo $key ?>" ><?php echo $value ?></OPTION>    
                    <?php } ?>
                </SELECT>
            </TD>
            <TD>
                <SELECT name="new_spons_type_id[]" >
                    <OPTION value="">--Select Sponser Type--</OPTION>
                    <?php foreach ($sponserTypeList as $key => $value) { ?>
                        <OPTION value="<?php echo $key ?>"><?php echo $value ?></OPTION>    
                    <?php } ?>                 
                </SELECT>
            </TD>
        </TR>

    </TABLE>
    <TABLE id="dataTable2_hidden" width="250px" border="1" style="display: none">

        <TR>

            <TD></TD>
            <TD>
                <SELECT name="new_organiser_id[]">
                    <OPTION value="">--Select Organiser--</OPTION>
                    <?php foreach ($organiserList as $key => $value) { ?>
                        <OPTION value="<?php echo $key ?>" ><?php echo $value ?></OPTION>    
                    <?php } ?>    

                </SELECT>
            </TD>

        </TR>

    </TABLE>

</div>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>

<script>

                $(document).ready(function () {
                    $("#rustagi_branch_other").hide();
                    $("#event_branch_id").append("<option value='-1'>Others</option>");
                    <?php if($events->getEventBranchId()=='-1'){?>
                            $('#event_branch_id option[value="-1"]').attr("selected","selected");
                            $("#event_branch_other").show();
                            //alert('satya');
                    <?php }else{ ?>
                            $("#event_branch_other").hide();
                    <?php } ?>
                       
                    $("#event_date").datepicker({format: "dd-mm-yyyy"});

                    //$("#profession_other").hide();
                    //$("#gothra_gothram_other").hide();
                })
                /**************Get State on select Country***************/
                $("#event_country").on('change', function () {
                    var countryId = this.value;
                    //alert(data);
                    $.ajax({
                        url: '/admincontrol/' + 'events/getStateName',
                        //url:'events/getStateName',
                        type: "POST",
                        dataType: "json",
                        data: {Country_ID: countryId},
                        beforeSend: function () {
                            $('#Loading_Request').show();
                        },
                        complete: function () {
                            $('#Loading_Request').hide();
                        },
                        success: function (resp) {
                            if (resp.Status == 'Success') {
                                $("#event_state").empty();
                                $("#event_city").empty();
                                $("#event_state").append("<option value=''>Select State</option>");
                                $.each(resp.statelist, function (idx, obj) {
                                    $("#event_state").append("<option value='" + obj["id"] + "'>" + obj["state_name"] + "</option>");
                                });
                            } else {
                                $("#event_state").empty();
                                $("#event_city").empty();
                                alert("No States are available");
                            }
                        },
                        error: function (error) {
                            console.log(error);
                            alert(error);
                        }
                    });
                });
                /*******************End******************/
                /*************Get City on Select State*************************************************/
                $("#event_state").on('change', function () {
                    var stateId = this.value;
                    $.ajax({
                        url: '/admincontrol/' + 'events/getCityName',
                        type: "POST",
                        dataType: "json",
                        data: {State_ID: stateId},
                        beforeSend: function () {
                            $('#Loading_Request').show();
                        },
                        complete: function () {
                            $('#Loading_Request').hide();
                        },
                        success: function (resp) {
                            if (resp.Status == 'Success') {
                                $("#event_city").empty();
                                $("#event_branch_id").empty();
                                $("#event_city").append("<option value=''>Select City</option>");
                                $.each(resp.statelist, function (idx, obj) {
                                    $("#event_city").append("<option value='" + obj["id"] + "'>" + obj["city_name"] + "</option>");
                                });
                            } else {
                                $("#event_city").empty();
                                alert("No Cities are Available");
                            }
                        },
                        error: function (error) {
                            console.log(error);
                            alert(error);
                        }
                    });
                });
                /*******************End******************/
                /*************Get Branch on Select City*************************************************/
                $("#event_city").on('change', function () {
                    var cityId = this.value;
                    $.ajax({
                        url: '/admincontrol/' + 'events/getRustagiBranch',
                        type: "POST",
                        dataType: "json",
                        data: {City_ID: cityId},
                        beforeSend: function () {
                            $('#Loading_Request').show();
                        },
                        complete: function () {
                            $('#Loading_Request').hide();
                        },
                        success: function (resp) {
                            //$("#event_branch_other").hide();

                            if (resp.Status == 'Success') {
                                $("#event_branch_id").empty();
                                $("#event_branch_id").append("<option value=''>Select Branch</option>");
                                $.each(resp.statelist, function (idx, obj) {
                                    $("#event_branch_id").append("<option value='" + obj["branch_id"] + "'>" + obj["branch_name"] + "</option>");
                                });
                            } else {
                                $("#event_branch_id").empty();
                                alert("No Branches are Available");
                                $("#event_branch_other").show();
                            }
                            $("#event_branch_id").append("<option value='-1'>Others</option>");
                        },
                        error: function (error) {
                            console.log(error);
                            alert(error);
                        }
                    });
                });
                /*******************End******************/
                
                 $("#event_branch_id").on('change', function () {

                    if(this.value==='-1'){
                       $("#event_branch_other").show(); 
                    }else{
                        $("#event_branch_other").hide(); 
                    }
                });
</script>

<SCRIPT language="javascript">
    function addRowOrganiser(tableID) {

        var table = document.getElementById(tableID);
        var tableNew = document.getElementById('dataTable2_hidden');

        var rowCount = table.rows.length;
        var row = table.insertRow(rowCount);

        var colCount = table.rows[0].cells.length;

        for (var i = 0; i < colCount; i++) {

            var newcell = row.insertCell(i);

            newcell.innerHTML = tableNew.rows[0].cells[i].innerHTML;
            //alert(newcell.innerHTML.getElementById('select_organiser_id'));
//            switch (newcell.childNodes[0].type) {
//                // case "text":
//                //         newcell.childNodes[0].value = "";
//                //         break;
//                case "checkbox":
//                    newcell.childNodes[0].checked = false;
//                    break;
//                case "select-one":
//                    newcell.childNodes[0].selectedIndex = 0;
//                    break;
//            }
        }
    }

    function addRowSponser(tableID) {

        var table = document.getElementById(tableID);
        var tableNew = document.getElementById('dataTable_hidden');

        var rowCount = table.rows.length;
        var row = table.insertRow(rowCount);

        var colCount = table.rows[0].cells.length;

        for (var i = 0; i < colCount; i++) {

            var newcell = row.insertCell(i);

            newcell.innerHTML = tableNew.rows[0].cells[i].innerHTML;
            //console.log(newcell);
            //alert(newcell.innerHTML.getElementById('select_organiser_id'));
//            switch (newcell.childNodes[0].type) {
//                // case "text":
//                //         newcell.childNodes[0].value = "";
//                //         break;
//                case "checkbox":
//                    newcell.childNodes[0].checked = false;
//                    break;
//                case "select-one":
//                    newcell.childNodes[0].selectedIndex = 0;
//                    break;
//            }
        }
    }

    function deleteRow(tableID) {
        if (tableID == 'dataTable') {
            try {

                var rowCountChecked = '0';
                var table = document.getElementById(tableID);
                //var rowCount = table.rows.length;
                //var table = document.getElementById('sponser_row');
                //var rowCount = table.rows.namedItem('sponser_row').length;
                //var row = table.rows['0'];
                rowCount = $("tr[id='sponser_row']").length;
                //console.log(rowCount);
                for (var i = 0; i < rowCount; i++) {
                    var row = table.rows[i];
                    var chkbox = row.cells[0].childNodes[0];
                    if (null != chkbox && true == chkbox.checked) {
                        rowCountChecked++;
                    }
                }
                if (rowCount == rowCountChecked) {
                    //console.log('satya');
                    alert("Cannot delete all the rows.");
                    return false;
                }
                //console.log(rowCountChecked);

                for (var i = 0; i < rowCount; i++) {

                    var row = table.rows[i];
                    var chkbox = row.cells[0].childNodes[0];
                    //console.log(chkbox.checked.length);
                    if (null != chkbox && true == chkbox.checked) {
                        if (rowCount <= 1) {

                            alert("Cannot delete all the rows.");
                            break;

                        }
                        deleteRowSponser(chkbox.value);
                        console.log(chkbox.value);
                        table.deleteRow(i);
                        rowCount--;
                        i--;
                    }

                }
            } catch (e) {
                alert(e);
            }
        }
        if (tableID == 'dataTable2') {

            try {

                var rowCountChecked = '0';
                var table = document.getElementById(tableID);
                //var rowCount = table.rows.length;
                rowCount = $("tr[id='organiser_row']").length;
                console.log(rowCount);
                for (var i = 0; i < rowCount; i++) {
                    var row = table.rows[i];
                    var chkbox = row.cells[0].childNodes[0];
                    if (null != chkbox && true == chkbox.checked) {
                        rowCountChecked++;
                    }
                }
                if (rowCount == rowCountChecked) {
                    //console.log('satya');
                    alert("Cannot delete all the rows.");
                    return false;
                }
                //console.log(rowCountChecked);

                for (var i = 0; i < rowCount; i++) {

                    var row = table.rows[i];
                    var chkbox = row.cells[0].childNodes[0];
                    //console.log(chkbox.checked.length);
                    if (null != chkbox && true == chkbox.checked) {
                        if (rowCount <= 1) {

                            alert("Cannot delete all the rows.");
                            break;

                        }
                        deleteRowOrganiser(chkbox.value);
                        console.log(chkbox.value);
                        table.deleteRow(i);
                        rowCount--;
                        i--;
                    }

                }
            } catch (e) {
                alert(e);
            }
        }
    }

    function deleteRowSponser(sponserId) {
        $.ajax({
            url: '/admincontrol/' + 'events/deleteSponser',
            type: "POST",
            dataType: "json",
            data: {sponser_id: sponserId},
            beforeSend: function () {
                $('#Loading_Request').show();
            },
            complete: function () {
                $('#Loading_Request').hide();
            },
            success: function (resp) {
                console.log(resp);
                if (resp.Status == 'Success') {
//                    $("#event_branch_id").empty();
//                    $("#event_branch_id").append("<option value=''>Select Branch</option>");
//                    $.each(resp.statelist, function (idx, obj) {
//                        $("#event_branch_id").append("<option value='" + obj["branch_id"] + "'>" + obj["branch_name"] + "</option>");
//                    });
                } else {

                }

            },
            error: function (error) {
                console.log(error);

            }
        });
    }

    function deleteRowOrganiser(organiserId) {
        $.ajax({
            url: '/admincontrol/' + 'events/deleteOrganiser',
            type: "POST",
            dataType: "json",
            data: {organiser_id: organiserId},
            beforeSend: function () {
                $('#Loading_Request').show();
            },
            complete: function () {
                $('#Loading_Request').hide();
            },
            success: function (resp) {
                console.log(resp);
                if (resp.Status == 'Success') {
//                    $("#event_branch_id").empty();
//                    $("#event_branch_id").append("<option value=''>Select Branch</option>");
//                    $.each(resp.statelist, function (idx, obj) {
//                        $("#event_branch_id").append("<option value='" + obj["branch_id"] + "'>" + obj["branch_name"] + "</option>");
//                    });
                } else {

                }

            },
            error: function (error) {
                console.log(error);

            }
        });
    }
</SCRIPT>