
                   <?php 

                $form=$this->form; 
                $form->prepare();


        //$form->setAttribute('action',$this->url('admin',array('controller'=>'State','action'=>'edit')));
        $form->setAttribute('action', $this->url('admin/state', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('method','post');
        $form->setAttribute('name', 'editform');
        $form->setAttribute('autocomplete','off');
        //$form->setAttribute('id','StateForm');
        $form->setAttribute('id','StateFormEdit');
       // $action = $this->serverUrl().$this->url('admin',array('controller'=>'state','action'=>'edit','id'=>$id));
        $action = $this->url('admin/state', array('action' => 'edit', 'id' => $id));
        //$form->setAttribute('onSubmit',"return SubmitFormAction($(this).attr('id'),'".$action."',addformResp)");
        $form->setAttribute('onSubmit', "return SubmitFormAction($(this).attr('id'),'" . $action . "',addformResp)");

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
            
            
            
            <div class="tab-pane fade active in" id="driver_tab">
    <div class="" style="">

        <div class="" style="">
            <div class="form-group clearfix margintopbottom20">
                
                <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                    <?= $this->translate($form->get('country_id')->getLabel()) ?>
                </label>
                <div class="col-sm-2">
                <?php
                    echo $this->formHidden($form->get('id'));
                    //echo $this->formElement($form->get('country_name'));
                    echo $this->formElement($form->get('country_id'));
                    ?> 
                    <span class="showerror"></span>                                      
                </div>
                <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('state_name')->getLabel()) ?>
                           </label>
                <div class="col-sm-2" id="editparent">
                    <?php
                    //echo $this->formHidden($form->get('id'));
                    echo $this->formElement($form->get('state_name'));
                    //echo $this->formElement($form->get('country_id'));
                    ?> 
                    <input id="state_name"  class="form-control inputchange" placeholder="State Name" type="text" 
                                                     onkeyup="keyupresults33($(this).val(),$('#StateFormEdit :input[name=country_id]').val()
                                                                        ,searchboxresults,'<?php echo $this->url("admin/state",
                                                             array('action'=>'searchboxresults'))?>',StateFormEdit)" value="" name="state_name"  >
                    <span class="showerror"></span>   
                    <div class="col-sm-3 searchboxresults" id="searchresults" style="position: absolute;
                         overflow-y:scroll;
                         background:#FFF;
                         width:93%;
                         height:auto;
                         z-index: 9999;display:none;">
                    </div>                                
                </div>
                
                <!--<label id="flight_nos" class="col-sm-2 control-label labelalign ">
                    <?php //echo $this->translate($form->get('state_name')->getLabel()) ?>
                </label>
                <div class="col-sm-1">
                    <?php
                    //echo $this->formElement($form->get('state_name'));
                    ?>  
                    <span class="showerror"></span>                                   

                </div>-->

                <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                    <?= $this->translate($form->get('state_code')->getLabel()) ?>
                </label>
                <div class="col-sm-1">
                    <?php
                    echo $this->formElement($form->get('state_code'));
                    echo $this->formHidden($form->get('master_state_id'));
                    ?>  
                    <span class="showerror"></span>                                   

                </div>

                <label id="flight_nos" class="col-sm-1 control-label labelalign ">
<?php //echo $this->translate($form->get('dial_code')->getLabel()) ?>
                </label>
                <div class="col-sm-1">
<?php
//echo $this->formHidden($form->get('master_state_id'));
//echo $this->formElement($form->get('dial_code'));
?>  
                    <span class="showerror"></span>                                   

                </div>
                <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                        <?php //echo $this->translate($form->get('currency')->getLabel()) ?>
                                    </label>

                                    <div class="col-sm-1">
                                        <?php
                                        //echo $this->formElement($form->get('currency'));
                                        ?>  
                                        <!--<span class="showerror"></span> -->                                  

                                    </div>
                
                
                 <div class="row">
            <div class="form-group clearfix margintopbottom20">


                <!-- <label id="flight_nos" class="col-sm-2 control-label labelalign ">
<?//= $this->translate($form->get('is_active')->getLabel()) ?>
                </label>
                                       <div class="col-sm-3">
<?php
//echo $this->formElement($form->get('is_active'));
?> 
                                          <span class="showerror"></span>                                   
                                                                             
                                       </div>-->
            </div>
        </div>
                <div class="col-sm-1 pull-left">
<?php
echo $this->formRow($form->get('submit'));
?>                                    
                </div>
                <div class="col-sm-1 pull-left">
                    <a class="btn btn-red defaultbtnsearch searchBooking" href="javascript:void(0);" onclick="location.reload();">Cancel</a>                              
                </div>


            </div>
        </div>
       

    </div>
</div>
          
        <?php   
echo $this->form()->closeTag();

        ?>                                   
                                                  