  
                      <?php 

                $form=$this->form; 
                $form->prepare();


//        $form->setAttribute('action',$this->url('admin',array('controller'=>'institute','action'=>'edit','id'=>$id)));
//        $form->setAttribute('method','post');

                $form->setAttribute('action', $this->url('admin/institute', array('action' => 'edit', 'id' => $id)));
                $form->setAttribute('method', 'post');
                $form->setAttribute('name', 'editform');
                $form->setAttribute('autocomplete', 'off');
                $form->setAttribute('id', 'InstituteFormEdit');
                $action = $this->url('admin/institute', array('action' => 'edit', 'id' => $id));
                $form->setAttribute('onSubmit', "return SubmitFormAction($(this).attr('id'),'" . $action . "',addformResp)");

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
                     
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                                                
                                <label id="flight_nos" class="col-sm-1 control-label labelalign "><?php echo $this->translate('Country') ?></label>
                                            <div class="col-sm-1  " style="padding:0;">
                                                <?php
                                                echo $this->formRow($form->get('country'));
                                                ?>                                                    
                                                                                    
                                            </div>  
                                            
                                             <label id="flight_nos" class="col-sm-1 control-label labelalign "><?php echo $this->translate('State'); ?></label>
                                            <div class="col-sm-1" style="padding:0;">
                                                <?php echo $this->formRow($form->get('state')); ?>
                                               
                                            </div>                                           

					<label id="flight_nos" class="col-sm-1 control-label labelalign "><?php echo $this->translate('City'); ?></label>
                                            <div class="col-sm-1 " style="padding:0;">
                                                <?php echo $this->formRow($form->get('city')); ?>
                                                                                   
                                            </div> 
                                            
                                             <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('institute_name')->getLabel()) ?>
                            
                           </label>
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('institute_name'));
                                                     ?>                                    
                                                  </div>  
                                
                                                                                 
                                                  </div>
                                                  
                                                   
                                                  
                                                  <div class="form-group clearfix margintopbottom20">
                        <label id="flight_nos" class="col-sm-1 control-label labelalign ">  <?= $this->translate($form->get('institute_type')->getLabel()) ?>
                           
                           </label>
                                                  <div class="col-sm-2">
                                                    <?php 
                                                     echo $this->formElement($form->get('institute_type'));
                                                     ?>                                                                                 
                                                  </div>
                                                  
                                                   <label id="flight_nos" class="col-sm-1 control-label labelalign "> <?= $this->translate($form->get('institute_address')->getLabel()) ?></label>
                                                  <div class="col-sm-2">
                                                    <?php 
                                                     echo $this->formElement($form->get('institute_address'));
                                                     ?>                                                                                 
                                                  </div>
                                                  
                                                  
                                                  
                                                  
                                                    <label id="flight_nos" class="col-sm-1 control-label labelalign "> <?= $this->translate($form->get('purpose')->getLabel()) ?></label>
                           
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formElement($form->get('purpose'));
                                                     ?>                                    
                                                  </div> 
                                                  <label id="flight_nos" class="col-sm-1 control-label labelalign "><?= $this->translate($form->get('operated_by')->getLabel()) ?></label>
                                                  <div class="col-sm-2" style="height:45px;">
                                                     <?php 
                                                     echo $this->formElement($form->get('operated_by'));
                                                     ?>                                                                                     
                                                  </div>
                                                  
                                                  <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                           <!-- <?= $this->translate($form->get('is_active')->getLabel()) ?>-->
                           Members
                           </label>
                                                  <div class="col-sm-2">
                                                    <!-- <?php 
                                                     echo $this->formElement($form->get('is_active'));
                                                     ?>  -->  
                                                     <input type="text" class="form-control"    />  <a href="#">Add Another Member</a>                          
                                                  </div>
                                                 
                                                  
                                                  <label id="flight_nos" class="col-sm-1 control-label labelalign "><?= $this->translate($form->get('is_active')->getLabel()) ?></label>
                           
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formElement($form->get('is_active'));
                                                     ?>                                    
                                                  </div>
                                                  
                                                  
                                                  
                                                   <div class="col-sm-1">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                         
                                                 </div>
                                             </div>
                                            
              </div>
            </div>
          
        <?php   
echo $this->form()->closeTag();

        ?>  
     
  
