<style>
    .modal-dialog {
        width: 67%;
    }

    .activestatus{
        color:green;
        background:green;
        border-radius:30px; width:15px; height:15px;
        cursor:pointer

    }

    .de-activestatus{
        color:green;
        background:red;
        border-radius:30px; width:15px; height:15px;
        cursor:pointer;


    }

</style>

<style type="text/css">
input[type="text"]{height:20px; vertical-align:top;}
.field_wrapper div{ margin-bottom:10px;}
.add_button{ margin-top:10px; margin-left:10px;vertical-align: text-bottom;}
.remove_button{ margin-top:10px; margin-left:10px;vertical-align: text-bottom;}
</style>


<?php 

// foreach ($institutes as $institute) {

// echo  $institute->institute_name."<br>";

// }

// echo "<pre>";
// print_r($institutes);
// die;

?>
<div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
            <!--<div class="alert alert-block alert-success">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i>Add Institute Master</strong>, </div>-->
            <!--<div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
            </div>-->
            <div class="row">
              <div class="col-xs-12">
                <h3  >Add Institute Master</h3>
                <div class="filter">
                 <div class="panel-body" style="padding:0 !important">
                  <div class="col-lg-6">View Records>></div>
                  </div>
                </div>
                <div class="portlet-body">
                    
                    <div id="myTabContent" class="tab-content">
                            <div class="tab-pane fade active in" id="home">
                                <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                                    <div class="row">
                                        <div class="form-group clearfix margintopbottom20">
                                            <label id="flight_nos" class="col-sm-1 col-sm-1updated control-label labelalign ">Select Country</label>
                                            <div class="col-sm-2 ">
                                                <select class="form-control" id="filter_country2" ftype="country">
                <option value="">Select country</option>
                <?php
                
//               \Zend\Debug\Debug::dump($filters_data);
//                    exit;
                foreach ($filters_data as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->countryName . "</option>";
                }
                ?>
            </select>
                                                
                                                <div class="col-sm-3" id="countrysearchresults" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;">
                                                </div>                                    
                                            </div>

                                            <label id="point_airport" class="col-sm-1 col-sm-1updated control-label labelalign ">Select State
                                            </label>
                                            <div class="col-sm-2">
                                                <select class="form-control" id="filter_state" ftype="state">
                                                </select>
                                            </div>

                                            <label id="flight_nos" class="col-sm-1 col-sm-1updated control-label labelalign ">Select City</label>
                                            <div class="col-sm-2 ">
                                                <select class="form-control" id="filter_city" ftype="city">
                                                </select>
                                            </div>  
                                            
                                            <label id="flight_nos" class="col-sm-1 col-sm-1updated control-label labelalign ">Select Institute</label>
                                            <div class="col-sm-2 ">
                                                <select class="form-control" id="filter_institute" ftype="institute">
                                                </select>
                                            </div> 

                                            <div class="col-sm-1  ">
                                                 <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search"   onclick="filterData2();">
                                            </div>
                                            <div class="col-sm-6 ">
                                               <a id="showaddform" class="btn btn-red defaultbtnsearch searchBooking" href="#"> Add</a>
                                               <!--<a class="btn btn-red defaultbtnsearch showaddForm" href="javascript:void(0);"> Add</a>-->
                                                
                                            </div>


                                        </div>
                                    </div>
                                    
                                </div>



                            </div>
                        </div>
                    
   
                </div>
                
                 
                  <div class="filter">
                   <div class="panel-body " style="padding:0 !important;">
                  <div class="col-lg-6" style="cursor:pointer;">Add Update Records>>
                  </div>
  
                  </div>
   
                </div>
                
                
                
          <div id="addForm" class="tab-content dontshow">
                    <?php 

                $form=$this->form; 
                $form->prepare();


//        $form->setAttribute('action',$this->url('admin',array('controller'=>'institute','action'=>'add')));
//        $form->setAttribute('method','post');
        
        $form->setAttribute('action', $this->url('admin/institute', array('action' => 'add')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('autocomplete', 'off');
        $form->setAttribute('id', 'InstituteForm');
        $action = $this->url('admin/institute', array('action' => 'add'));
        $form->setAttribute('onSubmit', "return SubmitFormAction($(this).attr('id'),'" . $action . "',addformResp)");

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
          
            
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                                                
                                <label id="flight_nos" class="col-sm-1 control-label labelalign "><?php echo $this->translate('Country') ?></label>
                                            <div class="col-sm-1  " style="padding:0;">
                                                <?php
                                                echo $this->formRow($form->get('country'));
                                                ?>                                                    
                                                                                    
                                            </div>  
                                            
                                             <label id="flight_nos" class="col-sm-1 control-label labelalign "><?php echo $this->translate('State'); ?></label>
                                            <div class="col-sm-1" style="padding:0;">
                                                <?php echo $this->formRow($form->get('state')); ?>
                                               
                                            </div>                                           

					<label id="flight_nos" class="col-sm-1 control-label labelalign "><?php echo $this->translate('City'); ?></label>
                                            <div class="col-sm-1 " style="padding:0;">
                                                <?php echo $this->formRow($form->get('city')); ?>
                                                                                   
                                            </div> 
                                            
                                             <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('institute_name')->getLabel()) ?>
                            
                           </label>
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('institute_name'));
                                                     ?>                                    
                                                  </div>  
                                
                                                                                 
                                                  </div>
                                                  
                                                   
                                                  
                                                  <div class="form-group clearfix margintopbottom20">
                        <label id="flight_nos" class="col-sm-1 control-label labelalign ">  <?= $this->translate($form->get('institute_type')->getLabel()) ?>
                           
                           </label>
                                                  <div class="col-sm-2">
                                                    <?php 
                                                     echo $this->formElement($form->get('institute_type'));
                                                     ?>                                                                                 
                                                  </div>
                                                  
                                                   <label id="flight_nos" class="col-sm-1 control-label labelalign "> <?= $this->translate($form->get('institute_address')->getLabel()) ?></label>
                                                  <div class="col-sm-2">
                                                    <?php 
                                                     echo $this->formElement($form->get('institute_address'));
                                                     ?>                                                                                 
                                                  </div>
                                                  
                                                  
                                                  
                                                  
                                                    <label id="flight_nos" class="col-sm-1 control-label labelalign "> <?= $this->translate($form->get('purpose')->getLabel()) ?></label>
                           
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formElement($form->get('purpose'));
                                                     ?>                                    
                                                  </div> 
                                                  <label id="flight_nos" class="col-sm-1 control-label labelalign "><?= $this->translate($form->get('operated_by')->getLabel()) ?></label>
                                                  <div class="col-sm-2" style="height:45px;">
                                                     <?php 
                                                     echo $this->formElement($form->get('operated_by'));
                                                     ?>                                                                                     
                                                  </div>
                                                  
                                                  <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate('Members') ?>                           
                           </label>             <!-- start auto -->  
                                                <div class="field_wrapper">
                                                <div>
                                                <!--<input type="text" name="field_name[]" value=""/>-->
                                                
                                                <input id="" class=" form-control inputchange search_instituteName" placeholder="Institute Name" type="text" style="width: 180px;"
                                                       onkeyup="institutesearchactions($(this).val(), '<?php echo $this->url('admin/institute', array('action'=>'institutesearch'))?>', institutesearchresp, 'instituteName')" name="institute_name[]">
                                                <div class="col-sm-3 institutesearchresults" id="" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;">
                                                </div> 
                                                <a href="javascript:void(0);" class="add_button" title="Add field">add</a>
                                                </div>
                                               </div>
                                                 
                                           <!-- end auto -->       
                                                  
                                                  <label id="flight_nos" class="col-sm-1 control-label labelalign "><?= $this->translate($form->get('is_active')->getLabel()) ?></label>
                           
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formElement($form->get('is_active'));
                                                     ?>                                    
                                                  </div>
                                                  
                                                  
                                                  
                                                   <div class="col-sm-1">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                         
                                                 </div>
                                             </div>
                                             
                                             
              </div>
            </div>
         
        <?php   
echo $this->form()->closeTag();

        ?>
                                                  </div>
                <div id="editForm" class="tab-content dontshow">
                </div>
                                            
                
                    <div class="clearfix"></div>
                  
                <div class="col-lg-12" style="background-color:#FFF;" id="radiosearch" fld="tbl_rustagi_institutions">
                  
                  <div class="col-lg-1"><div class="radio">
                                                <label>
                                                    <input type="radio" value="1" id="optionsRadios1" name="optionsRadios" 
                                       onchange="RadioSearch($(this).val(), 'tbl_rustagi_institutions', '<?php echo 
                                       $this->url('admin/institute', array('action'=>'ajaxradiosearch'))?>',
                                                   radioSearchResult2)" ><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-1"><div class="radio">
                                                <label>
                                                    <input type="radio" value="0" id="optionsRadios1" name="optionsRadios" onchange=
                                    "RadioSearch($(this).val(), 'tbl_rustagi_institutions', '<?php echo $this->url
                                            ('admin/institute', array('action'=>'ajaxradiosearch'))?>', 
                                                        radioSearchResult2)"><strong>In-Active</strong>
                                                </label>
                                                
                                              
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="delselected('<?php echo $this->url('admin/institute', array('action'=>
                                    'delmultiple'))?>',delmultipleresp)">Delete Selected</button>                                              
                    </div>
                  </div> 
                  <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?php echo $this->url('admin/institute', array
                                    ('action'=>'changeStatusAll'))?>',statuschangeallresp,1)">Activate Selected</button>                                    
                    </div>
                  </div> 
                    <div class="col-lg-2 pull-right">
                        <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?php echo $this->url('admin/institute', array
                                    ('action'=>'changeStatusAll'))?>',statuschangeallresp,0)">De-Activate Selected</button>                                    
                        </div>
                    </div>
                 
                  
                  
                  </div>
                  
                  <div class="col-sm-12">


                </div>
                  
                <div class="col-md-12"  id="institute_data_list">
                    <?php echo $this->partial('admin/institute/instituteList.phtml'); ?>
                 </div>
                    <div class="col-md-12" id="institute_search_list">
                        
                        
                        
                    </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
                
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 
          
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a>
</div></div>
<div id="viewInstituteModel"></div>
<?php //echo $this->inlineScript()->prependFile($this->basePath('/assets/js/institute.js')); ?>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<?php echo $this->inlineScript()->prependFile($this->basePath('/assets/js/institute.js')); ?>
<?php echo $this->inlineScript()->prependFile($this->basePath('/assets/js/institute-auto-jquery.js')); ?>

<script>

            
            /**************Get State on select Country***************/
            $("#country").on('change', function () {
    var countryId = this.value;
    //alert(countryId);
            $.ajax({
            url: '<?php echo $this->basePath() ?>' + '/account/getStateName',
                    type: "POST",
                    dataType: "json",
                    data: {Country_ID: countryId},
                    beforeSend: function () {
                    $('#Loading_Request').show();
                    },
                    complete: function () {
                    $('#Loading_Request').hide();
                    },
                    success: function (resp) {
                    if (resp.Status == 'Success') {
                    $("#state").empty();
                            $("#city").empty();
                            $("#state").append("<option value=''>Select State</option>");
                            $.each(resp.statelist, function (idx, obj) {
                            $("#state").append("<option value='" + obj["id"] + "'>" + obj["state_name"] + "</option>");
                            });
                    } else {
                    $("#state").empty();
                            $("#city").empty();
                            alert("No States are available");
                    }
                    },
                    error: function (error) {
                    console.log(error);
                            alert(error);
                    }
            });
    });
            /*******************End******************/
            /*************Get City on Select State*************************************************/
            $("#state").on('change', function () {
    var stateId = this.value;
            $.ajax({
            url: '<?php echo $this->basePath() ?>' + '/account/getCityName',
                    type: "POST",
                    dataType: "json",
                    data: {State_ID: stateId},
                    beforeSend: function () {
                    $('#Loading_Request').show();
                    },
                    complete: function () {
                    $('#Loading_Request').hide();
                    },
                    success: function (resp) {
                    if (resp.Status == 'Success') {
                    $("#city").empty();
                            $("#city").append("<option value=''>Select City</option>");
                            $.each(resp.statelist, function (idx, obj) {
                            $("#city").append("<option value='" + obj["id"] + "'>" + obj["city_name"] + "</option>");
                            });
                    } else {
                    $("#city").empty();
                            alert("No Cities are Available");
                    }
                    },
                    error: function (error) {
                    console.log(error);
                            alert(error);
                    }
            });
    });
            /*******************End******************/
            
            /*************Get City on Select State*************************************************/
//$("#city").on('change', function(){
//var cityId=this.value;
//$.ajax({
//    url:'<?php //echo $this->basePath()?>'+'/user/getRustagiBranch',
//    type:"POST",
//dataType:"json",
//    data:{City_ID:cityId},
//    beforeSend: function(){
//            $('#Loading_Request').show();
//    },
//    complete: function(){
//            $('#Loading_Request').hide();
//    },
//    success:function(resp){
//$("#branch_other").hide();
//
//if(resp.Status=='Success'){
//$("#branch_ids").empty();
//$("#branch_ids").append("<option value=''>Select Branch</option>");
//$.each(resp.statelist, function(idx, obj) {                            
//$("#branch_ids").append("<option value='"+obj["branch_id"]+"'>"+obj["branch_name"]+"</option>");
//});
//}else{
//$("#branch_ids").empty();
//alert("No Branches are Available");
//$("#branch_other").show();
//}
//$("#branch_ids").append("<option value='Other'>Others</option>");
//    },
//    error:function(error){
//            console.log(error);	
//            alert(error);			
//    }
//});	
//});
/*******************End******************/
</script>

<SCRIPT language="javascript">
        function addRow(tableID) {
 
            var table = document.getElementById(tableID);
 
            var rowCount = table.rows.length;
            var row = table.insertRow(rowCount);
 
            var colCount = table.rows[0].cells.length;
 
            for(var i=0; i<colCount; i++) {
 
                var newcell = row.insertCell(i);
 
                newcell.innerHTML = table.rows[0].cells[i].innerHTML;
                //alert(newcell.childNodes);
                switch(newcell.childNodes[0].type) {
                    // case "text":
                    //         newcell.childNodes[0].value = "";
                    //         break;
                    case "checkbox":
                            newcell.childNodes[0].checked = false;
                            break;
                    case "select-one":
                            newcell.childNodes[0].selectedIndex = 0;
                            break;
                }
            }
        }
 
        function deleteRow(tableID) {
            try {
            var table = document.getElementById(tableID);
            var rowCount = table.rows.length;
 
            for(var i=0; i<rowCount; i++) {
                var row = table.rows[i];
                var chkbox = row.cells[0].childNodes[0];
                if(null != chkbox && true == chkbox.checked) {
                    if(rowCount <= 1) {
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
 
            }
            }catch(e) {
                alert(e);
            }
        }
 
    </SCRIPT>
    
    <script type="text/javascript">
       $(document).ready(function(){
	var maxField = 10; //Input fields increment limitation
	var addButton = $('.add_button'); //Add button selector
	var wrapper = $('.field_wrapper'); //Input field wrapper
        var filepath = '<?php echo $this->url("admin/institute", array("action"=>"institutesearch"));?>';
        //var institutesearchresp=institutesearchresp;
        var instituteName='instituteName';
        
	//var fieldHTML = '<div><input id="" class="form-control inputchange search_instituteName" placeholder="Institute Name" type="text" style="width: 180px;" onkeyup="institutesearchactions($(this).val(), '<?php echo $this->url("admin/institute", array("action"=>"institutesearch"));?>', institutesearchresp, "instituteName")" name="institute_name[]"/><div class="col-sm-3 institutesearchresults" id="" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;"></div><a href="javascript:void(0);" class="remove_button" title="Remove field">remove</a></div>';
        var fieldHTML = '<div><input id="" class="form-control inputchange search_instituteName" placeholder="Institute Name" type="text" style="width: 180px;" onkeyup="javascript:institutesearchactions($(this).val(),\''+filepath+ '\', institutesearchresp ,\''+instituteName+ '\')" name="institute_name[]"/><div class="col-sm-3 institutesearchresults" id="" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;"></div><a href="javascript:void(0);" class="remove_button" title="Remove field">remove</a></div>';
	var x = 1; //Initial field counter is 1
	$(addButton).click(function(){ //Once add button is clicked
		if(x < maxField){ //Check maximum number of input fields
			x++; //Increment field counter
			$(wrapper).append(fieldHTML); // Add field html
		}
	});
	$(wrapper).on('click', '.remove_button', function(e){ //Once remove button is clicked
		e.preventDefault();
		$(this).parent('div').remove(); //Remove field html
		x--; //Decrement field counter
	});
});
</script>