                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                           <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                        <th>S. No.</th>
                        <th class="hidden-480">Country</th>
                        <th class="hidden-480">State</th>
                        <th class="hidden-480">City</th>
                        <th>Institute Name</th>
                        
                        <!--<th class="hidden-480">Created Date</th>-->
                        <th class="hidden-480">Modified Date</th> 
                        <!--<th class="hidden-480">Created By</th>-->
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody id="sortable">
                        <input type="hidden" id="table_name" value="tbl_rustagi_institutions">
                            <input type="hidden" id="id_name" value="id">
                      <?php 
					  $i=1;
                         if (count($institutes) > 0) {  
                      foreach ($institutes as $institute) {
                      
                      ?>
                      <tr id="<?php echo $institute['id']; ?>" >
                        <td><input type="checkbox" value="<?=$institute['id']?>" class="checkme" name="checkme[]"> </td> 
                       <td><?= $i ?></td>  
                       <td><?= $institute['country_name']?></td> 
                       <td><?= $institute['state_name']?></td> 
                       <td><?= $institute['city_name']?></td> 
                        <td><?= $institute['institute_name']?></td>            
                        <!--<td class="hidden-480"><?//=$institute['created_date']?></td>-->
                        <td class="hidden-480"><?=$institute['modified_date']?></td>
                        <!--<td class="hidden-480"><?php //echo ($institute['modified_by']==1)? 'Admin': 'NotByAdmin'; ?></td>-->
                        <!--<td class="hidden-480"><?php //echo $institute['username']; ?></td>-->
                        <td class="hidden-480"><?php echo $institute['username'];?></td>
                        
                        
                        <td class="hidden-480">
						<!--<?php echo ($institute->isActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($institute['is_active']==1)? 'Active': 'In-Active';
                        $statuscolor = ($institute['is_active']==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$institute['id']?>,<?= ($institute['is_active']==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/institute', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        
                        <td><div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('admin',array('controller'=>'institute','action'=>'view','id'=>$institute->id)); ?>">
                         <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataByInstituteId('<?php echo $this->url
                                                           ('admin/institute', array('action'=>'viewById','id'=>$institute['id'])); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                         
                         <a class="green" href="javascript:void(0);" onclick="editbox(<?= 
                                                   $institute['id'] ?>, '<?php echo $this->url('admin/institute', array('action' => 
                                                       'edit', 'id' => $institute['id']));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 
                          <a class="red" href="<?php echo $this->url('admin/institute',array('action'=>'delete','id'=>
                              $institute['id'])); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa 
                                                                                             fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      
                      
                      
                      <?php 
                      $i++;
                    }
                    } else{
                        //Zend\Debug\Debug::dump($religions);
                        echo" <tr><td colspan=9><center><h2>No data available</h2></center></td></tr>";
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                
<?php 

if($this->action!='index'){
    ?>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.2.1.1.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.bootstrap.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.tableTools.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.colVis.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/table.js"></script> 
<?php
}

?>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery-1.10.2.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery-ui-1.10.4.custom.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/script.js"></script>
            
             