                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                           <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                        <th>S. No.</th>
                        <th class="hidden-480">Country</th>
                        <th class="hidden-480">State</th>
                        <th class="hidden-480">City</th>
                        <th>Institute Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        <!--<th class="hidden-480">Modified By</th>-->
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
					  $i=1;
                       if (count($results) > 0) {                   
                      foreach ($results as $institute) {
                          
//                          echo  "<pre>";
//                          print_r($institute);exit;
                      
                      ?>
                      <tr>
                        <td><input type="checkbox" value="<?=$institute['id']?>" class="checkme" name="checkme[]"> </td> 
                       <td><?= $i ?></td>  
                       <td><?= $institute['country_name']?></td> 
                       <td><?= $institute['state_name']?></td> 
                       <td><?= $institute['city_name']?></td> 
                        <td><?= $institute['institute_name']?></td>                       
                        <td class="hidden-480"><?=$institute['modified_date']?></td>
                        <td class="hidden-480"><?=$institute['username']?></td>
                        
                        <td class="hidden-480">
						<!--<?php echo ($institute['is_active']==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($institute['is_active']==1)? 'Active': 'In-Active';
                        $statuscolor = ($institute['is_active']==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$institute['id']?>,<?= ($institute['is_active']==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/institute', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        <!--<td class="hidden-480"><?php //echo ($institute->modifiedBy==1)? 'Admin': 'NotByAdmin'; ?></td>-->
                        <td><div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('admin',array('controller'=>'institute','action'=>'view','id'=>$institute['id'])); ?>">
                         <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataByInstituteId('<?php echo $this->url
                                                           ('admin/institute', array('action'=>'viewById','id'=>$institute['id'])); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                         
                         <a class="green" href="javascript:void(0);" onclick="editbox(<?= 
                                                   $institute['id'] ?>, '<?php echo $this->url('admin/institute', array('action' => 
                                                       'edit', 'id' => $institute['id']));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 
                          <a class="red" href="<?php echo $this->url('admin/institute',array('action'=>'delete','id'=>
                              $institute['id'])); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa 
                                                                                             fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      
                      
                      
                      <?php 
                      $i++;
                    }
                  } else
        echo" <tr><td colspan=9><center><h2>No data available</h2></center></td></tr>";
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                

            
             