<style>

	.activestatus{
		color:green;
		background:green;
		border-radius:30px; width:11px; height:11px;
		cursor:pointer
		
	}
	
	.de-activestatus{
		color:green;
		background:red;
		border-radius:30px; width:11px; height:11px;
		cursor:pointer
		
	}
	.col-sm-1
	{
		width:22px !important;
		padding:0 !important;
	}
	
	.thumbnail {
    background-color:  transparent !important;
    border: 1px solid #ddd;
    border-radius: 4px;
    display: block;
    line-height: 1.42857;
    margin-bottom: 0 !important;
    padding: 0 !important;
    transition: border 0.2s ease-in-out 0s;
}
</style>

<?php 

?>
        <div class="ace-settings-container" id="ace-settings-container">
          <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn"> <i class="ace-icon fa fa-cog bigger-130"></i> </div>
          <div class="ace-settings-box clearfix" id="ace-settings-box">
            <div class="pull-left width-50">
              <div class="ace-settings-item">
                <div class="pull-left">
                  <select id="skin-colorpicker" class="hide">
                    <option data-skin="no-skin" value="#438EB9">#438EB9</option>
                    <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                    <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                    <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                  </select>
                </div>
                <span>&nbsp; Choose Skin</span> </div>
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
                <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
              </div>
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
                <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
              </div>
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
                <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
              </div>
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
                <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
              </div>
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container" />
                <label class="lbl" for="ace-settings-add-container"> Inside <b>.container</b> </label>
              </div>
            </div>
            <!-- /.pull-left -->
            
            <div class="pull-left width-50">
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover" />
                <label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
              </div>
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact" />
                <label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
              </div>
              <div class="ace-settings-item">
                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight" />
                <label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
              </div>
            </div>
            <!-- /.pull-left --> 
          </div>
          <!-- /.ace-settings-box --> 
        </div>
        <!-- /.ace-settings-container -->
        
        <div class="page-header">
          <h1> Dashboard <small> <i class="ace-icon fa fa-angle-double-right"></i> overview &amp; stats </small> </h1>
        </div>
        <!-- /.page-header -->
        
        <div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
            <!--<div class="alert alert-block alert-success">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i> Welcome to <strong class="green"> RUSTAGI SAMAJ </strong>,
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis. </div>-->
              
            <div class="row">
              <div class="col-md-15 col-sm-6 col-xs-6 col-xs-6new">
              <div class="panel panel-back noti-box">
              <span class="icon-box"><img src="/rustagi-new/public/assets/images/member.png" alt=""></span>
                <p class="main-text"><a href="<?php echo $this->basePath();?>/admin/matrimonyuser/memberuserindex">Total Members </a> </p>
                <div class="text-box" >
                  <?php 
                  foreach ($Members["Total Users"] as $key => $value) {
					  $key1	= "<span class='col-sm-10' style='padding:0;'>".$key."</span>";
					  $value1  = "<span class='col-sm-1'>".$value."</span>";
                   echo $key1."  ".$value1."<br>";
                  }
                  ?>
                </div>
                </div>
              </div>
              
              <div class="col-md-15 col-sm-6 col-xs-6 col-xs-6new">
             
               <div class="panel panel-back noti-box">
               <span class="icon-box"><img src="/rustagi-new/public/assets/images/member.png" alt=""></span>
                <p class="main-text"><a href="<?php echo $this->basePath();?>/admincontrol/matrimonyuser/matrimonyuserindex">Matrimonials Members</a></p>
                <div class="text-box" >
                 <?php 
                  foreach ($Members["Matrimony Users"] as $key => $value) {
					   $key1	= "<span class='col-sm-10' style='padding:0;'>".$key."</span>";
					  $value1  = "<span class='col-sm-1'>".$value."</span>";
                   echo $key1."  ".$value1."<br>";
                  }
                  ?>
                  
                </div>
                </div>
             
              </div>
           <!--   
              <div class="col-md-15 col-sm-6 col-xs-6 col-xs-6new" >
               <div class="panel panel-back noti-box">
               <span class="icon-box"><img src="/rustagi-new/public/assets/images/bride.png" alt=""></span>
                <p class="main-text">TOTAL BRIDES</p>
                <div class="text-box" >
                <?php 
                  foreach ($Members["Brides Users"] as $key => $value) {
                   echo $key." - ".$value."<br>";
                  }
                  ?>
                </div>
                </div>
              </div>
              
              <div class="col-md-15 col-sm-6 col-xs-6 col-xs-6new">
               <div class="panel panel-back noti-box">
               <span class="icon-box"><img src="/rustagi-new/public/assets/images/groom.png" alt=""></span>
                <p class="main-text">TOTAL GROOMS</p>
                <div class="text-box" >
                <?php 
                  foreach ($Members["Grooms Users"] as $key => $value) {
                   echo $key." - ".$value."<br>";
                  }
                  ?>
                </div>
                </div>
              </div>-->
              
              <div class="col-md-15 col-sm-6 col-xs-6 col-xs-6new">
               <div class="panel panel-back noti-box">
                <span class="icon-box"><img src="/rustagi-new/public/assets/images/member.png" alt=""></span>
                <p class="main-text"><a href="<?php echo $this->basePath();?>/admincontrol/matrimonyuser/memberuserindex">MEMBERS</a></p>
                <div class="text-box" >
                 <?php 
                  foreach ($Members["Member Users"] as $key => $value) {
					    $key1	= "<span class='col-sm-10' style='padding:0;'>".$key."</span>";
					  $value1  = "<span class='col-sm-1'>".$value."</span>";
                   echo $key1."  ".$value1."<br>";
                  }
                  ?>
                 
                </div>
                </div>
              </div>  
              
              <div class="col-md-15 col-sm-6 col-xs-6 col-xs-6new">
               <div class="panel panel-back noti-box">
               <span class="icon-box"><img src="/rustagi-new/public/assets/images/community.png" alt=""></span>
                <p class="main-text"><a href="<?php echo $this->basePath();?>/admincontrol/matrimonyuser/memberuserindex">TOTAL COMMUNITY</a></p>
                <div class="text-box" >
                <?php 
                  foreach ($Members["Community User"] as $key => $value) {
					    $key1	= "<span class='col-sm-10' style='padding:0;'>".$key."</span>";
					  $value1  = "<span class='col-sm-1'>".$value."</span>";
                   echo $key1."  ".$value1."<br>";
                  }
                  ?>
                 
                </div>
                </div>
              </div> 
                
              <div class="col-md-15 col-sm-6 col-xs-6 col-xs-6new">
               <div class="panel panel-back noti-box">
                <span class="icon-box"><img src="/rustagi-new/public/assets/images/member.png" alt=""></span>
                <p class="main-text">TOTAL POST</p>
                <div class="text-box" >
                <p>Currently not available</p>
                 
                </div>
                </div>
              </div>         
            </div>
            
            
            <div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
              <div class="col-sm-12">
                <div class="widget-box">
                  <div class="widget-header widget-header-flat widget-header-small">
                    <h5 class="widget-title"> <i class="ace-icon fa fa-signal"></i> Visualization Graph </h5>
                    <div class="widget-toolbar no-border">
                      <div class="inline dropdown-hover">
                        <button class="btn btn-minier btn-primary"> This Week <i class="ace-icon fa fa-angle-down icon-on-right bigger-110"></i> </button>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-125 dropdown-lighter dropdown-close dropdown-caret">
                          <li class="active"> <a href="#" class="blue"> <i class="ace-icon fa fa-caret-right bigger-110">&nbsp;</i> This Week </a> </li>
                          <li> <a href="#"> <i class="ace-icon fa fa-caret-right bigger-110 invisible">&nbsp;</i> Last Week </a> </li>
                          <li> <a href="#"> <i class="ace-icon fa fa-caret-right bigger-110 invisible">&nbsp;</i> This Month </a> </li>
                          <li> <a href="#"> <i class="ace-icon fa fa-caret-right bigger-110 invisible">&nbsp;</i> Last Month </a> </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="widget-body">
                    <div class="widget-main">
                      <div id="piechart-placeholder"></div>
                      <div class="hr hr8 hr-double"></div>
                      <div class="clearfix">
                        <div class="grid3"> <span class="grey"> <i class="ace-icon fa fa-facebook-square fa-2x blue"></i> &nbsp; likes </span>
                          <h4 class="bigger pull-right">1,255</h4>
                        </div>
                        <div class="grid3"> <span class="grey"> <i class="ace-icon fa fa-twitter-square fa-2x purple"></i> &nbsp; tweets </span>
                          <h4 class="bigger pull-right">941</h4>
                        </div>
                        <div class="grid3"> <span class="grey"> <i class="ace-icon fa fa-pinterest-square fa-2x red"></i> &nbsp; pins </span>
                          <h4 class="bigger pull-right">1,050</h4>
                        </div>
                      </div>
                    </div>
                    <!-- /.widget-main --> 
                  </div>
                  <!-- /.widget-body --> 
                </div>
                <!-- /.widget-box --> 
              </div>
              <!-- /.col --> 
            </div>
            <!-- /.row -->
            
            <div class="hr hr32 hr-dotted"></div>
            
            <!-- /.row -->
            
            <div class="row">
              <div class="col-sm-12">
                <div class="widget-box transparent" id="recent-box">
                  <div class="widget-header">
                    <h4 class="widget-title lighter smaller"> <i class="ace-icon fa fa-rss orange"></i>RECENT </h4>
                    <div class="widget-toolbar no-border">
                      <ul class="nav nav-tabs" id="recent-tab">
                        <li class="active"> <a data-toggle="tab" href="#members-tab">Members</a> </li>
                        <li> <a data-toggle="tab" href="#matrimony-members-tab">Matrimony Members</a> </li>
                        <li> <a data-toggle="tab" href="#latest-news-tab">Latest News</a> </li>
                        <li> <a data-toggle="tab" href="#latest-events-tab">Latest Events</a> </li>
                        <li> <a data-toggle="tab" href="#latest-community-tab">Latest Community</a> </li>
                      </ul>
                    </div>
                  </div>
                  <div class="widget-body">
                    <div class="widget-main padding-4">
                      <div class="tab-content padding-8">
                        <div id="members-tab" class="tab-pane active">
                          <h4 class="smaller lighter green"> <i class="ace-icon fa fa-list"></i> Members Lists </h4>
                          <ul id="tasks" class="item-list">
                            <li class="item-orange clearfix">
                              <label class="inline">
                                <input type="checkbox" class="ace" />
                                <span class="lbl"> Answering customer questions</span> </label>
                              <div class="pull-right easy-pie-chart percentage" data-size="30" data-color="#ECCB71" data-percent="42"> <span class="percent">42</span>% </div>
                            </li>
                            <li class="item-red clearfix">
                              <label class="inline">
                                <input type="checkbox" class="ace" />
                                <span class="lbl"> Fixing bugs</span> </label>
                              <div class="pull-right action-buttons"> <a href="#" class="blue"> <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <span class="vbar"></span> <a href="#" class="red"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> <span class="vbar"></span> <a href="#" class="green"> <i class="ace-icon fa fa-flag bigger-130"></i> </a> </div>
                            </li>
                            <li class="item-default clearfix">
                              <label class="inline">
                                <input type="checkbox" class="ace" />
                                <span class="lbl"> Adding new features</span> </label>
                              <div class="inline pull-right position-relative dropdown-hover">
                                <button class="btn btn-minier bigger btn-primary"> <i class="ace-icon fa fa-cog icon-only bigger-120"></i> </button>
                                <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                                  <li> <a href="#" class="tooltip-success" data-rel="tooltip" title="Mark&nbsp;as&nbsp;done"> <span class="green"> <i class="ace-icon fa fa-check bigger-110"></i> </span> </a> </li>
                                  <li> <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete"> <span class="red"> <i class="ace-icon fa fa-trash-o bigger-110"></i> </span> </a> </li>
                                </ul>
                              </div>
                            </li>
                            <li class="item-blue clearfix">
                              <label class="inline">
                                <input type="checkbox" class="ace" />
                                <span class="lbl"> Upgrading scripts used in template</span> </label>
                            </li>
                            <li class="item-grey clearfix">
                              <label class="inline">
                                <input type="checkbox" class="ace" />
                                <span class="lbl"> Adding new skins</span> </label>
                            </li>
                            <li class="item-green clearfix">
                              <label class="inline">
                                <input type="checkbox" class="ace" />
                                <span class="lbl"> Updating server software up</span> </label>
                            </li>
                            <li class="item-pink clearfix">
                              <label class="inline">
                                <input type="checkbox" class="ace" />
                                <span class="lbl"> Cleaning up</span> </label>
                            </li>
                          </ul>
                        </div>
                        <div id="matrimony-members-tab" class="tab-pane">
                          <h4 class="smaller lighter green"> <i class="ace-icon fa fa-list"></i> Matrimony Members </h4>
                          <div class="clearfix">
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Bob Doe's avatar" src="<?=$this->basePath().$path?>/assets/avatars/user.jpg" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Bob Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">20 min</span> </div>
                                <div> <span class="label label-warning label-sm">pending</span>
                                  <div class="inline position-relative">
                                    <button class="btn btn-minier btn-yellow btn-no-border dropdown-toggle" data-toggle="dropdown" data-position="auto"> <i class="ace-icon fa fa-angle-down icon-only bigger-120"></i> </button>
                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                      <li> <a href="#" class="tooltip-success" data-rel="tooltip" title="Approve"> <span class="green"> <i class="ace-icon fa fa-check bigger-110"></i> </span> </a> </li>
                                      <li> <a href="#" class="tooltip-warning" data-rel="tooltip" title="Reject"> <span class="orange"> <i class="ace-icon fa fa-times bigger-110"></i> </span> </a> </li>
                                      <li> <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete"> <span class="red"> <i class="ace-icon fa fa-trash-o bigger-110"></i> </span> </a> </li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Joe Doe's avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar2.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Joe Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">1 hour</span> </div>
                                <div> <span class="label label-warning label-sm">pending</span>
                                  <div class="inline position-relative">
                                    <button class="btn btn-minier btn-yellow btn-no-border dropdown-toggle" data-toggle="dropdown" data-position="auto"> <i class="ace-icon fa fa-angle-down icon-only bigger-120"></i> </button>
                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                      <li> <a href="#" class="tooltip-success" data-rel="tooltip" title="Approve"> <span class="green"> <i class="ace-icon fa fa-check bigger-110"></i> </span> </a> </li>
                                      <li> <a href="#" class="tooltip-warning" data-rel="tooltip" title="Reject"> <span class="orange"> <i class="ace-icon fa fa-times bigger-110"></i> </span> </a> </li>
                                      <li> <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete"> <span class="red"> <i class="ace-icon fa fa-trash-o bigger-110"></i> </span> </a> </li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Jim Doe's avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Jim Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">2 hour</span> </div>
                                <div> <span class="label label-warning label-sm">pending</span>
                                  <div class="inline position-relative">
                                    <button class="btn btn-minier btn-yellow btn-no-border dropdown-toggle" data-toggle="dropdown" data-position="auto"> <i class="ace-icon fa fa-angle-down icon-only bigger-120"></i> </button>
                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                      <li> <a href="#" class="tooltip-success" data-rel="tooltip" title="Approve"> <span class="green"> <i class="ace-icon fa fa-check bigger-110"></i> </span> </a> </li>
                                      <li> <a href="#" class="tooltip-warning" data-rel="tooltip" title="Reject"> <span class="orange"> <i class="ace-icon fa fa-times bigger-110"></i> </span> </a> </li>
                                      <li> <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete"> <span class="red"> <i class="ace-icon fa fa-trash-o bigger-110"></i> </span> </a> </li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Alex Doe's avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar5.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Alex Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">3 hour</span> </div>
                                <div> <span class="label label-danger label-sm">blocked</span> </div>
                              </div>
                            </div>
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Bob Doe's avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar2.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Bob Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">6 hour</span> </div>
                                <div> <span class="label label-success label-sm arrowed-in">approved</span> </div>
                              </div>
                            </div>
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Susan's avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar3.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Susan</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">yesterday</span> </div>
                                <div> <span class="label label-success label-sm arrowed-in">approved</span> </div>
                              </div>
                            </div>
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Phil Doe's avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar4.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Phil Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">2 days ago</span> </div>
                                <div> <span class="label label-info label-sm arrowed-in arrowed-in-right">online</span> </div>
                              </div>
                            </div>
                            <div class="itemdiv memberdiv">
                              <div class="user"> <img alt="Alexa Doe's avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar1.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Alexa Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">3 days ago</span> </div>
                                <div> <span class="label label-success label-sm arrowed-in">approved</span> </div>
                              </div>
                            </div>
                          </div>
                          <div class="space-4"></div>
                          <div class="center"> <i class="ace-icon fa fa-users fa-2x green middle"></i> &nbsp; <a href="#" class="btn btn-sm btn-white btn-info"> See all members &nbsp; <i class="ace-icon fa fa-arrow-right"></i> </a> </div>
                          <div class="hr hr-double hr8"></div>
                        </div>
                     
                        
                        <div id="latest-news-tab" class="tab-pane">
                          <h4 class="smaller lighter green"> <i class="ace-icon fa fa-list"></i> Latest News </h4>
                          <div class="comments">
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Bob Doe's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Bob Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">6 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="inline position-relative">
                                  <button class="btn btn-minier bigger btn-yellow dropdown-toggle" data-toggle="dropdown"> <i class="ace-icon fa fa-angle-down icon-only bigger-120"></i> </button>
                                  <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                    <li> <a href="#" class="tooltip-success" data-rel="tooltip" title="Approve"> <span class="green"> <i class="ace-icon fa fa-check bigger-110"></i> </span> </a> </li>
                                    <li> <a href="#" class="tooltip-warning" data-rel="tooltip" title="Reject"> <span class="orange"> <i class="ace-icon fa fa-times bigger-110"></i> </span> </a> </li>
                                    <li> <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete"> <span class="red"> <i class="ace-icon fa fa-trash-o bigger-110"></i> </span> </a> </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Jennifer's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar1.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Jennifer</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="blue">15 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Joe's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar2.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Joe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="orange">22 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Rita's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar3.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Rita</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="red">50 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                          </div>
                          <div class="hr hr8"></div>
                          <div class="center"> <i class="ace-icon fa fa-comments-o fa-2x green middle"></i> &nbsp; <a href="#" class="btn btn-sm btn-white btn-info"> See all comments &nbsp; <i class="ace-icon fa fa-arrow-right"></i> </a> </div>
                          <div class="hr hr-double hr8"></div>
                        </div>
                        <div id="latest-events-tab" class="tab-pane">
                          <h4 class="smaller lighter green"> <i class="ace-icon fa fa-list"></i> Latest Events </h4>
                          <div class="comments">
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Jennifer's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar1.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Jennifer</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="blue">15 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Bob Doe's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Bob Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">6 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="inline position-relative">
                                  <button class="btn btn-minier bigger btn-yellow dropdown-toggle" data-toggle="dropdown"> <i class="ace-icon fa fa-angle-down icon-only bigger-120"></i> </button>
                                  <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                    <li> <a href="#" class="tooltip-success" data-rel="tooltip" title="Approve"> <span class="green"> <i class="ace-icon fa fa-check bigger-110"></i> </span> </a> </li>
                                    <li> <a href="#" class="tooltip-warning" data-rel="tooltip" title="Reject"> <span class="orange"> <i class="ace-icon fa fa-times bigger-110"></i> </span> </a> </li>
                                    <li> <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete"> <span class="red"> <i class="ace-icon fa fa-trash-o bigger-110"></i> </span> </a> </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Joe's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar2.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Joe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="orange">22 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Rita's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar3.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Rita</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="red">50 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                          </div>
                          <div class="hr hr8"></div>
                          <div class="center"> <i class="ace-icon fa fa-comments-o fa-2x green middle"></i> &nbsp; <a href="#" class="btn btn-sm btn-white btn-info"> See all comments &nbsp; <i class="ace-icon fa fa-arrow-right"></i> </a> </div>
                          <div class="hr hr-double hr8"></div>
                        </div>
                        <div id="latest-community-tab" class="tab-pane">
                          <h4 class="smaller lighter green"> <i class="ace-icon fa fa-list"></i> Latest Community </h4>
                          <div class="comments">
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Bob Doe's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Bob Doe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="green">6 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="inline position-relative">
                                  <button class="btn btn-minier bigger btn-yellow dropdown-toggle" data-toggle="dropdown"> <i class="ace-icon fa fa-angle-down icon-only bigger-120"></i> </button>
                                  <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                    <li> <a href="#" class="tooltip-success" data-rel="tooltip" title="Approve"> <span class="green"> <i class="ace-icon fa fa-check bigger-110"></i> </span> </a> </li>
                                    <li> <a href="#" class="tooltip-warning" data-rel="tooltip" title="Reject"> <span class="orange"> <i class="ace-icon fa fa-times bigger-110"></i> </span> </a> </li>
                                    <li> <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete"> <span class="red"> <i class="ace-icon fa fa-trash-o bigger-110"></i> </span> </a> </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Jennifer's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar1.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Jennifer</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="blue">15 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Joe's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar2.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Joe</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="orange">22 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                            <div class="itemdiv commentdiv">
                              <div class="user"> <img alt="Rita's Avatar" src="<?=$this->basePath().$path?>/assets/avatars/avatar3.png" /> </div>
                              <div class="body">
                                <div class="name"> <a href="#">Rita</a> </div>
                                <div class="time"> <i class="ace-icon fa fa-clock-o"></i> <span class="red">50 min</span> </div>
                                <div class="text"> <i class="ace-icon fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis &hellip; </div>
                              </div>
                              <div class="tools">
                                <div class="action-buttons bigger-125"> <a href="#"> <i class="ace-icon fa fa-pencil blue"></i> </a> <a href="#"> <i class="ace-icon fa fa-trash-o red"></i> </a> </div>
                              </div>
                            </div>
                          </div>
                          <div class="hr hr8"></div>
                          <div class="center"> <i class="ace-icon fa fa-comments-o fa-2x green middle"></i> &nbsp; <a href="#" class="btn btn-sm btn-white btn-info"> See all comments &nbsp; <i class="ace-icon fa fa-arrow-right"></i> </a> </div>
                          <div class="hr hr-double hr8"></div>
                        </div>
                      </div>
                    </div>
                    
                  </div>
                 
                </div>
               
              </div>
            
            </div>
            <!-- /.row -->
            
            <!--<div class="hr hr-18 dotted hr-double"></div>-->
            <!--<h4 class="pink"> <i class="ace-icon fa fa-hand-o-right icon-animated-hand-pointer blue"></i> <a href="#modal-table" role="button" class="green" data-toggle="modal"> Table Inside a Modal Box </a> </h4>-->
<!--            <div class="hr hr-18 dotted hr-double"></div>-->
            <div id="editForm" class="tab-content dontshow">
                </div>
            <div class="row">
              <div class="col-xs-12">
               <!-- <h3 class="header smaller lighter blue">jQuery dataTables</h3>-->
                <div class="clearfix">
                  <div class="pull-right tableTools-container"></div>
                </div>
                <div class="table-header"> Results for "Latest Registered Member" </div>
                
                <!-- div.table-responsive --> 
                
                <!-- div.dataTables_borderWrap -->
                <div>
                <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                       <th>S.No. </th>
                        <th  style="width:4%;"><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" ></th>
                        <th>Image</th>
                        <th>Name</th>
                       <!-- <th>Last Name</th>-->
                        <th class="">Father Name</th>
                         <th class="">Residence</th>
                          <th class="">Native Place</th>
                           <th class="">Mobile N.</th>
                            <th class="">User Type</th>
                            <th class="">User Status</th> 
                           <th class="">Period</th>                        
                        <th class="">Status</th>
                        <th class="">Action</th>
                       <!-- <th style="width:8%;"></th>-->
                      </tr>
                    </thead>
                    <tbody>
                     <?php 
                      $i=1;
                      if(count($TopNewUsers)>0){
                      foreach ($TopNewUsers as $NewUsers) {
//                          echo  "<pre>";
//                          print_r($NewUsers);
//                          echo  "</pre>";exit;
                      ?>
                    
                      <tr>
                        <td><?=$i?></td>
                        <td><input type="checkbox" value="<?=$NewUsers->id?>" class="checkme" name="checkme[]"> </td>
                        <td style="width:6% !important;">
                        <div class="col-sm-1">
                          <a  href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox">
                          <?php 
                          $path = (empty($NewUsers->profile_photo))? "/img/default_user.png":$NewUsers->profile_photo;
                          
                          ?>
                         
                          <img src="<?=$this->basePath().$path?>" class="img-responsive" alt="">
                          </a>
                          </div>
                          
                          </td>
                        <td><?=$NewUsers->full_name ?></td>                       
                       <!--/* <td class="hidden-480"><?=$NewUsers->full_name ?></td>*/-->
                        <td><?php //echo $NewUsers->father_name ?></td>
                         <td><?=$NewUsers->address ?></td>
                          <td><?=$NewUsers->native_place ?></td>
                           <td><?=$NewUsers->mobile_no ?></td>
                            <td>
                            	<div class="memberstatus iconsize" title="Member"></div> 
                                <?php 
                                if($NewUsers->IsExecutive==1){?>
                                    <div class="userstatus iconsize" title="Executive"></div>
                              <?php  }
                                ?>
                                <div class="plan5status iconsize" title="Free Membership"></div>
                            
                            
                            </td>
                             <td>
                            	<span class="label label-sm label-info arrowed arrowed-righ">Paid</span>
                            
                            </td>
                            
                             <td>2017-02-20</td>
                        <td class="hidden-480" align="center">
						
							<div style="float:left;">					
						<?php $status = ($NewUsers->is_active==1)? 'Active': 'In-Active';
                        $statuscolor = ($NewUsers->is_active==1)? 'activestatus': 'de-activestatus';
                         ?>
                         
                         <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$NewUsers->id?>,<?= ($NewUsers->is_active==0)?0:1; ?>,'<?php echo $this->url('admin/dashboard', array('action'=>'changestatus'));?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </div>
                            
                        <div style="float:left;">					
						<?php $status = ($NewUsers->is_used==1)? 'Approved': 'Un-Approved';
                        $apprv_unapprve = ($NewUsers->is_used==1)? 'aprovestatus iconsize': 'unaprovestatus iconsize';
                         ?>
                         
                         <div name="ChangeStatus" id="changestatus<?=$i;?>" class="<?=$apprv_unapprve?>">
                        </div>
                        </div>
                            
                        <div style="float:left;">					
						<?php $status = ($NewUsers->is_used==1)? 'Approved': 'Un-Approved';
                        $online = ($NewUsers->login_status==1)? 'onlinestatus iconsize': '';
                         ?>
                         
                         <div name="ChangeStatus" id="changestatus<?=$i;?>" class="<?=$online?>">
                        </div>
                        </div>
                            
                         </td>
                        <td style="width:8%;">
                          <div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('admin',array('controller'=>'institute','action'=>'view','id'=>$institute->id)); ?>">
                         <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataByMemberId('<?php echo $this->url
                                                           ('admin/dashboard', array('action'=>'viewByMemberId','id'=>$NewUsers->id)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                         
                         <a class="green" href="javascript:void(0);" onclick="editbox(<?= 
                                                   $NewUsers->id ?>, '<?php echo $this->url('admin/dashboard', array('action' => 
                                                       'edit', 'id' => $NewUsers->id));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 
                          <a class="red" href="<?php echo $this->url('admin/dashboard',array('action'=>'delete','id'=>
                              $NewUsers->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa 
                                                                                             fa-trash-o bigger-130"></i> </a> </div></td>
                      </tr>
                      
                      <?php 
                    $i++;
                    }
                  }
                      ?>
                     
                    </tbody>
                  </table>
                
                  
                </div>
                
                <div class="col-sm-12" style="margin-top:10px;">
                <div class="memberstatus iconsize1" title="Member"></div><label class="reffranaceicon">Member</label>
                <div class="userstatus iconsize" title="Community"></div><label class="reffranaceicon">Community</label>
                <div class="plan1status iconsize1" title="Member"></div><label class="reffranaceicon">Whole Life Membership</label>
                <div class="plan2status iconsize1" title="Member"></div><label class="reffranaceicon">Yearly Membership</label>
                <div class="plan3status iconsize1" title="Member"></div><label class="reffranaceicon">Half Yearly Membership</label>
                <div class="plan4status iconsize1" title="Member"></div><label class="reffranaceicon">Quatrly Membership</label>
                <div class="plan5status iconsize1" title="Member"></div><label class="reffranaceicon">Free Membership</label>
                 <!--<div class="matrimonistatus iconsize1" title="Member"></div><label class="reffranaceicon">Matrimonial</label>-->
                 <div class="activestatus iconsize1" title="Member"></div><label class="reffranaceicon">Active</label>
                 <div class="de-activestatus iconsize1" title="Member"></div><label class="reffranaceicon">De-Active</label>
                 
                    <div class="aprovestatus iconsize1" title="Member"></div><label class="reffranaceicon">Approved</label>
                     <div class="unaprovestatus iconsize1" title="Member"></div><label class="reffranaceicon">Un-Approved</label>
                     <div class="blokedstatus iconsize1" title="Member"></div><label class="reffranaceicon">Blocked</label>
                    <div class="onlinestatus iconsize1" title="Member"></div><label class="reffranaceicon">Online</label>
                    <div class="flagedstatus iconsize1" title="Member"></div><label class="reffranaceicon">Flagged</label>
                
                </div>
              </div>
            </div>
            
            <div id="editFormMatrimonial" class="tab-content dontshow">
                </div>
            <div class="row">
              <div class="col-xs-12">
               <!-- <h3 class="header smaller lighter blue">jQuery dataTables</h3>-->
                <div class="clearfix" style="margin-bottom:30px;">
                  
                </div>
                <div class="table-header"> Results for "Latest Registered Matrimonial" </div>
                
                <!-- div.table-responsive --> 
                
                <!-- div.dataTables_borderWrap -->
                <div>
                <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                       <th>S.No. </th>
                        <th  style="width:4%;"><input type="checkbox" value="" id="checkAll2" onclick="checkall2(this.id)" ></th>
                        <th>Image</th>
                        <th>Name</th>
                       <!-- <th>Last Name</th>-->
                        <th class="">Father Name</th>
                         <th class="">Residence</th>
                          <th class="">Native Place</th>
                           <th class="">Mobile N.</th>
                            <th class="">User Type</th>
                            <th class="">User Status</th> 
                           <th class="">Period</th>                        
                        <th class="">Status</th>
                        <th class="">Action</th>
                       <!-- <th style="width:8%;"></th>-->
                      </tr>
                    </thead>
                    <tbody>
                     <?php 
                      $i=1;
                      if(count($TopNewMatrimonials)>0){
                      foreach ($TopNewMatrimonials as $NewUsers2) {
//                          echo  "<pre>";
//                          print_r($NewUsers);
//                          echo  "</pre>";exit;
                      ?>
                    
                      <tr>
                        <td><?=$i?></td>
                        <td><input type="checkbox" value="<?=$NewUsers2->id?>" class="checkme2" name="checkme2[]"> </td>
                        <td style="width:6% !important;">
                        <div class="col-sm-1">
                          <a  href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox">
                          <?php      $image = (empty($NewUsers2->image_name))? '/images/new-big.jpg' : $NewUsers2->image_name;?><img src="<?php echo $this->basepath().'/matrimonial/'.$image; ?>" >
                          </a>
                          </div>
                          
                          </td>
                        <td><?=$NewUsers2->full_name ?></td>                       
                       <!--/* <td class="hidden-480"><?=$NewUsers2->full_name ?></td>*/-->
                        <td><?php echo $NewUsers2->name ?></td>
                         <td><?=$NewUsers2->address ?></td>
                          <td><?=$NewUsers2->native_place ?></td>
                           <td><?=$NewUsers2->mobile_no ?></td>
                            <td>
                            	<div class="matrimonistatus iconsize" title="Matrimonial"></div> 
                                <?php 
                                //if($NewUsers2->IsMember==1 && $NewUsers2->IsExecutive==1){?>
                                    <div class="userstatus iconsize" title="Executive"></div>
                              <?php  //}
                                ?>
                                <div class="plan5status iconsize" title="Free Membership"></div>
                            
                            
                            </td>
                             <td>
                            	<span class="label label-sm label-info arrowed arrowed-righ">Paid</span>
                            
                            </td>
                            
                             <td>2017-02-20</td>
                        <td class="hidden-480" align="center">
						
							<div style="float:left;">					
						<?php $status = ($NewUsers2->is_active==1)? 'Active': 'In-Active';
                        $statuscolor = ($NewUsers2->is_active==1)? 'activestatus': 'de-activestatus';
                         ?>
                         
                         <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$NewUsers2->id?>,<?= ($NewUsers2->is_active==0)?0:1; ?>,'<?php echo $this->url('admin/dashboard', array('action'=>'changematrimonialstatus'));?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </div>
                            
                        <div style="float:left;">					
						<?php $status = ($NewUsers2->is_used==1)? 'Approved': 'Un-Approved';
                        $apprv_unapprve = ($NewUsers2->is_used==1)? 'aprovestatus iconsize': 'unaprovestatus iconsize';
                         ?>
                         
                         <div name="ChangeStatus" id="changestatus<?=$i;?>" class="<?=$apprv_unapprve?>">
                        </div>
                        </div>
                            
                        <div style="float:left;">					
						<?php $status = ($NewUsers2->is_used==1)? 'Approved': 'Un-Approved';
                        $online = ($NewUsers2->login_status==1)? 'onlinestatus iconsize': '';
                         ?>
                         
                         <div name="ChangeStatus" id="changestatus<?=$i;?>" class="<?=$online?>">
                        </div>
                        </div>
                            
                         </td>
                        <td style="width:8%;">
                          <div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('admin',array('controller'=>'institute','action'=>'view','id'=>$institute->id)); ?>">
                         <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataByMatrimonialId('<?php echo $this->url
                                                           ('admin/dashboard', array('action'=>'viewByMatrimonialId','id'=>$NewUsers2->id)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                         
                         <a class="green" href="javascript:void(0);" onclick="editbox(<?= 
                                                   $NewUsers2->id ?>, '<?php echo $this->url('admin/dashboard', array('action' => 
                                                       'editmatrimonial', 'id' => $NewUsers2->id));
                                        ?>', editformmatrimonialresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 
                          <a class="red" href="<?php echo $this->url('admin/dashboard',array('action'=>'deletematrimonial','id'=>
                              $NewUsers2->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa 
                                                                                             fa-trash-o bigger-130"></i> </a> </div></td>
                      </tr>
                      
                      <?php 
                    $i++;
                    }
                  }
                      ?>
                     
                    </tbody>
                  </table>
                
                  
                </div>
                
                
              </div>
              <div class="col-sm-12" style="margin-top:10px;">
                <div class="matrimonistatus iconsize1" title="Member"></div><label class="reffranaceicon">Matrimonial</label>
                <div class="userstatus iconsize" title="Community"></div><label class="reffranaceicon">Community</label>
                <div class="plan1status iconsize1" title="Member"></div><label class="reffranaceicon">Whole Life Membership</label>
                <div class="plan2status iconsize1" title="Member"></div><label class="reffranaceicon">Yearly Membership</label>
                <div class="plan3status iconsize1" title="Member"></div><label class="reffranaceicon">Half Yearly Membership</label>
                <div class="plan4status iconsize1" title="Member"></div><label class="reffranaceicon">Quatrly Membership</label>
                <div class="plan5status iconsize1" title="Member"></div><label class="reffranaceicon">Free Membership</label>
                 <!--<div class="matrimonistatus iconsize1" title="Member"></div><label class="reffranaceicon">Matrimonial</label>-->
                 <div class="activestatus iconsize1" title="Member"></div><label class="reffranaceicon">Active</label>
                 <div class="de-activestatus iconsize1" title="Member"></div><label class="reffranaceicon">De-Active</label>
                 
                    <div class="aprovestatus iconsize1" title="Member"></div><label class="reffranaceicon">Approved</label>
                     <div class="unaprovestatus iconsize1" title="Member"></div><label class="reffranaceicon">Un-Approved</label>
                     <div class="blokedstatus iconsize1" title="Member"></div><label class="reffranaceicon">Blocked</label>
                    <div class="onlinestatus iconsize1" title="Member"></div><label class="reffranaceicon">Online</label>
                    <div class="flagedstatus iconsize1" title="Member"></div><label class="reffranaceicon">Flagged</label>
                
                </div>
            </div>
            
            <!-- PAGE CONTENT ENDS --> 
          </div>
          <!-- /.col --> 
        </div>
        <!-- /.row --> 

        
  <!-- comment by amir -->
<!--<div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <div class="modal-content">
            <div class="modal-body">
               
            </div>
        </div>
    </div>
</div>-->

<div id="viewMemberModel"></div>
<div id="viewMatrimonialModel"></div>