<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
      
      
          <tr class="dontshow" id="indview<?=$i?>" aria-expanded="true">
                     
                	<td colspan="7">
                    <div aria-expanded="true" class="panel-body accordion-body packageDetails1 collapse in" id="accordion1">
               
                          <div class="tab-content" id="myTabContent">
        
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                <div class="row">
                   <div class="form-group clearfix margintopbottom20 col-sm-12">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Full Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $info->full_name;
                                                     ?>                                    
                                                  </div>

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php echo $this->translate('Father Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $info->name;
                                                     ?>                                    
                                                  </div>

                                                <!--  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php //echo $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     //echo date('l d-m-Y',strtotime($info->createdDate));
                                                     ?>                                    
                                                  </div> -->
                           
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Residence'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $info->address;
                                                     ?>                                    
                                                  </div>

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Native Place'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $info->native_place;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mobile No'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $info->mobile_no;
                                                     ?>                                    
                                                  </div>

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo empty($info->is_active)?'De-Active':'Active';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php echo $this->translate('Image'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     
                                                     
                                                 <?php      $image = (empty($info->image_name))? '/images/new-big.jpg' : $info->image_name;?><img src="<?php echo $this->basepath().'/matrimonial/'.$image; ?>" >
                                                                                         
                                                  </div>
                                                 </div>
                                             </div>


                                          <!--   <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php //echo $this->translate('Modified By'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     //echo ($info->modifiedBy==1)?'Admin':'Not Available Now';
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php //echo $this->translate('Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     //echo ($info->isActive==1)? 'Active':'In-Active';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  -->

                                        <!--  <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php //echo $this->translate('Modified Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     //echo date('l d-m-Y',strtotime($info->modifiedDate));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  
                                             
              </div> -->
           
          </div>
      </div>
                    
                                             
                       </td>
                    </tr>   
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
         