<div >
    <p>
        <a href="<?= $this->url('admin/pages', array('action' => 'pagesindex')); ?>"><button class="btn btn-warning btn-xlg">Go Back</button></a>
    </p>
</div>


<div class="portlet-body">
    <?php
    $form = $this->form;
    $form->prepare();


    //$form->setAttribute('action',$this->url('admin',array('controller'=>'Pages','action'=>'add')));
    $form->setAttribute('action', $this->url('admin/pages', array('action' => 'pagesadd')));
    $form->setAttribute('method', 'post');
    $form->setAttribute('onsubmit','return SubmitAddPagesForm();');
    //$form->setAttribute('autocomplete', 'off');
    $form->setAttribute('id', 'PagesForm');
    //$form->setAttribute('enctype','multipart/form-data');
    //$action = $this->serverUrl().$this->url().'/pages/add';
    // $form->setAttribute('onSubmit');

    echo $this->form()->openTag($form);
// echo $this->formCollection($form);
    ?>

    <div class="tab-pane fade active in" id="driver_tab">
        <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">

            <div class="row" style="position:relative;z-index:1;">
                <div class="form-group clearfix margintopbottom20">
                    
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('title')->getLabel()) ?>
                    </label>
                   
                    <div class="col-sm-3" id="addparent" >
                        
                        <?php
                        echo $this->formHidden($form->get('id'));
                        echo $this->formElement($form->get('title'));
                        //echo $this->formElement($form->get('page_name'));
                        ?> 
                        <span class="showerror"></span>   

                    </div>
                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?= $this->translate($form->get('page_name')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3" id="addparent" >
                        
                        <?php
                       // echo $this->formHidden($form->get('id'));
                        //echo $this->formElement($form->get('title'));
                        echo $this->formElement($form->get('page_name'));
                        ?> 
                        <span class="showerror"></span>   

                    </div>




                </div>
            </div>

           


                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php echo $this->translate($form->get('description')->getLabel()); ?>
                    </label>
            
                    <div class="row">
                        <div class="col-xs-12">

                            <div class="wysiwyg-editor" id="editor1"></div>                              

                        </div><!-- /.col -->
                    </div><!-- /.row -->                
                

            <div class="row">
                <div class="form-group clearfix margintopbottom20">

                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                        <?php //echo $this->translate($form->get('image')->getLabel()) ?>
                    </label>
                    <div class="col-sm-3">
                        <?php
                        //echo $this->formElement($form->get('image'));
                        
                        echo $this->formElement($form->get('description'));
                        
                        //echo $this->formElement($form->get('is_active'));
                        
                        ?> 
                                                         

                    </div>
                   <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('is_active')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('is_active'));
                                                     ?>                                    
                                                  </div>
                </div>
            </div>
                    <a href="#"  data-toggle="modal" data-target="#avatar-modalpost_image"  class="cropimage">Upload Photo</a>
                    
        
    
        <img id="post_photo" src="<?php echo $this->basePath('img/default_user.png') ?>" width="40" height="40"/>
        <input type="hidden" name="image" id="image" value="">


    <?php
//echo $this->formElement($form->get('image'));
?>
                    
            <div class="row">
                <div class="form-group clearfix margintopbottom20">
                    <div class="col-sm-3 pull-right">
<?php
echo $this->formRow($form->get('submit'));
?>                                    
                    </div>
                    <div class="col-sm-1 pull-right">
                       <!-- <a class="btn btn-red defaultbtnsearch searchBooking" href="javascript:void(0);" onclick="location.reload();">Cancel</a>  -->                            
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
echo $this->form()->closeTag();
?>
</div>
</div>
</div>

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
<!--  added by amir -->
<div class="modal fade" id="avatar-modalpost_image" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="avatar-form" id="cropform_post" method="post" action="#" enctype="multipart/form-data" onsubmit="return croppostimage('<?= $this->serverurl() . $this->url() . "/croppostimage" ?>', croppostimageresults);">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title" id="avatar-modal-label">Post Picture</h4>
                </div>
                <div class="modal-body">
                    <div id="showloader_post" style="position:absolute;top:30%;left:0;width:100%;min-height:300px;display:none;z-index:1000;">
                        <center><img src="<?= $this->basepath() ?>/img/loadingmap2.gif"></center>
                    </div>


                    <h4>Image:</h4>
                    <input type="file" name="file" id="file_post"> 
                    <div class="banner"><img class="cropper2" id="showimage_post" src="<?= $this->basepath() ?>/img/default_user.png"></div>

                    <!--<input name="uid" id="uid" type="hidden">
                    <input name="ref_no" id="ref_no" type="hidden">
                    <input name="profile_photo_flag" id="profile_photo_flag" type="hidden">
                    <input name="profile_photo" id="profile_photo" type="hidden">

                    <input name="field_name" id="field_name1" type="hidden">

                    <input name="table_name" id="table_name1" type="hidden">-->

                    <input type="hidden" class="form-control" id="dataX11_post" placeholder="x1" name="x1">

                    <input type="hidden" class="form-control" id="dataY11_post" placeholder="y1" name="y1">

                    <input type="hidden" class="form-control" id="dataX21_post" placeholder="x2" name="x2">

                    <input type="hidden" class="form-control" id="dataY21_post" placeholder="y2" name="y2">

                    <input type="hidden" class="form-control" id="dataWidth1_post" placeholder="width" name="width">

                    <input type="hidden" class="form-control" id="dataHeight1_post" placeholder="height" name="height">

                    <input type="hidden" class="form-control" id="cropenabled2" name="cropenabled" value="Enable">
                    <!--<div id="forprofile">
                        <h5 style="font-weight:bold;color:cornflowerblue;">OR</h5>
                        <a href="#" id="profileFrom_gallery" data-toggle="modal" data-target="#chooseGallery" style="font-weight:bold;font-size:14px;color:chocolate;">Choose from Gallery</a>
                    </div>-->
                    <input type="hidden" id="actualimage_post" name="actualimage">
                    <button id="cropper-enable_post" type="button" class="btn btn-success croptrigger2">Enable</button>
                    <button id="cropper-disable_post" type="button" class="btn btn-danger croptrigger2">Disable</button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                    <input class="btn btn-primary avatar-save" type="submit" value="Save">
                </div>
            </form>
        </div>



    </div>
</div>
