
		<div class="col-sm-3">
    <div class="footer-panel">
        <h3>Need Help?</h3>
     		 <ul class="member_details">
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->basePath() ?>/user/login">Member Login</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->basePath() ?>/user/signup">Sign Up</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->basePath() ?>/matrimonial">Partner Search</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->basePath() ?>/membership">Member Directory</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('matrimonialfee') ?>">Premium Memberships</a></li>
                <!-- <li class="matrimony_arow" style="margin-top:5px;"><a href="#">Customer Support</a></li>-->
                </ul>
        </div></div>
        
        <div class="col-sm-3">
    <div class="footer-panel">
        <h3>Company</h3>
         <ul class="member_details">
        		 <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('about') ?>">About Us</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="#">Affiliate Program</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="#">Awards & Recognition</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('career') ?>">Career</a></li>
                 <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('contact') ?>">Contact Us</a></li>
                </ul>
        </div></div>
        
        <div class="col-sm-3">
    <div class="footer-panel">
        <h3>Privacy & You </h3>
         <ul class="member_details">
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('terms-of-use') ?>">Terms of Use</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('terms-of-use') ?>#policy">Privacy Policy</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('terms-of-use') ?>#disclaimer">Disclaimer</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('terms-of-use') ?>#safe">Be Safe Online</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('terms-of-use') ?>#thirdparatywebsite">Third Party Website</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('terms-of-use') ?>#content-post">Content Posted on the Site</a></li>
                	
              
                </ul>
        </div></div>
        
        <div class="col-sm-3">
    <div class="footer-panel">
        <h3>More</h3>
         <ul class="member_details">
                <li class="matrimony_arow" style="margin-top:5px;"><a href="#"> VIP Rustagi</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->basePath() ?>/membership">Select Rustagi</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->url('communities') ?>">Rustagi Centres</a></li>
                <li class="matrimony_arow" style="margin-top:5px;"><a href="<?php echo $this->basePath() ?>/matrimonial">Wedding Planning</a></li>
                 <li class="matrimony_arow" style="margin-top:5px;"><a href="#">Success Stories</a></li>
                 
                </ul>
        </div></div>