<div class="col-xs-7" style="line-height:30px;">Copyrights &copy; <?php echo date('Y') ?> Rustagi Samaj. Design & Developed by <a href="http://tracoweb.com/" target="_blank">TracoWeb.</a></div>

<div class="col-xs-5">
    <ul class="social-footer">
        <li><a href="#" class="facebook"></a></li>
        <li><a href="#" class="twitter"></a></li>
        <li><a href="#" class="gplus"></a></li>
        <li><a href="#" class="dribbble"></a></li>
    </ul>
</div>

<div class="modal fade" id="loginPopUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document" style="width:222px !important;">
        <div class="modal-content gnt-pad15 modal-contentnew">
            <form id="loginForm" method="POST" action="/user/loginUser" name="loginForm">
                <div class="form-group">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h2 class="modal-title" id="myModalLabel">Login</h2>
                    </div>
                    <div class="modal-body">

                        <div class="col-sm-12">
                            Email OR Mobile
                            <input type="text" name="login_email" id="login_email" class="form-control" />
                        </div>
                        <div class="col-sm-12">
                            Password
                            <input type="password" name="login_password" id="login_password" class="form-control" />
                        </div>

                        <div class="col-sm-12">

                            <input type="checkbox" name="rember" /><em>Remember me</em>
                        </div>

                        <div class="col-sm-12">

                            <button type="submit" name="login" id="login" class="btn btn-default btn-block popuplogingbut">Sign In</button>
                        </div>

                        <div class="col-sm-12">
                            <a type="submit" class="">Forgot your password?</a>
                        </div>

                        <div class="col-sm-12 text-center">OR</div>

                        <div class="col-sm-12">New account 
                            <a class="btn btn-default btn-block popuplogingbut" href="<?php echo $this->basePath() ?>/user/signup"><?php echo $this->translate('Signup') ?></a>

                        </div>

                        <div class="col-sm-12 text-center"> </div>  

                    </div>
                    <div class="clearfix"></div>
                    <div class="modal-footer">

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>