<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
            <span class="sr-only">Sub Page</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">

        <ul class="nav navbar-nav">
            <li><a href="<?php echo $this->basePath() ?>/history"><?php echo $this->translate('History') ?></a></li>
            <li><a href="<?php echo $this->basePath() ?>/vision"><?php echo $this->translate('Our Vision') ?></a></li>
            <li><a href="<?php echo $this->basePath() ?>/communities"><?php echo $this->translate('Other Rustagi Institutions') ?></a></li>
            <li><a href="<?php echo $this->basePath() ?>/community"><?php echo $this->translate('Team Member') ?></a></li>
            <!--<li><a href="<?php //echo $this->basePath() ?>/pages/branches"><?php //echo $this->translate('All India Branches')  ?></a></li>-->
        </ul>

    </div>
</nav>
<?php //Zend\Debug\Debug::dump($filters_data["country"]);?>
<div class="panel-group" id="accordion">
    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_country" ftype="country" onchange="filterDataCommunity()";>
                <option value=''>---Select---country---</option>
                <?php
                foreach ($filters_data["country"] as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->country_name . "</option>";
                }
                ?>
            </select>
        </li>
    </ul>


    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_state" ftype="state"  onchange="filterDataCommunity();">
            </select>
        </li>
    </ul>



    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_city" ftype="city"  onchange="filterDataCommunity();">
            </select>
        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <select class="form-control" id="rustagi_branch" ftype="rustagi_branch"  onchange="filterDataCommunity();">
            </select>

        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <select class="form-control" id="post_filter" ftype="post_filter"  onchange="filterDataCommunity();">
               <option value=''>---Filter by post---</option>
                <?php
                foreach ($filters_data["tbl_communities"] as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->category_name . "</option>";
                }
                ?>
            </select>

        </li>
    </ul>
</div>