<?php if ($this->authUser()->isLogin() === true) { ?>
<div id="tour_step1" data-step="1">
            <div id="profile_info_widget" class="profile_info" style="display:block">

                <div id="" class="my_rustagi_profile_info">
                    <div class="my_rustagi_thumbnail" align="center">  
                          <?php if($photo['image_path']!=""){ 
                              $imgPath=$this->basePath('/uploads/').$photo['image_path'];
                            }else{
                              $imgPath=$this->basePath('img/default_user.png');
                            }
                            ?>
                             <img src="<?php echo $imgPath; ?>" height="" width="100%">
                    </div>
                    
                    <div class="manage_links_wrap">
                        <a href="<?php echo $this->url('profile', array('action' => 'personal-profile')) ?>" class="light_blue">Edit Profile</a>
                        <a href="<?php echo $this->url('profile', array('action' => 'mygallery')) ?>" class="light_blue">Manage Photos</a>
                        <a href="<?php echo $this->url('profile', array('action'=>'profile-view')) ?>" class="light_blue">View Profile</a>
                         <a href="<?php echo $this->url('profile', array('action'=>'change-password')) ?>" class="light_blue">Change Password</a>
                         <a href="#" class="light_blue">Profile setting</a>
                        <!-- <a href="#" class="light_blue">Edit Preferences</a>
                                     <a href="#" class="light_blue">Privacy Options</a>-->
                    </div>
                   
                    </div>        </div>
        </div>

        <div class="inbox_widget">
            <ul>

                <li>
                    <span class="ms_ln_heading">Inbox</span>
                </li>  
                <li class="default">

                    <span class="ms_ln_heading">Inbox</span>
                </li>
                <li class="inner_list">
                    <div class="inner_folders">

        <a href="<?php echo $this->url('profile',array('action'=>'member-invitation-received', 'slug' => 'received'))?>">
                            <span class="span_bold"><?php echo $this->invitation['invitation']; ?></span>                <span>Invitations</span>
                            <span class="arrow_wrap"><span class="myshaadi_left_arrow"></span></span>            </a>
                    </div>
                </li>

                <li>
                    <span class="accepted_icon"></span>
                    <span class="ms_ln_heading">Accepted</span>

                </li>
                <li class="inner_list">
                    <div class="inner_folders">
 <a href="<?php echo $this->url('profile', array('action' => 'member-accepted',  'slug' => 'accepted')); ?>">
                        <span>Members</span>
                            <span class=" num"><?php echo $this->accepted['accepted']; ?></span>
                        </a>
                    </div>
                </li>

                <li>
                    <span class="sent_icon"></span>
                    <span class="ms_ln_heading">Sent</span>
                </li>
                <li class="inner_list">
                    <div class="inner_folders">

    <a href="<?php echo $this->url('profile',array('action'=>'member-invitation-sent', 'slug' => 'sent'))?>">
                            <span>Invitations </span>
                            <span class=" num"><?php echo $this->sent['sent']; ?></span></a>
                    </div>
                </li>
                
<li>
<span class="sent_icon"></span>
<span class="ms_ln_heading">Decline/Cancel</span>
</li>
<li class="inner_list">
<div class="inner_folders">
<a href="<?php echo $this->url('profile', array('action' => 'member-declined', 'slug' => 'interests')); ?>">
<span>Invitations </span>
<span class=" num"><?php echo $this->declineRequest['decline_request']; ?></span></a>
</div>
</li>
                
            </ul>
        </div>

<?php }?>

<div class="panel-group" id="membership_accordion">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" href="<?php echo $this->basePath()?>/membership">
        <span class="pull-right glyphicon"></span>Member Directory</a>
      </h4>
    </div>
    
  </div>



 <?php 

/*

 // foreach($filters_data["country"]["filter_query"]["country"] as $grdata){
 //          echo $grdata->id;
 //        } 


 // print_r($filters_data["country"][0]);

  // foreach($filters_data["country"] as $k=> $v)
  //           {
               
  //               print_r($v[1]);
  //               // echo "<option value=".$GrData->id.">".$GrData->country_name."</option>";
  //           }

 */?>
      <ul class="newulclass">
  <li>
      <select class="form-control" id="filter_country" ftype="country" onchange="filterMembership();">
        <option value="">---Select---country---</option>
                <?php
                foreach ($filters_data["country"] as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->country_name . "</option>";
                }
                ?>
      </select>
  </li>
</ul>


      <ul class="newulclass">
<li>
    <li><select class="form-control" id="filter_state" ftype="state"  onchange="filterMembership();">
            </select>
        </li>
</li>
</ul>
     

  
      <ul class="newulclass">
       <li>
            <select class="form-control" id="filter_city" ftype="city"  onchange="filterMembership();">
            </select>
        </li>
</ul>
     
 
      <ul class="newulclass">
        <li><input type="text" class="form-control" placeholder="---Pin---Code---" ftype="zip_pin_code" id="zip_pin_code"></li>
    </ul>
    <ul class="newulclass">
        <li><input type="text" class="form-control" placeholder="---Enter---Phone---No" ftype="phone_no" id="phone_no"></li>
    </ul>
    <ul class="newulclass">
        <li><input type="text" class="form-control" placeholder="---Name---" ftype="full_name" id="full_name"></li>
    </ul>
    <ul class="newulclass">
        <li><input type="text" class="form-control" placeholder="---Email---" ftype="office_email" id="office_email"></li>
    </ul>
    <ul class="newulclass">
        <li><input type="text" class="form-control" placeholder="---Enter---Profile---ID---" id="ref_no" ftype="ref_no"></li>
    </ul>
<ul class="newulclass">
        <li>
            <div class="slider">
                <b>Age:</b><br>
                <input type="hidden" id="amount_age1_member">
                <input type="hidden" id="amount_age2_member">
                <input type="hidden" id="member_age_change" value="0">
                <span class="amount" id="age-amount_member">0</span>
                <div class="slider-range" id="slider_age_member" ftype="age"></div> 
            </div>
        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <div class="slider">
                <b>Annual Income :</b><br>
                <input type="hidden" id="amount_annual_income1_member">
                <input type="hidden" id="amount_annual_income2_member">
                <input type="hidden" id="member_amount_change" value="0">
                <span class="amount" id="income-amount_member">0</span>
                <div class="slider-range" id="slider_annual_income_member" ftype="annual_income"></div> 
            </div>
        </li>
    </ul>

 <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_height" ftype="height" onchange="filterMembership();">
                <option value="">---Select---Height---</option>   
                <?php
                foreach ($filters_data["height"] as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->height . "</option>";
                }
                ?>
            </select>
        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_profession" ftype="profession" onchange="filterMembership();">
                <option value="">---Select---Profession---</option>   
                <?php
                foreach ($filters_data["profession"] as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->profession . "</option>";
                }
                ?>
            </select>
        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_education" ftype="education_field" onchange="filterMembership();">
                <option value="">---Select---Education---</option>   
                <?php
                foreach ($filters_data["education_level"] as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->education_field . "</option>";
                }
                ?>
            </select>
        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_designation" ftype="designation" onchange="filterMembership();">
                <option value="">---Select---Designation---</option>   
                <?php
                foreach ($filters_data["designation"] as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->designation . "</option>";
                }
                ?>
            </select>
        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_mstatus" ftype="marital_status" onchange="filterMembership();">
                <option value="">---Marital---Status---</option>   
                <option value="Single">Single</option>   
                <option value="Married">Married</option>   
                <option value="Divorced">Divorced</option>   
                <option value="Widowed">Widowed</option>   
                <option value="Separated">Separated</option>   
            </select>
        </li>
    </ul>
    <ul class="newulclass">
        <li>
            <select class="form-control" id="filter_dossam" ftype="manglik_dossam" onchange="filterMembership();">
                <option value="">---Manglik---Dosh---</option>
                <option value="Manglik">Manglik</option>
                <option value="Non Manglik">Non Manglik</option>
            </select>
        </li>
    </ul>
     
      

    
       
      
   </div>

  <?php  echo $this->partial('layout/sidebar-slider')   ?>

 
