                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                        
                        <th>S.No.</th>
                        <th>Category Name</th>
                        <!--<th class="hidden-480">Created Date</th>-->
                        <th class="hidden-480">Modified Date</th>                        
                        <!--<th class="hidden-480">Created By</th>-->
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                        <!--<input type="hidden" id="table_name" value="tbl_newscategory">
                            <input type="hidden" id="id_name" value="id">-->
                      <?php 
                      $i=1;
                      foreach ($newscategories as $newscategory) {
                      
                      ?>
                      <tr id="<?php //echo $newscategory['id']; ?>" >
                         
                       
                        <td><?= $i?></td>                       
                        <td><?= $newscategory['category_name']?></td>                       
                        <!--<td class="hidden-480"><?//= $newscategory['created_date'];?></td>-->
                        <td class="hidden-480"><?= $newscategory['modified_date'];?></td>
                        <!--<td class="hidden-480"><?php //echo $newscategory['username']; ?></td>-->
                        <td class="hidden-480"><?php echo $newscategory['username'];?></td>
                        <!--<td class="hidden-480"><?php //echo ($newscategory->isActive==1)? 'Active': '<span '
                                //. 'class="label label-sm label-warning">In-Active</span>'; ?></td>-->
                        <td class="hidden-480">
						<!--<?php echo ($newscategory['is_active']==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($newscategory['is_active']==1)? 'Active': 'In-Active';
                        $statuscolor = ($newscategory['is_active']==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$newscategory['id']?>,<?= ($newscategory['is_active']==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/news', array('action'=>
                                                                    'categorychangestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        <!--<td class="hidden-480"><?php //echo ($newscategory['modified_by']==1)? 'Admin': 'NotByAdmin'; ?></td>-->
                        <td><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" href="<?php echo $this->url('admin/news',array('action'=>'viewnewscategory','id'=>$newscategory['id'])); ?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> <a class="green" href="<?php echo $this->url('admin/news',array('action'=>'editnewscategory','id'=>$newscategory['id'])); ?>" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('admin/news',array('action'=>'deletenewscategory','id'=>$newscategory['id'])); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                
<?php 

if($this->action!='indexnewscategory'){
    ?>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.2.1.1.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.bootstrap.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.tableTools.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.colVis.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/table.js"></script> 
<?php
}
?>
<!-- <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="<?php //echo $this->basePath(); ?>/assets/js/jquery-1.10.2.js"></script> 
<script src="<?php //echo $this->basePath(); ?>/assets/js/jquery-ui-1.10.4.custom.min.js"></script> 
<script src="<?php //echo $this->basePath(); ?>/assets/js/script.js"></script> -->
            
             