<div class="container" style="margin-bottom:100px;">
    <div class="row" align="center">
        <div class="col-sm-6" align="center" style="float:none !important; box-shadow:0 0 2px 0; margin:10px 0; ">

            
                <div class="form-group">
                    <div class="modal-header">

                        <h2 class="modal-title" id="myModalLabel">Login</h2>
                    </div>
                    <div class="modal-body">
                        
                        <form action="<?php echo $this->basePath() ?>/user/login-user" name="" method="post">
                        <div class="col-sm-6">
                         
                            <div class="btn btn-default btn-block popuplogingbut" style="background:#eda344 !important; padding:18px 0; font-size:18px; color:#fff; border-radius:50% !important; height:140px; width:140px;">
                           	 <img src="/images/matrimoni_icon.png" />
                            </div>
                            <input type="checkbox" name="matrimonial_user" value="1" id="matrimonail_user" checked="" class="abc" /><h3 style="margin-top:5px; font-size:14px;">Matrimonial User</h3>
                           
                        </div>
                        <div class="col-sm-6">
                       
                        <div class="btn btn-default btn-block popuplogingbut" style="background:#eda344 !important; padding:0 0; font-size:18px; color:#fff; border-radius:50% !important; height:140px; width:140px;">
                            <IMG src="/images/membership.png" />
                           </div> 
                           <input type="checkbox" name="member_user" value="1" id="member_user" class="abc" /><h3 style="margin-top:5px; font-size:14px;">Membership User</h3>
                           
                        </div>

                        

                       <div class="col-sm-12">
                            <button type="submit" name="login" id="login" class="btn btn-default btn-block popuplogingbut">Log-In</button>
                        </div>

                        </form>
                        
                        

                        <div class="col-sm-12 text-center" style="height:10px;"> </div>  

                    </div>
                    
                    <div class="modal-header">

                        <h2 class="modal-title" id="myModalLabel">&nbsp; </h2>
                    </div>
                    <div class="clearfix"></div>
                   
                </div>
            
        </div> 
    </div>

</div>
<script>
$(document).ready(function(){
   $(".abc").each(function()
{
    $(this).change(function()
    {
        $(".abc").prop('checked',false);
        $(this).prop('checked',true);
    });
}); 
    
});


</script>
