
<div class="container">
    <div class="row" align="center">
        <div class="col-sm-4" align="center" style="float:none !important; box-shadow:0 0 2px 0; margin:10px 0; ">

            <form role="form" method="post" action="<?php echo $this->url('user', array('action' => 'loginUser')) ?>">
                <div class="form-group">
                    <div class="modal-header">

                        <h2 class="modal-title" id="myModalLabel">Login</h2>
                    </div>
                    <div class="modal-body">
<?php 
//echo 'satya';
if ($this->flashMessenger()->hasMessages()) {

    echo '<div style="color: #800">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message[0];
    }

    echo '</div>';
}

?>
                        <div class="col-sm-12">
                            Email OR Mobile
                            <input type="text" name="login_email" id="login_email" class="form-control" />
                        </div>
                        <div class="col-sm-12">
                            Password
                            <input type="password" name="login_password" id="login_password" class="form-control" />
                        </div>

                        <div class="col-sm-12">

                            <input type="checkbox" name="rember" /><em>Remember me</em>
                        </div>

                        <div class="col-sm-6">

                            <button type="submit" name="login" id="login" class="btn btn-default btn-block popuplogingbut">Sign In</button>
                        </div>

                        <div class="col-sm-6" style="padding:0;">
                            <a type="submit" class="" style="cursor:pointer;">Forgot your password?</a>
                        </div>

                        <div class="col-sm-12 text-center">OR</div>

                        <div class="col-sm-12">New account 
                            <a class="btn btn-default btn-block popuplogingbut" href="<?php echo $this->basePath() ?>/user/signup"><?php echo $this->translate('Signup') ?></a>

                        </div>

                        <div class="col-sm-12 text-center" style="height:10px;"> </div>  

                    </div>
                    <div class="clearfix"></div>
                   
                </div>
            </form>
        </div> 
    </div>

</div>

