
<div class="container">
    <div class="row" align="center">
        <div class="col-sm-4" align="left" style="float:none !important; box-shadow:0 0 2px 0; margin:10px 0; margin-bottom:100px; ">

            <form role="form" method="post" action="<?php echo $this->url('user', array('action' => 'loginUser')) ?>">
                <div class="form-group">
                    <div class="modal-header">

                        <h2 class="modal-title" id="myModalLabel">Signup</h2>
                    </div>
                    <div class="modal-body">
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div style="color: #800">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message[0];
    }

    echo '</div>';
}

?>
                       <div class="col-sm-12">
                            User Name
                            <input type="text" name="User_name" id="User_name" class="form-control" />
                        </div>
                        
                          <div class="col-sm-12">
                            Password
                            <input type="password" name="login_password" id="login_password" class="form-control" />
                        </div>
                       
                        <div class="col-sm-12">
                            Email ID
                            <input type="text" name="login_email" id="login_email" class="form-control" />
                        </div>
                      
                      
                      <div class="col-sm-12">
                            Mobile
                            <input type="text" name="Mobile_signup" id="Mobile_signup" class="form-control" />
                        </div>
                      


                        <div class="col-sm-12 text-center">&nbsp;</div>

                        <div class="col-sm-12">
                            <a class="btn btn-default btn-block popuplogingbut" href="<?php echo $this->basePath() ?>/user/signup"><?php echo $this->translate('Signup') ?></a>

                        </div>

                        <div class="col-sm-12 text-center" style="height:10px;"> </div>  

                    </div>
                    <div class="clearfix"></div>
                   
                </div>
            </form>
        </div> 
    </div>

</div>

