
<div class="container" style="margin-bottom:100px;">
    <div class="row" align="center">
        <div class="col-sm-6" align="center" style="float:none !important; box-shadow:0 0 2px 0; margin:10px 0; ">

            
                <div class="form-group">
                    <div class="modal-header">

                        <h2 class="modal-title" id="myModalLabel">Signup</h2>
                    </div>
                    <div class="modal-body">

                        <div class="col-sm-6">
                         <a href="<?php echo $this->basePath() ?>/user/signup2">
                            <div class="btn btn-default btn-block popuplogingbut" style="background:#F30; padding:30px 0; font-size:18px; color:#fff; border-radius:50% !important; height:140px; width:140px;">
                           	 <img src="/images/metrimonial_icon.png" />
                            </div>
                            <h3 style="margin-top:5px;">Matrimonial User</h3>
                            </a>
                        </div>
                        <div class="col-sm-6">
                        <a href="<?php echo $this->basePath() ?>/user/signup2">
                        <div class="btn btn-default btn-block popuplogingbut" style="background:#F30; padding:30px 0; font-size:18px; color:#fff; border-radius:50% !important; height:140px; width:140px;">
                            <IMG src="/images/membership.png" />
                           </div> 
                           
                           <h3 style="margin-top:5px;">Membership User</h3>
                           </a>
                        </div>

                        <!--<div class="col-sm-12">

                            <input type="checkbox" name="rember" /><em>Remember me</em>
                        </div>-->

                       <!-- <div class="col-sm-6">

                            <button type="submit" name="login" id="login" class="btn btn-default btn-block popuplogingbut">Sign In</button>
                        </div>-->

                      <!--  <div class="col-sm-6" style="padding:0;">
                            <a type="submit" class="" style="cursor:pointer;">Forgot your password?</a>
                        </div>

                        <div class="col-sm-12 text-center">OR</div>

                        <div class="col-sm-12">New account 
                            <a class="btn btn-default btn-block popuplogingbut" href="<?php echo $this->basePath() ?>/user/signup"><?php echo $this->translate('Signup') ?></a>

                        </div>-->

                        <div class="col-sm-12 text-center" style="height:10px;"> </div>  

                    </div>
                    
                    <div class="modal-header">

                        <h2 class="modal-title" id="myModalLabel"> &nbsp;</h2>
                    </div>
                    <div class="clearfix"></div>
                   
                </div>
            
        </div> 
    </div>

</div>

