<style>
    .modal-dialog {
        width: 67%;
    }

    .activestatus{
        color:green;
        background:green;
        border-radius:30px; width:15px; height:15px;
        cursor:pointer

    }

    .de-activestatus{
        color:green;
        background:red;
        border-radius:30px; width:15px; height:15px;
        cursor:pointer;


    }



</style>


<?php 

// foreach ($branchs as $branch) {

// echo  $branch->branch_name."<br>";

// }

// echo "<pre>";
// print_r($branchs);
// die;

?>
<div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
            <!--<div class="alert alert-block alert-success">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i>Add Branch Master</strong>, </div>-->
            <!--<div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
            </div>-->
            <div class="row">
              <div class="col-xs-12">
                <h3  >Add Branch Master</h3>
                <div class="filter">
                 <div class="panel-body" style="padding:0 !important">
                  <div class="col-lg-6">View Records>></div>
                  </div>
                </div>
                <div class="portlet-body">
                    
                    <div id="myTabContent" class="tab-content">
                            <div class="tab-pane fade active in" id="home">
                                <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                                    <div class="row">
                                        <div class="form-group clearfix margintopbottom20">
                                            <label id="flight_nos" class="col-sm-1 col-sm-1updated control-label labelalign ">Select Country</label>
                                            <div class="col-sm-2 ">
                                                <select class="form-control" id="filter_country2" ftype="country">
                <option value="">Select country</option>
                <?php
                
//               \Zend\Debug\Debug::dump($filters_data);
//                    exit;
                foreach ($filters_data as $GrData) {
                    echo "<option value=" . $GrData->id . ">" . $GrData->countryName . "</option>";
                }
                ?>
            </select>
                                                
                                                <div class="col-sm-3" id="countrysearchresults" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;">
                                                </div>                                    
                                            </div>

                                            <label id="point_airport" class="col-sm-1 col-sm-1updated control-label labelalign ">Select State
                                            </label>
                                            <div class="col-sm-2">
                                                <select class="form-control" id="filter_state" ftype="state">
                                                </select>
                                            </div>

                                            <label id="flight_nos" class="col-sm-1 col-sm-1updated control-label labelalign ">Select City</label>
                                            <div class="col-sm-2 ">
                                                <select class="form-control" id="filter_city" ftype="city">
                                                </select>
                                            </div>  
                                            
                                            <label id="flight_nos" class="col-sm-1 col-sm-1updated control-label labelalign ">Select Branch</label>
                                            <div class="col-sm-2 ">
                                                <select class="form-control" id="filter_branch" ftype="branch">
                                                </select>
                                            </div> 

                                            <div class="col-sm-1  ">
                                                 <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search"   onclick="filterData2();">
                                            </div>
                                            <div class="col-sm-6 ">
                                               <!--<a id="showaddform" class="btn btn-red defaultbtnsearch searchBooking" href="#"> Add</a>-->
                                               <a class="btn btn-red defaultbtnsearch showaddForm" href="javascript:void(0);"> Add</a>
                                                
                                            </div>


                                        </div>
                                    </div>
                                    
                                </div>



                            </div>
                        </div>
                    
   
                </div>
                
                 
                  <div class="filter">
                   <div class="panel-body " style="padding:0 !important;">
                  <div class="col-lg-6" style="cursor:pointer;">Add Update Records>>
                  </div>
  
                  </div>
   
                </div>
                
                
                
          <div id="addForm" class="tab-content"></div>
          <div id="editForm" class="tab-content dontshow"></div>
                                            
                
                    <div class="clearfix"></div>
                  
                <div class="col-lg-12" style="background-color:#FFF;" id="radiosearch" fld="tbl_rustagi_branches">
                  
                  <div class="col-lg-1"><div class="radio">
                                                <label>
                                                    <input type="radio" value="1" id="optionsRadios1" name="optionsRadios" 
                                       onchange="RadioSearch($(this).val(), 'tbl_rustagi_branches', '<?php echo 
                                       $this->url('admin/branch', array('action'=>'ajaxradiosearch'))?>',
                                                   radioSearchResult2)" ><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-1"><div class="radio">
                                                <label>
                                                    <input type="radio" value="0" id="optionsRadios1" name="optionsRadios" onchange=
                                    "RadioSearch($(this).val(), 'tbl_rustagi_branches', '<?php echo $this->url
                                            ('admin/branch', array('action'=>'ajaxradiosearch'))?>', 
                                                        radioSearchResult2)"><strong>In-Active</strong>
                                                </label>
                                                
                                              
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="delselected('<?php echo $this->url('admin/branch', array('action'=>
                                    'delmultiple'))?>',delmultipleresp)">Delete Selected</button>                                              
                    </div>
                  </div> 
                  <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?php echo $this->url('admin/branch', array
                                    ('action'=>'changeStatusAll'))?>',statuschangeallresp,1)">Activate Selected</button>                                    
                    </div>
                  </div> 
                    <div class="col-lg-2 pull-right">
                        <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?php echo $this->url('admin/branch', array
                                    ('action'=>'changeStatusAll'))?>',statuschangeallresp,0)">De-Activate Selected</button>                                    
                        </div>
                    </div>
                 
                  
                  
                  </div>
                  
                  <div class="col-sm-12">


                </div>
                  
                <div class="col-md-12"  id="branch_data_list">
                    <?php echo $this->partial('admin/branch/branchList.phtml'); ?>
                 </div>
                    <div class="col-md-12" id="branch_search_list">
                        
                        
                        
                    </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
                
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 
          
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a>
</div></div>
<div id="viewBranchModel"></div>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<?php echo $this->inlineScript()->prependFile($this->basePath('/assets/js/branch.js')); ?>


<script>

            
            /**************Get State on select Country***************/
            $("#country").on('change', function () {
                //alert(1);
    var countryId = this.value;
            $.ajax({
            url: '<?php echo $this->basePath() ?>' + '/account/getStateName',
                    type: "POST",
                    dataType: "json",
                    data: {Country_ID: countryId},
                    beforeSend: function () {
                    $('#Loading_Request').show();
                    },
                    complete: function () {
                    $('#Loading_Request').hide();
                    },
                    success: function (resp) {
                    if (resp.Status == 'Success') {
                    $("#state").empty();
                            $("#branch_city_id").empty();
                            $("#state").append("<option value=''>Select State</option>");
                            $.each(resp.statelist, function (idx, obj) {
                            $("#state").append("<option value='" + obj["id"] + "'>" + obj["state_name"] + "</option>");
                            });
                    } else {
                    $("#state").empty();
                            $("#branch_city_id").empty();
                            alert("No States are available");
                    }
                    },
                    error: function (error) {
                    console.log(error);
                            alert(error);
                    }
            });
    });
            /*******************End******************/
            /*************Get City on Select State*************************************************/
            $("#state").on('change', function () {
    var stateId = this.value;
            $.ajax({
            url: '<?php echo $this->basePath() ?>' + '/account/getCityName',
                    type: "POST",
                    dataType: "json",
                    data: {State_ID: stateId},
                    beforeSend: function () {
                    $('#Loading_Request').show();
                    },
                    complete: function () {
                    $('#Loading_Request').hide();
                    },
                    success: function (resp) {
                    if (resp.Status == 'Success') {
                    $("#branch_city_id").empty();
                            $("#branch_city_id").append("<option value=''>Select City</option>");
                            $.each(resp.statelist, function (idx, obj) {
                            $("#branch_city_id").append("<option value='" + obj["id"] + "'>" + obj["city_name"] + "</option>");
                            });
                    } else {
                    $("#branch_city_id").empty();
                            alert("No Cities are Available");
                    }
                    },
                    error: function (error) {
                    console.log(error);
                            alert(error);
                    }
            });
    });
            /*******************End******************/
            
            /*************Get City on Select State*************************************************/
//$("#city").on('change', function(){
//var cityId=this.value;
//$.ajax({
//    url:'<?php //echo $this->basePath()?>'+'/user/getRustagiBranch',
//    type:"POST",
//dataType:"json",
//    data:{City_ID:cityId},
//    beforeSend: function(){
//            $('#Loading_Request').show();
//    },
//    complete: function(){
//            $('#Loading_Request').hide();
//    },
//    success:function(resp){
//$("#branch_other").hide();
//
//if(resp.Status=='Success'){
//$("#branch_ids").empty();
//$("#branch_ids").append("<option value=''>Select Branch</option>");
//$.each(resp.statelist, function(idx, obj) {                            
//$("#branch_ids").append("<option value='"+obj["branch_id"]+"'>"+obj["branch_name"]+"</option>");
//});
//}else{
//$("#branch_ids").empty();
//alert("No Branches are Available");
//$("#branch_other").show();
//}
//$("#branch_ids").append("<option value='Other'>Others</option>");
//    },
//    error:function(error){
//            console.log(error);	
//            alert(error);			
//    }
//});	
//});
/*******************End******************/
$(".showaddForm").click(function(){

$.ajax({
            url: '<?php echo $this->basePath() ?>/admincontrol' + '/branch/add',
                    type: "POST",
                    dataType: "html",
                    //data: {State_ID: stateId},
                    beforeSend: function () {
                    $('#Loading_Request').show();
                    },
                    complete: function () {
                    $('#Loading_Request').hide();
                    },
                    success: function (resp) {
                    //alert(resp);
                    $("#editForm").fadeOut();
                    $("#addForm").html(resp);
                    },
                    error: function (error) {
                    console.log(error);
                            alert(error);
                    }
            });
    
});
</script>