                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                           <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.branchId)" > </th>
                        <th>S. No.</th>
                        <th class="hidden-480">Country</th>
                        <th class="hidden-480">State</th>
                        <th class="hidden-480">City</th>
                        <th>Branch Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        <!--<th class="hidden-480">Modified By</th>-->
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
					  $i=1;
                       if (count($results) > 0) {                   
                      foreach ($results as $branch) {
//                          echo  "<pre>";
//                          print_r($branch);exit;
                      
                      ?>
                      <tr>
                        <td><input type="checkbox" value="<?=$branch['branch_id']?>" class="checkme" name="checkme[]"> </td> 
                       <td><?= $i ?></td>  
                       <td><?= $branch['country_name']?></td> 
                       <td><?= $branch['state_name']?></td> 
                       <td><?= $branch['city_name']?></td> 
                        <td><?php echo $branch['branch_name']?></td>                       
                        <td class="hidden-480"><?=$branch['modified_date']?></td>
                        <td class="hidden-480"><?php echo $branch['username'];?></td>
                        
                        <td class="hidden-480">
						<!--<?php echo ($branch['is_active']==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($branch['is_active']==1)? 'Active': 'In-Active';
                        $statuscolor = ($branch['is_active']==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$branch->branchId?>,<?= ($branch['is_active']==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/branch', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        <!--<td class="hidden-480"><?php //echo ($branch->modifiedBy==1)? 'Admin': 'NotByAdmin'; ?></td>-->
                        <td><div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('admin',array('controller'=>'branch','action'=>'view','id'=>$branch['branch_id'])); ?>">
                         <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataByBranchId('<?php echo $this->url
                                                           ('admin/branch', array('action'=>'viewById','id'=>$branch['branch_id'])); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                         
                         <a class="green" href="javascript:void(0);" onclick="editbox(<?= 
                                                   $branch['branch_id'] ?>, '<?php echo $this->url('admin/branch', array('action' => 
                                                       'edit', 'id' => $branch['branch_id']));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 
                          <a class="red" href="<?php echo $this->url('admin/branch',array('action'=>'delete','id'=>
                              $branch['branch_id'])); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa 
                                                                                             fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      
                      
                      
                      <?php 
                      $i++;
                    }
                  } else
        echo" <tr>
                         
                       <td colspan=9><center><h2>No data available</h2></center></td></tr>";
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                

            
             