<table  width="100%" style="border:none !important;">
<tbody>
<?php
if(count($branchs)>0){
	$i=1;
 foreach ($branchs as $branch) {
?>


<tr>
<td>
<a href="javascript:void(0);" id="branchsearch<?=$i;?>" onclick="grabvalues2('<?=$branch->branch_name?>','<?=$branch->id?>','<?=$parentname?>');"><?= $branch->branch_name?></a>
</td>
</tr>
<?php
$i++;
}
}
else echo "<p>No matched search</p>";
?>
</tbody>
</table>