
<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar') ?>

 
</div>
<?php //echo $this->partial('flash-message'); ?>


<div class="col-sm-9 width80per">
<div class="upcoming-events" style="line-height:23px;">
<h2>Why Should we register on Rustagi Samaj</h2> 

Rustagi Samaj is a community site which connects all the Rustagi, Rastogi, Rohtagi community across the globe.<br />
<br />

In Present Modern Life due to urbanization in the society, new Generation do not know about the community, Through Rustagi Samaj people can maintain details about their Family’s and details about Elders with Photos as well as other details 
<br />
<br />
<h2>Rustagi Samaj free services:</h2>
<ul>
	<li>
Free Matrimonial Registration</li>
<li> 
Free contact details of the community people </li>
	<li>You can easily filter search for any person in the community</li>
	<li>Free information about the Events and News of the community</li>
	<li>Free Obituary posting </li>
	<li>Free just born information posting</li>
	<li>Free Jokes, Poems and sms</li>
	<li>Free Devotional, Health & Food posts</li>
	<li>List of community achievers </li>
	<li>View popular post’s in the community</li>
	<li>Post Success Story   </li>
	<li>Post your suggestions</li>
	<li>Get Attractive offers from Advertisers </li>
</ul>

<h2>People can search for a member by different methods:</h2>
	<ul>
    <li>Name/ Member ID of the member</li>
	<li>Father’s Name </li>
	<li>Area of residence</li>
	<li>Profession </li>
	<li>Income slab</li>
	<li>Age</li>
	<li>Height </li>
</ul>
<h2>Benefits of Registering on Rustagi Samaj:</h2>
<ul>
	<li>You will be able to know your community </li>
	<li>You can manage your profile and use your profile for socialization </li>
	<li>Log in Minimum 20 Days in a Months & Get Free Gift Vouchers</li>
	<li>Complete your profile & Avail Free Gift</li>
	<li>Avail Special deals on Regular Basis by Publishers/ Advertisers</li>
	</ul>
    <h2>Rustagi Samaj for Matrimonial match:</h2>
<ul>
	<li>Register for free for Matrimonial search</li>
	<li>Filter search your partner to have the best Match </li>
</ul>
<h2 class="">Benefits of Advertising on Rustagi Samaj</h2>
	<ul>
    	<li>Your Advert will be seen by Millions of People on Internet, Easy to generate Leads</li>
        <li>Your Company/ Business details would also be listed on Search Engines - Google, Yahoo, Bing, Etc.</li>
        <li>You can Add, Modify or Delete your Advert anytime and from anywhere</li>
        <li>Your Company/ Business will get Noticed by people and will attract more Clients</li>
        <li>Rustagi Samaj is a Dynamic Portal, which can be browsed on all platforms. – Computer, Tablet, Mobile, etc.</li>
        <li>Through Rustagi Samaj your Company/ Business can reach more people Easily & Fast as compared to Print Media</li>
    </ul>
    
   <h2> Why Paid Membership:</h2>

Upgrade your Matrimonial membership to find the perfect partner! With paid membership, you can connect to members seemlessly with your choices and get more responses for yourself.
<br />
<br />

<h2>Benefits:</h2>
<ul>
	<li>Send personal messages to members you like </li>
	<li>Chat with other members</li>
	<li>View verified contact details of members </li>
	<li>Show your contact details for faster response </li>
	<li>Quick response service </li>
	<li>Match free horoscope</li>
</ul>
	                    
</div>

<div class="clearfix"></div>

<div class="featured-list" style="width:95%; padding-left:67px;">
<ul id="flexiselDemo2">
<li style="width:100%;">
<a href="<?php echo $this->basePath();?>/pages/gallery" style="float:left; padding:0;" class="col-sm-4">
<div class="col-xs-5"><img src="<?php echo $this->basePath('images/gallery-thumb.jpg'); ?>" class="img-responsive" /></div>
<div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('PHOTO GALLERY') ?></h2></div>
</a>

<a href="<?php echo $this->basePath();?>/pages/about" style="float:left; padding:0;" class="col-sm-4">
<div class="col-xs-5"><img src="<?php echo $this->basePath('images/about-us-thumb.jpg'); ?>" class="img-responsive" /></div>
<div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('ABOUT RUSTAGI SAMAJ') ?></h2></div>
</a>

<a href="<?php echo $this->basePath();?>/matrimonial" style="float:left; padding:0;" class="col-sm-4">
<div class="col-xs-5"><img src="<?php echo $this->basePath('images/matrimonial.jpg'); ?>" class="img-responsive" /></div>
<div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('MATRIMONIAL') ?></h2></div>
</a>
</li>

<li>
<a href="<?php echo $this->basePath();?>/pages/gallery" class="col-sm-12" style="width:100%; padding:0;">
<img src="<?php echo $this->basePath('images/rustagi_ad.jpg'); ?>" class="img-responsive" style="width:100%;" />
</a>
</li>
</ul>
</div>


<div class="clearfix"></div>

</div>