
<div class="col-sm-3 col-sm-3-new width20per forslyder">
    <?php echo $this->partial('layout/sidebar') ?>


</div>
<?php //echo $this->partial('flash-message'); ?>


<div class="col-sm-9 width80per">
    <div class="upcoming-events">
        <span class="bar">&nbsp;</span>
        <h2 class="text-center">UPCOMING EVENTS</h2>

<?php //\Zend\Debug\Debug::dump($this->MyHelper()->getFamilyInfoById('135')->familyInfoArray)?>
        <?php //echo $this->MyHelper()->getFamilyInfoById(135)->familyInfoArray['father_name'] ?>


        <ul id="flexiselDemo1">
            <?php if (count($this->Upcoming_events) > 0) {
                foreach ($Upcoming_events as $event) {
                    ?>

                    <li>
                        <a href="#">
                            <div class="col-xs-2">
                                <span class="text14"><?= date("M", strtotime($event->event_date)); ?></span>
                                <span class="text28"><?= date("d", strtotime($event->event_date)); ?></span>
                            </div>
                            <div class="col-xs-10">
                                <p class="lead"> <?= $event->event_name ?><?= date("Y", strtotime($event->event_date)); ?></p>
                                <p>प्रस्तुत करता - रुस्तगी सभा डेल्ही रजिस्टर्ड,<br> दिनांक - <?= date("d-M-Y", strtotime($event->event_date)); ?>,<br> <?= date("l", strtotime($event->event_date)); ?> - AM <?= date("h:i", strtotime($event->start_time)); ?> बजे से PM ८ बजे तक,<br> स्थान - <?= $event->venue ?>  </p>
                            </div>
                        </a>
                    </li>
                <?php }
            } else {
                ?> 
                <span style="text-align:center;font-weight:bold;font-size:16px;color:cornflowerblue;">No Data available</span>
<?php } ?>


        </ul>                   

    </div>

    <div class="clearfix"></div>

    <div class="featured-list addslyder">
        <ul id="flexiselDemo2">
            <li class="cssmobile">
                <a href="<?php echo $this->basePath(); ?>/pages/gallery" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/gallery-thumb.jpg'); ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('PHOTO GALLERY') ?></h2></div>
                </a>
            </li>

            <li class="cssmobile">
                <a href="<?php echo $this->basePath(); ?>/pages/gallery" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/gallery-thumb.jpg'); ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('PHOTO GALLERY') ?></h2></div>
                </a>
            </li>

            <li class="cssmobile">
                <a href="<?php echo $this->basePath(); ?>/pages/gallery" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/gallery-thumb.jpg'); ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('PHOTO GALLERY') ?></h2></div>
                </a>
            </li>

            <li class="cssfull">
                <a href="<?php echo $this->url('photo-gallery') ?>" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/gallery-thumb.jpg'); ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('PHOTO GALLERY') ?></h2></div>
                </a>

                <a href="<?php echo $this->url('about') ?>" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/about-us-thumb.jpg'); ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('ABOUT RUSTAGI SAMAJ') ?></h2></div>
                </a>

                <a href="<?php echo $this->basePath() ?>/matrimonial" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/matrimonial.jpg'); ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('MATRIMONIAL') ?></h2></div>
                </a>
            </li>

            <li>
                <a href="#" class="col-sm-12" style="width:100%; padding:0;">
                    <img src="<?php echo $this->basePath('images/aira_1.jpg'); ?>" class="img-responsive" style="width:100%;" />
                </a>
            </li>
        </ul>
    </div>


    <div class="clearfix"></div>
<?php if (count($this->ExecMembers) > 0) { ?>
        <div class="profile-list">
            <h2><?php echo $this->translate('EXECUTIVE COMMITTEE MEMBERS') ?></h2>
            <ul id="flexiselDemo3">
    <?php foreach ($ExecMembers as $execmem)  { ?>

                    <li class="homepagelicls">
                        <div id="f1_container" align="center">
                            <a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $execmem['uid'] ?>">
                                <div id="f1_card" class="shadow">
                                    <div class="front face profile-pic">
                                    <a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $execmem['uid'] ?>">        
                                        <img src="<?php
                                        if ($execmem['profile_photo'] != '') {
                                            echo $this->basePath() . '/uploads/' . $execmem['profile_photo'];
                                        } else {
                                            if ($execmem['gender'] == 'Male') {
                                                echo $this->basePath() . '/img/default_user.png';
                                            } else {
                                                echo $this->basePath() . '/img/default_user.png';
                                            }
                                        }
                                        ?>"/>
                                    </a>    

                                    </div>
                                    <div class="back face center" align="center" style="vertical-align:middle;">
                                        <span style="font-size:9px;">Father</span><br />
        <?php echo $execmem['father_name'] ?> 
                      <!-- <?php echo ($execmem['age'] > 0) ? "Age:" . $execmem['age'] : ""; ?> <br>-->

          <!-- <?php echo $execmem['native_place'] ?> <br> -->
                                    </div>
                                </div>

                            </a>
                        </div>           
                        <div class="profile-content">
                            <h4 style="text-align:center !important; margin-bottom:0 !important; height:14px;"><?php echo $this->MyHelper()->setReplaceString($execmem['full_name'] . ' '.$execmem['last_name']) ?></h4>
                            <p style="text-align:center !important; text-transform:capitalize; margin-bottom:2px;"><?php echo $execmem['category_name'] ?><!--, <?php echo $execmem->city_name ?>--></p>
                            <label>      
                                <a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $execmem['uid'] ?>" class="btn btn-default homemore">More Info</a>
                            </label>    
                        </div>
                    </li>

        <?php } ?>
            </ul>
        </div>
<?php } ?>



    <div class="clearfix"></div>

            <?php if (count($this->GroomData) > 0) { ?>
        <div class="profile-list">
            <h2><?php echo $this->translate('MEMBERS') ?></h2>
            <ul id="flexiselDemo4">
    <?php foreach ($GroomData as $GrData)  { ?>
                    <li class="homepagelicls">
                        <div id="f1_container" align="center">
                            <a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $GrData['uid'] ?>">
                                <div id="f1_card" class="shadow">
                                    <div class="front face profile-pic">
                                    <a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $GrData['uid'] ?>" >
                                        <img src="<?php
                                        if ($GrData['profile_photo'] != '') {
                                            echo $this->basePath() . '/uploads/' . $GrData['profile_photo'];
                                        } else {
                                            if ($GrData['gender'] == 'Male') {
                                                echo $this->basePath() . '/img/default_user.png';
                                            } else {
                                                echo $this->basePath() . '/img/default_user.png';
                                            }
                                        }
                                        ?>"/></a>

                                    </div>
                                    <div class="back face center" align="center">
                                        <span style="font-size:9px;">Father</span><br />
                        <?php echo $GrData['father_name'] ?> <br>
                    <!-- <?php echo ($GrData['age'] > 0) ? "Age:" . $GrData['age'] : ""; ?> <br>-->
                      <!-- <?php echo $execmem->native_place ?> <br> -->
                                    </div>
                                </div>

                            </a>
                        </div>          
                        <div class="profile-content">
                            <h4 style="text-align:center !important;  margin-bottom:0 !important; height:14px;"><?php echo $this->MyHelper()->setLimitCharacter($GrData['full_name'] .' '. $GrData['last_name']);  ?></h4>
                            <p style="text-align:center !important; margin-bottom:2px;"><?php echo $GrData['profession'] ?><!--<?php echo $GrData['city_name'] ?>--></p>
                            <label> 
                                <a href="<?php echo $this->basePath() ?>/membership/profile-view?member_id=<?php echo $GrData['uid'] ?>" class="btn btn-default homemore">More Info</a>
                            </label>
                        </div>
                    </li>	


        <?php } ?>
            </ul>

        </div>			
    <?php } ?>




            <?php if (count($this->MatriData) > 0) { ?>
        <div class="profile-list">
            <h2><?php echo $this->translate('BRIDE') ?></h2>
            <ul id="flexiselDemo6">
                <?php
                foreach ($MatriData as $MaData) {
                   
                    ?>
                    <li class="homepagelicls">
                        <div id="f1_container" align="center">
                            <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?bride_id=<?php echo $MaData['uid'] ?>">
                                <div id="f1_card" class="shadow">
                                    <div class="front face profile-pic">

                                        <img src="<?php
                                        if ($MaData['image_name'] != '') {
                                            echo $this->basePath() .MATRIMONIAL_IMAGE_PATH . $MaData['image_name'];
                                        } else {
                                            echo $this->basePath() . '/img/default_user.png';
                                        }
                                        ?>"/>

                                    </div>
                                    <div class="back face center" align="center">
                                        <span style="font-size:9px;">Father</span><br />
        <?php //echo $this->MyHelper()->getFamilyInfoById($MaData['uid'])->familyInfoArray['father_name'] ?>
                        <?php echo $this->MyHelper()->getFatherInfoById($MaData['uid']);?> <br>
                    <!-- <?php echo ($MaData['age'] > 0) ? "Age:" . $MaData['age'] : ""; ?> <br>-->
                      <!-- <?php echo $execmem->native_place ?> <br> -->
                                    </div>
                                </div>

                            </a>
                        </div>          
                        <div class="profile-content">
                            <h4 style="text-align:center !important;  margin-bottom:0 !important;"><?php echo $this->MyHelper()->setLimitCharacter( $MaData['full_name'] .' '.$MaData['last_name']); ?></h4>
                            <p style="text-align:center !important; margin-bottom:0 !important;"><?php echo ($MaData['age'] > 0) ? "" . $MaData['age']."" : ""; ?>,<?php if($MaData['height']!="")echo $this->MyHelper()->getHeightById($MaData['height'])['height']; ?></p>
                            <p style="text-align:center !important; margin-bottom:0 !important;"><?php echo $MaData['profession_name'] ?><!--<?php echo $MaData['city_name'] ?>--></p>
                            <label> 
                                <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?bride_id=<?php echo $MaData['uid'] ?>" class="btn btn-default homemore">More Info</a>
                            </label>
                        </div>
                    </li>	


    <?php } ?>
            </ul>
        </div>
<?php } ?>
    
    
    
    
    <?php if (count($this->MatriGroomData) > 0) { ?>
        <div class="profile-list">
            <h2><?php echo $this->translate('GROOM') ?></h2>
            <ul id="flexiselDemo7">
                <?php
                foreach ($MatriGroomData as $MaData) {
                    ?>
                    <li class="homepagelicls">
                        <div id="f1_container" align="center">
                            <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $MaData['uid'] ?>">
                                <div id="f1_card" class="shadow">
                                    <div class="front face profile-pic">
                                        <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $MaData['uid'] ?>" >
                                        <img src="<?php
                                        if ($MaData['image_name'] != '') {
                                            echo $this->basePath() .MATRIMONIAL_IMAGE_PATH . $MaData['image_name'];
                                        } else {
                                            echo $this->basePath() . '/img/default_user.png';
                                        }
                                        ?>"/>
                                        </a>

                                    </div>
                                    <div class="back face center" align="center">
                                        <span style="font-size:9px;">Father</span><br />
        <?php //echo $this->MyHelper()->getFamilyInfoById($MaData['uid'])->familyInfoArray['father_name'] ?>
        <?php echo $this->MyHelper()->getFatherInfoById($MaData['uid']);?> <br>
                    <!-- <?php echo ($MaData['age'] > 0) ? "Age:" . $MaData['age'] : ""; ?> <br>-->
                      <!-- <?php echo $execmem->native_place ?> <br> -->
                                    </div>
                                </div>

                            </a>
                        </div>          
                        <div class="profile-content">
                            <h4 style="text-align:center !important; margin-bottom:0 !important;"><?php echo $this->MyHelper()->setLimitCharacter($MaData['full_name'] .' '.$MaData['last_name']) ?></h4>
                            <p style="text-align:center !important; margin-bottom:0 !important;"><?php echo ($MaData['age'] > 0) ? "" . $MaData['age']."" : ""; ?>,<?php if($MaData['height']!="")echo $this->MyHelper()->getHeightById($MaData['height'])['height']; ?></p>
                            <p style="text-align:center !important; margin-bottom:0 !important;"><?php echo $MaData['profession_name'] ?><!--<?php echo $MaData['city_name'] ?>--></p>
                            <label> 
                                <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $MaData['uid'] ?>" class="btn btn-default homemore">More Info</a>
                            </label>
                        </div>
                    </li>	


    <?php } ?>
            </ul>
        </div>
<?php } ?>
    
    

</div>