<style>
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    border-top: 1px solid #ddd;
    line-height: 1.42857;
    padding: 7px;
    vertical-align: top;
}

.sidebar-nav li {
    line-height: 32px;
}
</style>
<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-about') ?>
</div>

<div class="col-sm-9 width80per">
   <!-- <div class="upcoming-events"> <span class="bar">&nbsp;</span>-->
    <h2 class="text-left">Membership Packages</h2>
    <div class="col-lg-12"> 
      
      <!--Sight Add-->
      <div class="sightcont">
        <div class="sightinc" style="">
        
       <!-- <div class="col-sm-3 pull-right"><a href="#" class="sadd">Compare Plan</a></div>
        </div>-->
        <div class="sightadd">
          
          
          <div class="col-lg-2 col-lg-2fee " style="margin-top:5px; border:none;" onClick="$(this).parent().find('.sdesc').fadeIn('medium')" align="center"> 
          
        
            
          </div>
         
          
          <div class="col-lg-2 col-lg-2fee col-lg3fee" style="margin-top:5px;" align="center"> 
          
          <a href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;" ><img src="<?php echo $this->basePath()?>/images/free_pack.png" class="img-responsive" alt=""></a>
            
           <h3 style="padding-bottom:0; padding-top:0;">Free</h3><br />

            <p align="center" style="text-align:center;">Free <span>For 12 Months</span> </p>
          <!--  <div class="col-sm-6" onClick="addSightSeeing($(this).parent(),7)"><a class="sadd" href="#">Compare</a></div>-->
             <div class="col-sm-12 col-sm-12fee" align="center"><a href="#" class="sadd">Buy&nbsp;Now</a></div>
             
          </div>
          
          
          <div class="col-lg-2 col-lg-2fee col-lg3fee " style="margin-top:5px;" align="center"> 
          
          <a href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;" ><img src="<?php echo $this->basePath()?>/images/silver_pack.jpg" class="img-responsive"  alt=""></a>
            
            <h3 style="padding-bottom:0; padding-top:0;">Classic/ Silver</h3><br />

            <p align="center" style="text-align:center;">Free <span>For 4 Months</span> </p>
           <!-- <div class="col-sm-6" onClick="addSightSeeing($(this).parent(),7)"><a class="sadd" href="#">Compare</a></div>-->
             <div class="col-sm-12 col-sm-12fee" align="center"><a href="#" class="sadd">Buy&nbsp;Now</a></div>
            <!-- <div class="col-sm-12 "><a href="javascript:void(0)" class="" id="readmore2">Read More..</a></div>-->
          </div>
          
          <div class="col-lg-2 col-lg-2fee col-lg3fee" style="margin-top:5px;" align="center"> 
          
          <a href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;" ><img src="<?php echo $this->basePath()?>/images/gold_pack.jpg" class="img-responsive"  alt=""></a>
          <h3 style="padding-bottom:0; padding-top:0;">Cl. advantage/ Gold</h3>
            <p align="center" style="text-align:center;">Free <span>For 6 Months</span> </p>
            <!--<div class="col-sm-6" onClick="addSightSeeing($(this).parent(),7)"><a class="sadd" href="#">Compare</a></div>-->
             <div class="col-sm-12 col-sm-12fee" align="center"><a href="#" class="sadd">Buy&nbsp;Now</a></div>
             
          </div>
          
          <div class="col-lg-2 col-lg-2fee col-lg3fee" style="margin-top:5px;" align="center"> 
          
          <a href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;" ><img src="<?php echo $this->basePath()?>/images/diamond_pack.jpg" class="img-responsive" alt=""></a>
            
           <h3 style="padding-bottom:0; padding-top:0;">Cl. premium/ Diamond</h3>
            <p align="center" style="text-align:center;">Free <span>For 12 Months</span> </p>
          <!--  <div class="col-sm-6" onClick="addSightSeeing($(this).parent(),7)"><a class="sadd" href="#">Compare</a></div>-->
             <div class="col-sm-12 col-sm-12fee" align="center"><a href="#" class="sadd">Buy&nbsp;Now</a></div>
             
          </div>
          
          
          
          
          
          
        </div>
        
        
      </div>
      
      <!--Sight Add End--> 
      
      <div class="col-sm-12">
      	<div class="row" id="package1">
      
        <!--right table price start--> 
       <div class="" style="padding:0;">
                  <!--   Kitchen Sink -->
                    <div class="panel panel-default">
                      
                        <div class="panel-body" style="padding:0 !important;">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    
                                    <tbody>
                                        <tr>
                                        	<td align="left"> <a href="#">Send unlimted personal msg</a></td>
                                            
                                            <td  align="center" class="col-lg-2fee"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                             <td align="center" class="col-lg-2fee"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                            <td  align="center" class="col-lg-2fee"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                            <td  align="center" class="col-lg-2fee"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                            
                                        </tr>
                                        <tr>
                                        	<td align="left"> <a href="#">Access verified contact Details </a></td>
                                             <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                             <td align="center">45</td>
                                             <td align="center">55</td>
                                             <td align="center">70</td>
                                            
                                        </tr>
                                        <tr>
                                        <td align="left"> <a href="#">Send SMS</a></td>
                                         <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                          <td align="center">45</td>
                                          <td align="center">55</td>
                                          <td align="center">60</td>
                                                                                        
                                        </tr>
                                        <tr>
                                        <td align="left">  <a href="#">Chat instantly</a></td>
                                         <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                            <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          
                                        </tr>
                                        <tr>
                                        <td align="left"> <a href="#">View horoscope</a></td>
                                          <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                         <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           
                                        </tr>
                                        <tr>
                                        <td align="left"> <a href="#">Profile Highlighter </a></td>
                                         <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                          <td align="center">2Months limited</td>
                                          <td align="center">3Months limited</td>
                                         
                                        </tr>
                                        <tr>
                                        <td align="left"> <a href="#">Priority in search </a></td>
                                       <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                         <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                        
                                        </tr>
                                        <tr>
                                        <td align="left"> <a href="#">Paid tag for high response</a></td>
                                          <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                        <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                        
                                        </tr>
                                        <tr>
                                        <td align="left"> <a href="#">Prominent display in search/ featured profile</a></td>
                                          <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                          <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                        
                                        </tr>
                                        <tr>
                                        	<td align="left"> <a href="#">Advanced privacy</a></td>
                                           <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                         
                                        </tr>
                                        
                                        <tr>
                                        	<td align="left"> <a href="#">Alerts</a></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                         
                                        </tr>
                                        
                                        <tr>
                                        	<td align="left"> <a href="#">Response booster*</a></td>
                                           <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cros-box.jpg" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                         
                                        </tr>
                                        
                                        <tr>
                                        	<td align="left"> <a href="#">See who viewed your profile </a></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                           <td align="center"><img src="images/cehck-box.png" width="15" height="15" alt=""></td>
                                         
                                        </tr>
                                        
                                       
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                     <!-- End  Kitchen Sink -->
                </div>
         <!--End table price start--> 
      </div>
    </div>
  </div>
      </div>
      </div>
    </div>
  </div>
  
  </div>
<script type="text/javascript">
$('.popover-markup>.trigger').popover({
    html: true,
    title: function () {
        return $(this).parent().find('.head').html();
    },
    content: function () {
        return $(this).parent().find('.content').html();
    }
});
</script> 
<script type="text/javascript" >
document.getElementById('fromcity').selectedIndex=0;
document.getElementById('packform').reset();

var sightarray=new Array();
sightarray.push(1);
function removeSightSeeing(el,id){
  var btn="<div onclick='addSightSeeing($(this).parent(),"+id+")' class='sadd'>Add</div>";
  el.find('.sremove').remove();
  el.append(btn);
  $('.sightadd').append(el);
  sightarray.splice(sightarray.indexOf(id),1);
  document.getElementById('selsight').value=sightarray.toString();
  console.log(sightarray);
  console.log(document.getElementById('selsight').value);
}

function addSightSeeing(el,id){
	//alert(el);
	//alert(id);
  var btn="<div onclick='removeSightSeeing($(this).parent(),"+id+")' class='sremove'>Remove</div>";
  el.find('.sadd').remove();
  el.append(btn);
  $('.sightinc').append(el);
  sightarray.push(id);
  document.getElementById('selsight').value=sightarray.toString();
  console.log(sightarray);
  console.log(document.getElementById('selsight').value);
}
</script>

//<script>
//$(document).ready(function() {
//    
//$("#readmore1").click(function(){
//	 $("#package1").show();
//	$("#package2").hide();
//	$("#package3").hide();
//	$("#package4").hide();
//	
// 	
//});
//
//$("#readmore2").click(function(){
//    $("#package1").hide();
//	$("#package2").show();
//	$("#package3").hide();
//	$("#package4").hide();
//	
//	
//});
//
//$("#readmore3").click(function(){
//    $("#package1").hide();
//	$("#package2").hide();
//	$("#package3").show();
//	$("#package4").hide();
//	
//});
//
//$("#readmore4").click(function(){
//    $("#package1").hide();
//	$("#package2").hide();
//	$("#package3").hide();
//	$("#package4").show();
//	
//});
//});
//
//</script>